# @generated manually from src/bindings/python/Autograd.cpp
# mypy: disable-error-code="type-arg"
# mypy: allow-untyped-defs
# ruff: noqa: F401,PYI054

from collections.abc import Callable, Sequence
from typing import Any

from tensorplay._C import Node, TensorBase

class PyNode(Node):
    def __init__(self, ctx: Any) -> None: ...
    @property
    def _py_ctx(self) -> Any: ...
    def add_next_edge(self, next_node: Node | None, input_nr: int = 0) -> None: ...
    def add_post_hook(
        self,
        hook: Callable[[list[TensorBase], list[TensorBase]], Sequence[TensorBase]],
    ) -> None: ...
    def add_pre_hook(
        self,
        hook: Callable[[list[TensorBase]], Sequence[TensorBase]],
    ) -> None: ...
    def attach_outputs(self, outputs: Any) -> None: ...
    def register_hook(self, hook: Callable) -> None: ...
    def register_prehook(self, hook: Callable) -> None: ...
    def set_materialize_grads(self, value: bool) -> None: ...

class _InferenceMode:
    def __init__(self, mode: bool = True) -> None: ...
    def __enter__(self) -> _InferenceMode: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...

def backward(tensors: Sequence[TensorBase],
             grad_tensors: Sequence[TensorBase] | None = None,
             retain_graph: bool | None = None,
             create_graph: bool = False) -> None: ...
def grad(outputs: Sequence[TensorBase],
         inputs: Sequence[TensorBase],
         grad_outputs: Sequence[TensorBase] | None = None,
         retain_graph: bool | None = None,
         create_graph: bool = False,
         allow_unused: bool = False) -> tuple: ...
def collect_next_edges(arg0: TensorBase) -> list[tuple[Node, int]]: ...
def custom_function_apply(ctx_factory: object,
                          node_factory: object,
                          forward_fn: object,
                          setup_ctx_fn: object | None,
                          args: Sequence) -> tuple[object, object, tuple, bool, object]: ...
def run_custom_function_forward(ctx: object,
                                forward_fn: object,
                                setup_ctx_fn: object | None,
                                args: Sequence) -> object: ...
def setup_custom_function_graph(node: object,
                                args: Sequence) -> tuple[list, bool]: ...
def is_grad_enabled() -> bool: ...
def set_grad_enabled(arg0: bool) -> None: ...
def is_inference_mode_enabled() -> bool: ...
def is_anomaly_enabled() -> bool: ...
def is_anomaly_check_nan_enabled() -> bool: ...
def set_anomaly_enabled(enabled: bool, check_nan: bool = True) -> None: ...
