

class _CudaDeviceProperties:
    @property
    def name(self) -> str: ...

    @property
    def major(self) -> int: ...

    @property
    def minor(self) -> int: ...

    @property
    def total_memory(self) -> int: ...

    @property
    def multi_processor_count(self) -> int: ...

    def __repr__(self) -> str: ...

class _CudaEvent:
    def __init__(self, enable_timing: bool = False, blocking: bool = False, interprocess: bool = False) -> None: ...
    @property
    def device(self): ...
    @property
    def cuda_event(self) -> int: ...
    def record(self, stream: _CudaStream | None = None) -> None: ...
    def wait(self, stream: _CudaStream | None = None) -> None: ...
    def query(self) -> bool: ...
    def synchronize(self) -> None: ...
    def elapsed_time(self, end_event: _CudaEvent) -> float: ...

class _CudaStream:
    def __init__(self, device: int = -1, priority: int = 0) -> None: ...
    @property
    def device(self): ...
    @property
    def device_index(self) -> int: ...
    @property
    def cuda_stream(self) -> int: ...
    @property
    def priority(self) -> int: ...
    def query(self) -> bool: ...
    def synchronize(self) -> None: ...
    def wait_event(self, event: _CudaEvent) -> None: ...
    def wait_stream(self, stream: _CudaStream) -> None: ...
    def record_event(self, event: _CudaEvent | None = None) -> _CudaEvent: ...

def get_version() -> int: ...

def is_available() -> bool: ...

def device_count() -> int: ...

def current_device() -> int: ...

def set_device(device: int) -> None: ...

def get_device_name(device: int = 0) -> str: ...

def get_device_capability(device: int = 0) -> tuple[int, int]: ...

def get_device_properties(device: int = 0) -> _CudaDeviceProperties: ...

def synchronize(device: int = -1) -> None: ...

def memory_allocated(device: int = -1) -> int: ...

def memory_reserved(device: int = -1) -> int: ...

def max_memory_allocated(device: int = -1) -> int: ...

def max_memory_reserved(device: int = -1) -> int: ...

def reset_max_memory_allocated(device: int = -1) -> None: ...

def reset_peak_memory_stats(device: int = -1) -> None: ...

def empty_cache() -> None: ...

def manual_seed(seed: int) -> None: ...

def manual_seed_all(seed: int) -> None: ...

def current_stream(device: int = -1) -> _CudaStream: ...

def default_stream(device: int = -1) -> _CudaStream: ...

def set_stream(stream: _CudaStream) -> None: ...

def get_stream_from_pool(priority: int = 0, device: int = -1) -> _CudaStream: ...

def get_stream_priority_range() -> tuple[int, int]: ...

def _sleep(cycles: int) -> None: ...
