# @generated manually from src/bindings/python/Device.cpp
# mypy: disable-error-code="type-arg"
# mypy: allow-untyped-defs
# ruff: noqa: F401,PYI054

from typing import Any

def current_device() -> int: ...
def device_count() -> int: ...
def empty_cache() -> None: ...
def get_device_capability(device: int = 0) -> tuple: ...
def get_device_name(device: int = 0) -> str: ...
def get_device_properties(device: int = 0) -> Any: ...
def get_driver_version() -> int: ...
def get_version() -> int: ...
def is_available() -> bool: ...
def manual_seed(seed: int) -> None: ...
def manual_seed_all(seed: int) -> None: ...
def max_memory_allocated(device: int = -1) -> int: ...
def max_memory_reserved(device: int = -1) -> int: ...
def memory_allocated(device: int = -1) -> int: ...
def memory_reserved(device: int = -1) -> int: ...
def memory_stats(device: int = -1) -> dict: ...
def reset_peak_memory_stats(device: int = -1) -> None: ...
def set_device(device: int) -> None: ...
def synchronize(device: int = -1) -> None: ...
