# @generated manually from src/bindings/python/Distributed.cpp
# mypy: disable-error-code="type-arg"
# mypy: allow-untyped-defs
# ruff: noqa: F401,PYI054

from tensorplay._C import TensorBase

def all_gather(recv: TensorBase, send: TensorBase, comm: int) -> None: ...
def all_reduce(tensor: TensorBase, op: int, comm: int, root: int = 0) -> None: ...
def all_to_all_single_equal_split(recv: TensorBase, send: TensorBase, comm: int) -> None: ...
def all_to_all_single_unequal_split(recv: TensorBase, send: TensorBase, output_split_sizes: object, input_split_sizes: object, comm: int) -> None: ...
def broadcast(tensor: TensorBase, root: int, comm: int) -> None: ...
def comm_abort(comm: int) -> None: ...
def comm_count(comm: int) -> int: ...
def comm_destroy(comm: int) -> None: ...
def comm_init_rank(rank: int, world_size: int, unique_id: bytes) -> int: ...
def gather(recv: object, send: TensorBase, root: int, comm: int) -> None: ...
def get_unique_id() -> bytes: ...
def group_end() -> None: ...
def group_start() -> None: ...
def is_available() -> bool: ...
def recv(tensor: TensorBase, peer: int, comm: int) -> None: ...
def reduce(tensor: TensorBase, op: int, root: int, comm: int) -> None: ...
def reduce_scatter(recv: TensorBase, send: TensorBase, op: int, comm: int) -> None: ...
def scatter(recv: TensorBase, send: object, root: int, comm: int) -> None: ...
def send(tensor: TensorBase, peer: int, comm: int) -> None: ...
def version() -> str: ...
