# @generated manually from src/bindings/python/Stax.cpp
# mypy: disable-error-code="type-arg"
# mypy: allow-untyped-defs
# ruff: noqa: F401,PYI054

from collections.abc import Sequence
from typing import Any

from tensorplay._C import TensorBase

class ValueNode:
    @property
    def id(self) -> int: ...
    @property
    def shape(self) -> list[int]: ...
    @property
    def dtype(self) -> Any: ...
    @property
    def use_count(self) -> int: ...

class OpNode:
    @property
    def op_type(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def input_count(self) -> int: ...
    @property
    def inputs(self) -> list[ValueNode]: ...
    @property
    def outputs(self) -> list[ValueNode]: ...
    def add_input(self, node: ValueNode) -> None: ...
    def add_output(self) -> ValueNode: ...
    def has_attr(self, key: str) -> bool: ...
    def get_int_attr(self, key: str) -> int: ...
    def get_float_attr(self, key: str) -> float: ...
    def set_float_attr(self, key: str, value: float) -> None: ...
    def set_floats_attr(self, key: str, value: Sequence[float]) -> None: ...
    def set_ints_attr(self, key: str, value: Sequence[int]) -> None: ...

class Graph:
    def __init__(self) -> None: ...
    @property
    def inputs(self) -> list[ValueNode]: ...
    @property
    def nodes(self) -> list[OpNode]: ...
    @property
    def outputs(self) -> list[ValueNode]: ...
    def add_input(self) -> ValueNode: ...
    def create_node(self, op_type: str, name: str = "") -> OpNode: ...
    def register_output(self, node: ValueNode) -> None: ...
    def fuse(self) -> None: ...
    def execute(self, inputs: Sequence[TensorBase]) -> list[TensorBase]: ...
    def print(self) -> None: ...

class IRBuilder:
    def __init__(self, graph: Graph) -> None: ...
    def create_input(self, shape: Sequence[int], dtype: Any) -> ValueNode: ...
    def create_op(self, op_type: str, inputs: Sequence[ValueNode], name: str = "") -> OpNode: ...
    def mark_output(self, node: ValueNode) -> None: ...

def execute_fused_pointwise_multi(inputs: Sequence[TensorBase], program: Sequence, extra: Sequence[TensorBase] = ...) -> list[TensorBase]: ...
def install_call_trampoline(
    lowering: object,
    exec_fn: object,
    tail: list,
    tensor_type: object,
    nargs_expected: int,
    output_count: int,
    gradient_plan: bool,
    direct_addr: int = ...,
) -> object: ...
def make_call_dispatcher(python_entry: object) -> object: ...
