"""Public checkpoint serialization API."""

from .api import (
    DEFAULT_ALIGNMENT,
    DEFAULT_PROTOCOL,
    LoadEndianness,
    MAGIC_NUMBER,
    MEGA_EXTENSION,
    MEGA_INDEX_SUFFIX,
    PROTOCOL_VERSION,
    StorageType,
    add_safe_globals,
    clear_safe_globals,
    convert_model,
    convert_to_mega,
    default_restore_location,
    get_crc32_options,
    get_default_load_endianness,
    get_default_mmap_options,
    get_safe_globals,
    get_unsafe_globals_in_checkpoint,
    inspect_checkpoint,
    load,
    location_tag,
    normalize_storage_type,
    register_package,
    safe_globals,
    save,
    set_default_load_endianness,
    set_default_mmap_options,
    set_crc32_options,
    skip_data,
    storage_to_tensor_type,
)
from .common import (
    _StorageStub,
    _apply_location,
    _byteswap_tensor,
    _contig_stride,
    _is_path_like,
    _move_to,
    _parse_device,
    _sniff_format,
    _validate_device_spec,
    resolve_map_location,
)
from .mega import parse_mega_header
from .api import _probe_torch_stream

__all__ = [
    "DEFAULT_ALIGNMENT",
    "DEFAULT_PROTOCOL",
    "LoadEndianness",
    "MAGIC_NUMBER",
    "MEGA_EXTENSION",
    "MEGA_INDEX_SUFFIX",
    "PROTOCOL_VERSION",
    "StorageType",
    "add_safe_globals",
    "clear_safe_globals",
    "convert_model",
    "convert_to_mega",
    "default_restore_location",
    "get_crc32_options",
    "get_default_load_endianness",
    "get_default_mmap_options",
    "get_safe_globals",
    "get_unsafe_globals_in_checkpoint",
    "inspect_checkpoint",
    "load",
    "location_tag",
    "normalize_storage_type",
    "parse_mega_header",
    "register_package",
    "resolve_map_location",
    "safe_globals",
    "save",
    "set_default_load_endianness",
    "set_default_mmap_options",
    "set_crc32_options",
    "skip_data",
    "storage_to_tensor_type",
]
