from collections.abc import Iterable
from typing import Any, no_type_check

import tensorplay as tp


__all__: list[str] = []

# Keyed by Parameter object; tp Parameters are stable Python objects and
param_to_optim_hook_handle_map = {}
param_to_acc_grad_map = {}


@no_type_check
def _apply_optimizer_in_backward(
    optimizer_class,
    params: Iterable[tp.nn.Parameter],
    optimizer_kwargs: dict[str, Any],
    register_hook: bool = True,
) -> None:
    """
    Upon ``backward()``, the optimizer specified for each parameter will fire after
    the gradient has been accumulated into the parameter.

    Note - gradients for these parameters will be set to None after ``backward()``.
    This means that any other optimizer not specified via `_apply_optimizer_in_backward`
    over this parameter will be a no-op.

    Args:
        optimizer_class: Optimizer to apply to parameter
        params: parameters to apply optimizer state to
        optimizer_kwargs: kwargs to pass to optimizer constructor
        register_hook: whether to register a hook that runs the optimizer
            after gradient for this parameter is accumulated. This is the default
            way that optimizer in backward is implemented, but specific use cases
            (such as DDP) may wish to override this to implement custom behavior.
            (Default = True)

    Example::
        params_generator = model.parameters()
        param_1 = next(params_generator)
        remainder_params = list(params_generator)

        apply_optimizer_in_backward(tp.optim.SGD, [param_1], {"lr": 0.02})
        apply_optimizer_in_backward(tp.optim.Adam, remainder_params, {"lr": 0.04})

        model(...).sum().backward()  # after backward, parameters will already
        # have their registered optimizer(s) applied.

    """

    @no_type_check
    def _apply_optimizer_in_backward_to_param(param: tp.nn.Parameter) -> None:
        # Register a post-accumulate-grad hook on the parameter to fire the
        # optimizer when the gradient for the parameter has been accumulated.
        optim = optimizer_class([param], **optimizer_kwargs)
        if not hasattr(param, "_in_backward_optimizers"):
            param._in_backward_optimizers = [optim]
        else:
            param._in_backward_optimizers.append(optim)

        def hook(_param):
            with tp.no_grad():
                for o in _param._in_backward_optimizers:
                    o.step()
            # Gradients for parameters optimized in backward are cleared after
            # their optimizer fires.
            _param.grad = None

        if register_hook:
            handle = param.register_post_accumulate_grad_hook(hook)
            param_to_optim_hook_handle_map[param] = handle

    for param in params:
        _apply_optimizer_in_backward_to_param(param)


@no_type_check
def _get_in_backward_optimizers(param: tp.nn.Parameter):
    """
    Return optimizers generated by ``_apply_optimizer_in_backward`` for a given parameter.

    Users may call ``optimizer.step`` on returned optimizer(s) if they wish
    them to run manually instead of during backward.
    """
    return getattr(param, "_in_backward_optimizers", [])


apply_optimizer_in_backward = _apply_optimizer_in_backward
