This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file ./main.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file main.acn....done (20 entries accepted, 0 rejected).
Sorting entries....done (94 comparisons).
Generating output file main.acr....done (44 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
