// Generated by tp_porting/gen_inplace_alias.py -- in-place and alias
// bindings for table entries whose base overload is already registered.

#include "Tensor.h"
#include "Exception.h"
#include "tensorplay/ops/TPXOpsGenerated.h"

#include <optional>
#include <string>
#include <utility>
#include <vector>

namespace tensorplay {
namespace composite {

namespace ops = tensorplay::tpx::ops;

// The shape-changing updates (t_, transpose_, squeeze_, unsqueeze_) move no
// element: the tensor takes the geometry the matching view would have over
// its own storage.
namespace {

// Wraps a dimension the way the view ops do: a 0-d tensor accepts -1 and 0.
int64_t wrap_view_dim(int64_t dim, int64_t ndim) {
    const int64_t n = ndim > 0 ? ndim : 1;
    if (dim < -n || dim >= n) {
        TP_THROW(IndexError, "Dimension out of range (expected to be in range of [",
                 -n, ", ", n - 1, "], but got ", dim, ")");
    }
    return dim < 0 ? dim + n : dim;
}

// Drops the dimensions `drop` marks, provided they have size one.
Tensor& squeeze_marked(Tensor& self, const std::vector<bool>& drop) {
    std::vector<int64_t> sizes;
    std::vector<int64_t> strides;
    for (int64_t i = 0; i < self.dim(); ++i) {
        if (!(drop[i] && self.size(i) == 1)) {
            sizes.push_back(self.size(i));
            strides.push_back(self.stride(i));
        }
    }
    ops::as_strided_(self, sizes, strides);
    return self;
}

} // namespace

Tensor& inplace_copysign_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::copysign(self, other));
    return self;
}

Tensor& inplace_copysign_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::copysign(self, other));
    return self;
}

Tensor& inplace_div_dd_Tensor_mode(Tensor& self, const Tensor& other, const std::optional<std::string>& rounding_mode) {
    ops::copy_(self, ops::div(self, other, rounding_mode));
    return self;
}

Tensor& inplace_div_dd_Scalar_mode(Tensor& self, const Scalar& other, const std::optional<std::string>& rounding_mode) {
    ops::copy_(self, ops::div(self, other, rounding_mode));
    return self;
}

Tensor& inplace_divide_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::divide(self, other));
    return self;
}

Tensor& inplace_divide_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::divide(self, other));
    return self;
}

Tensor& inplace_divide_dd_Tensor_mode(Tensor& self, const Tensor& other, const std::optional<std::string>& rounding_mode) {
    ops::copy_(self, ops::divide(self, other, rounding_mode));
    return self;
}

Tensor& inplace_divide_dd_Scalar_mode(Tensor& self, const Scalar& other, const std::optional<std::string>& rounding_mode) {
    ops::copy_(self, ops::divide(self, other, rounding_mode));
    return self;
}

Tensor& inplace_true_divide_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::true_divide(self, other));
    return self;
}

Tensor& inplace_true_divide_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::true_divide(self, other));
    return self;
}

Tensor& inplace_fill_dd_Tensor(Tensor& self, const Tensor& value) {
    ops::copy_(self, ops::fill(self, value));
    return self;
}

Tensor& inplace_floor_divide_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::floor_divide(self, other));
    return self;
}

Tensor& inplace_multiply_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::multiply(self, other));
    return self;
}

Tensor& inplace_multiply_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::multiply(self, other));
    return self;
}

Tensor& inplace_mvlgamma_(Tensor& self, int64_t p) {
    ops::copy_(self, ops::mvlgamma(self, p));
    return self;
}

Tensor& inplace_squeeze_(Tensor& self) {
    return squeeze_marked(self, std::vector<bool>(self.dim(), true));
}

Tensor& inplace_squeeze_dd_dim(Tensor& self, int64_t dim) {
    const int64_t ndim = self.dim();
    dim = wrap_view_dim(dim, ndim);
    std::vector<bool> drop(ndim, false);
    if (ndim > 0) drop[dim] = true;
    return squeeze_marked(self, drop);
}

Tensor& inplace_squeeze_dd_dims(Tensor& self, const std::vector<int64_t>& dim) {
    const int64_t ndim = self.dim();
    std::vector<bool> drop(ndim, false);
    for (int64_t d : dim) {
        const int64_t w = wrap_view_dim(d, ndim);
        if (ndim == 0) continue;
        if (drop[w]) {
            TP_THROW(RuntimeError, "dim ", w,
                     " appears multiple times in the list of dims");
        }
        drop[w] = true;
    }
    return squeeze_marked(self, drop);
}

Tensor& inplace_transpose_(Tensor& self, int64_t dim0, int64_t dim1) {
    const int64_t ndim = self.dim();
    dim0 = wrap_view_dim(dim0, ndim);
    dim1 = wrap_view_dim(dim1, ndim);
    if (dim0 == dim1) {
        return self;
    }
    std::vector<int64_t> sizes = static_cast<std::vector<int64_t>>(self.shape());
    std::vector<int64_t> strides = self.strides();
    std::swap(sizes[dim0], sizes[dim1]);
    std::swap(strides[dim0], strides[dim1]);
    ops::as_strided_(self, sizes, strides);
    return self;
}

Tensor& inplace_t_(Tensor& self) {
    if (self.dim() > 2) {
        TP_THROW(RuntimeError, "t_() expects a tensor with <= 2 dimensions, but self is ",
                 self.dim(), "D");
    }
    return inplace_transpose_(self, 0, self.dim() < 2 ? 0 : 1);
}

Tensor& inplace_fix_(Tensor& self) {
    ops::copy_(self, ops::fix(self));
    return self;
}

Tensor& inplace_unsqueeze_(Tensor& self, int64_t dim) {
    const int64_t ndim = self.dim();
    dim = wrap_view_dim(dim, ndim + 1);
    std::vector<int64_t> sizes = static_cast<std::vector<int64_t>>(self.shape());
    std::vector<int64_t> strides = self.strides();
    const int64_t stride = dim >= ndim ? 1 : sizes[dim] * strides[dim];
    sizes.insert(sizes.begin() + dim, 1);
    strides.insert(strides.begin() + dim, stride);
    ops::as_strided_(self, sizes, strides);
    return self;
}

Tensor& inplace_subtract_dd_Tensor(Tensor& self, const Tensor& other, const Scalar& alpha) {
    ops::copy_(self, ops::subtract(self, other, alpha));
    return self;
}

Tensor& inplace_subtract_dd_Scalar(Tensor& self, const Scalar& other, const Scalar& alpha) {
    ops::copy_(self, ops::subtract(self, other, alpha));
    return self;
}

Tensor& inplace_put_(Tensor& self, const Tensor& index, const Tensor& source, bool accumulate) {
    ops::copy_(self, ops::put(self, index, source, accumulate));
    return self;
}

Tensor& inplace_eq_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::eq(self, other));
    return self;
}

Tensor& inplace_eq_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::eq(self, other));
    return self;
}

Tensor& inplace_bitwise_and_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::bitwise_and(self, other));
    return self;
}

Tensor& inplace_bitwise_and_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::bitwise_and(self, other));
    return self;
}

Tensor& inplace_bitwise_or_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::bitwise_or(self, other));
    return self;
}

Tensor& inplace_bitwise_or_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::bitwise_or(self, other));
    return self;
}

Tensor& inplace_bitwise_xor_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::bitwise_xor(self, other));
    return self;
}

Tensor& inplace_bitwise_xor_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::bitwise_xor(self, other));
    return self;
}

Tensor& inplace_bitwise_left_shift_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::bitwise_left_shift(self, other));
    return self;
}

Tensor& inplace_bitwise_left_shift_dd_Tensor_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::bitwise_left_shift(self, other));
    return self;
}

Tensor& inplace_bitwise_right_shift_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::bitwise_right_shift(self, other));
    return self;
}

Tensor& inplace_bitwise_right_shift_dd_Tensor_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::bitwise_right_shift(self, other));
    return self;
}

Tensor& inplace_digamma_(Tensor& self) {
    ops::copy_(self, ops::digamma(self));
    return self;
}

Tensor& inplace_ne_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::ne(self, other));
    return self;
}

Tensor& inplace_ne_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::ne(self, other));
    return self;
}

Tensor alias_not_equal_Scalar(const Tensor& self, const Scalar& other) {
    return ops::ne(self, other);
}

Tensor alias_not_equal_Tensor(const Tensor& self, const Tensor& other) {
    return ops::ne(self, other);
}

Tensor& inplace_not_equal_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::not_equal(self, other));
    return self;
}

Tensor& inplace_not_equal_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::not_equal(self, other));
    return self;
}

Tensor& inplace_ge_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::ge(self, other));
    return self;
}

Tensor& inplace_ge_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::ge(self, other));
    return self;
}

Tensor alias_greater_equal_Scalar(const Tensor& self, const Scalar& other) {
    return ops::ge(self, other);
}

Tensor alias_greater_equal_Tensor(const Tensor& self, const Tensor& other) {
    return ops::ge(self, other);
}

Tensor& inplace_greater_equal_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::greater_equal(self, other));
    return self;
}

Tensor& inplace_greater_equal_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::greater_equal(self, other));
    return self;
}

Tensor& inplace_le_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::le(self, other));
    return self;
}

Tensor& inplace_le_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::le(self, other));
    return self;
}

Tensor alias_less_equal_Scalar(const Tensor& self, const Scalar& other) {
    return ops::le(self, other);
}

Tensor alias_less_equal_Tensor(const Tensor& self, const Tensor& other) {
    return ops::le(self, other);
}

Tensor& inplace_less_equal_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::less_equal(self, other));
    return self;
}

Tensor& inplace_less_equal_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::less_equal(self, other));
    return self;
}

Tensor& inplace_gt_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::gt(self, other));
    return self;
}

Tensor& inplace_gt_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::gt(self, other));
    return self;
}

Tensor alias_greater_Scalar(const Tensor& self, const Scalar& other) {
    return ops::gt(self, other);
}

Tensor alias_greater_Tensor(const Tensor& self, const Tensor& other) {
    return ops::gt(self, other);
}

Tensor& inplace_greater_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::greater(self, other));
    return self;
}

Tensor& inplace_greater_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::greater(self, other));
    return self;
}

Tensor& inplace_lt_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::lt(self, other));
    return self;
}

Tensor& inplace_lt_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::lt(self, other));
    return self;
}

Tensor alias_less_Scalar(const Tensor& self, const Scalar& other) {
    return ops::lt(self, other);
}

Tensor alias_less_Tensor(const Tensor& self, const Tensor& other) {
    return ops::lt(self, other);
}

Tensor& inplace_less_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::less(self, other));
    return self;
}

Tensor& inplace_less_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::less(self, other));
    return self;
}

Tensor& inplace_swapaxes_(Tensor& self, int64_t axis0, int64_t axis1) {
    return ops::transpose_(self, axis0, axis1);
}

Tensor& inplace_swapdims_(Tensor& self, int64_t dim0, int64_t dim1) {
    return ops::transpose_(self, dim0, dim1);
}

Tensor& inplace_fmod_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::fmod(self, other));
    return self;
}

Tensor& inplace_fmod_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::fmod(self, other));
    return self;
}

Tensor& inplace_remainder_dd_Scalar(Tensor& self, const Scalar& other) {
    ops::copy_(self, ops::remainder(self, other));
    return self;
}

Tensor& inplace_remainder_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::remainder(self, other));
    return self;
}

} // namespace composite
} // namespace tensorplay

namespace tensorplay {
TENSORPLAY_LIBRARY_IMPL(Composite, InplaceAliasOps) {
    m.impl("copysign_.Tensor", composite::inplace_copysign_dd_Tensor);
    m.impl("copysign_.Scalar", composite::inplace_copysign_dd_Scalar);
    m.impl("div_.Tensor_mode", composite::inplace_div_dd_Tensor_mode);
    m.impl("div_.Scalar_mode", composite::inplace_div_dd_Scalar_mode);
    m.impl("divide_.Tensor", composite::inplace_divide_dd_Tensor);
    m.impl("divide_.Scalar", composite::inplace_divide_dd_Scalar);
    m.impl("divide_.Tensor_mode", composite::inplace_divide_dd_Tensor_mode);
    m.impl("divide_.Scalar_mode", composite::inplace_divide_dd_Scalar_mode);
    m.impl("true_divide_.Tensor", composite::inplace_true_divide_dd_Tensor);
    m.impl("true_divide_.Scalar", composite::inplace_true_divide_dd_Scalar);
    m.impl("fill_.Tensor", composite::inplace_fill_dd_Tensor);
    m.impl("floor_divide_.Scalar", composite::inplace_floor_divide_dd_Scalar);
    m.impl("multiply_.Tensor", composite::inplace_multiply_dd_Tensor);
    m.impl("multiply_.Scalar", composite::inplace_multiply_dd_Scalar);
    m.impl("mvlgamma_", composite::inplace_mvlgamma_);
    m.impl("squeeze_", composite::inplace_squeeze_);
    m.impl("squeeze_.dim", composite::inplace_squeeze_dd_dim);
    m.impl("squeeze_.dims", composite::inplace_squeeze_dd_dims);
    m.impl("t_", composite::inplace_t_);
    m.impl("transpose_", composite::inplace_transpose_);
    m.impl("fix_", composite::inplace_fix_);
    m.impl("unsqueeze_", composite::inplace_unsqueeze_);
    m.impl("subtract_.Tensor", composite::inplace_subtract_dd_Tensor);
    m.impl("subtract_.Scalar", composite::inplace_subtract_dd_Scalar);
    m.impl("put_", composite::inplace_put_);
    m.impl("eq_.Scalar", composite::inplace_eq_dd_Scalar);
    m.impl("eq_.Tensor", composite::inplace_eq_dd_Tensor);
    m.impl("bitwise_and_.Scalar", composite::inplace_bitwise_and_dd_Scalar);
    m.impl("bitwise_and_.Tensor", composite::inplace_bitwise_and_dd_Tensor);
    m.impl("bitwise_or_.Scalar", composite::inplace_bitwise_or_dd_Scalar);
    m.impl("bitwise_or_.Tensor", composite::inplace_bitwise_or_dd_Tensor);
    m.impl("bitwise_xor_.Scalar", composite::inplace_bitwise_xor_dd_Scalar);
    m.impl("bitwise_xor_.Tensor", composite::inplace_bitwise_xor_dd_Tensor);
    m.impl("bitwise_left_shift_.Tensor", composite::inplace_bitwise_left_shift_dd_Tensor);
    m.impl("bitwise_left_shift_.Tensor_Scalar", composite::inplace_bitwise_left_shift_dd_Tensor_Scalar);
    m.impl("bitwise_right_shift_.Tensor", composite::inplace_bitwise_right_shift_dd_Tensor);
    m.impl("bitwise_right_shift_.Tensor_Scalar", composite::inplace_bitwise_right_shift_dd_Tensor_Scalar);
    m.impl("digamma_", composite::inplace_digamma_);
    m.impl("ne_.Scalar", composite::inplace_ne_dd_Scalar);
    m.impl("ne_.Tensor", composite::inplace_ne_dd_Tensor);
    m.impl("not_equal.Scalar", composite::alias_not_equal_Scalar);
    m.impl("not_equal.Tensor", composite::alias_not_equal_Tensor);
    m.impl("not_equal_.Scalar", composite::inplace_not_equal_dd_Scalar);
    m.impl("not_equal_.Tensor", composite::inplace_not_equal_dd_Tensor);
    m.impl("ge_.Scalar", composite::inplace_ge_dd_Scalar);
    m.impl("ge_.Tensor", composite::inplace_ge_dd_Tensor);
    m.impl("greater_equal.Scalar", composite::alias_greater_equal_Scalar);
    m.impl("greater_equal.Tensor", composite::alias_greater_equal_Tensor);
    m.impl("greater_equal_.Scalar", composite::inplace_greater_equal_dd_Scalar);
    m.impl("greater_equal_.Tensor", composite::inplace_greater_equal_dd_Tensor);
    m.impl("le_.Scalar", composite::inplace_le_dd_Scalar);
    m.impl("le_.Tensor", composite::inplace_le_dd_Tensor);
    m.impl("less_equal.Scalar", composite::alias_less_equal_Scalar);
    m.impl("less_equal.Tensor", composite::alias_less_equal_Tensor);
    m.impl("less_equal_.Scalar", composite::inplace_less_equal_dd_Scalar);
    m.impl("less_equal_.Tensor", composite::inplace_less_equal_dd_Tensor);
    m.impl("gt_.Scalar", composite::inplace_gt_dd_Scalar);
    m.impl("gt_.Tensor", composite::inplace_gt_dd_Tensor);
    m.impl("greater.Scalar", composite::alias_greater_Scalar);
    m.impl("greater.Tensor", composite::alias_greater_Tensor);
    m.impl("greater_.Scalar", composite::inplace_greater_dd_Scalar);
    m.impl("greater_.Tensor", composite::inplace_greater_dd_Tensor);
    m.impl("lt_.Scalar", composite::inplace_lt_dd_Scalar);
    m.impl("lt_.Tensor", composite::inplace_lt_dd_Tensor);
    m.impl("less.Scalar", composite::alias_less_Scalar);
    m.impl("less.Tensor", composite::alias_less_Tensor);
    m.impl("less_.Scalar", composite::inplace_less_dd_Scalar);
    m.impl("less_.Tensor", composite::inplace_less_dd_Tensor);
    m.impl("swapaxes_", composite::inplace_swapaxes_);
    m.impl("swapdims_", composite::inplace_swapdims_);
    m.impl("fmod_.Scalar", composite::inplace_fmod_dd_Scalar);
    m.impl("fmod_.Tensor", composite::inplace_fmod_dd_Tensor);
    m.impl("remainder_.Scalar", composite::inplace_remainder_dd_Scalar);
    m.impl("remainder_.Tensor", composite::inplace_remainder_dd_Tensor);
}
} // namespace tensorplay
