// Generated by tp_porting/gen_variant_wiring.py -- alias overloads.
// Registered base overloads are reused through the generated
// composition entry points; no new kernel math lives here.

#include "Tensor.h"
#include "Dispatcher.h"
#include "tensorplay/ops/TPXOpsGenerated.h"

#include <optional>
#include <string>
#include <tuple>
#include <vector>

namespace tensorplay {
namespace composite {

namespace ops = tensorplay::tpx::ops;

std::tuple<Tensor, Tensor> alias_wrap__ctc_loss_Tensor(const Tensor& log_probs, const Tensor& targets, const Tensor& input_lengths, const Tensor& target_lengths, int64_t blank, bool zero_infinity) {
    return ops::_ctc_loss(log_probs, targets, input_lengths, target_lengths, blank, zero_infinity);
}

Tensor alias_wrap__ctc_loss_backward_Tensor(const Tensor& grad, const Tensor& log_probs, const Tensor& targets, const Tensor& input_lengths, const Tensor& target_lengths, const Tensor& neg_log_likelihood, const Tensor& log_alpha, int64_t blank, bool zero_infinity) {
    return ops::_ctc_loss_backward(grad, log_probs, targets, input_lengths, target_lengths, neg_log_likelihood, log_alpha, blank, zero_infinity);
}

Tensor alias_wrap_conv_transpose2d_input(const Tensor& input, const Tensor& weight, const std::optional<Tensor>& bias, const std::vector<int64_t>& stride, const std::vector<int64_t>& padding, const std::vector<int64_t>& output_padding, int64_t groups, const std::vector<int64_t>& dilation) {
    return ops::conv_transpose2d(input, weight, bias, stride, padding, output_padding, groups, dilation);
}

Tensor alias_wrap_conv_transpose3d_input(const Tensor& input, const Tensor& weight, const std::optional<Tensor>& bias, const std::vector<int64_t>& stride, const std::vector<int64_t>& padding, const std::vector<int64_t>& output_padding, int64_t groups, const std::vector<int64_t>& dilation) {
    return ops::conv_transpose3d(input, weight, bias, stride, padding, output_padding, groups, dilation);
}

Tensor alias_wrap_count_nonzero_dim_IntList(const Tensor& self, const std::vector<int64_t>& dim) {
    return ops::count_nonzero(self, dim);
}

Tensor alias_wrap_float_power_Tensor_Tensor(const Tensor& self, const Tensor& exponent) {
    return ops::float_power(self, exponent);
}

std::tuple<Tensor, Tensor> alias_wrap_frexp_Tensor(const Tensor& self) {
    return ops::frexp(self);
}

std::vector<Tensor> alias_wrap_gradient_tensorarray(const Tensor& self, const std::vector<Tensor>& spacing, const std::vector<int64_t>& dim, int64_t edge_order) {
    return ops::gradient(self, spacing, dim, edge_order);
}

Tensor alias_wrap_ldexp_Tensor(const Tensor& self, const Tensor& other) {
    return ops::ldexp(self, other);
}

Tensor alias_wrap_lerp_Scalar(const Tensor& self, const Tensor& end, Scalar weight) {
    return ops::lerp(self, end, weight);
}

Tensor alias_wrap_log_softmax_int(const Tensor& self, int64_t dim, std::optional<DType> dtype) {
    return ops::log_softmax(self, dim, dtype.value_or(DType::Undefined));
}

std::tuple<Tensor, Tensor, Tensor> alias_wrap_lstm_input(const Tensor& input, const std::vector<Tensor>& hx, const std::vector<Tensor>& params, bool has_biases, int64_t num_layers, double dropout, bool train, bool bidirectional, bool batch_first) {
    return ops::lstm(input, hx, params, has_biases, num_layers, dropout, train, bidirectional, batch_first);
}

Tensor alias_wrap_masked_fill_Scalar(const Tensor& self, const Tensor& mask, Scalar value) {
    return ops::masked_fill(self, mask, value);
}

std::vector<Tensor> alias_wrap_meshgrid_indexing(const std::vector<Tensor>& tensors, std::string indexing) {
    return ops::meshgrid(tensors, indexing);
}

Tensor alias_wrap_min_other(const Tensor& self, const Tensor& other) {
    return ops::min(self, other);
}

Tensor alias_wrap_movedim_intlist(const Tensor& self, const std::vector<int64_t>& source, const std::vector<int64_t>& destination) {
    return ops::movedim(self, source, destination);
}

Tensor alias_wrap_normal_Tensor_Tensor(const Tensor& mean, const Tensor& std, std::optional<Generator> generator) {
    return ops::normal(mean, std);
}

Tensor alias_wrap_scatter_reduce_two(const Tensor& self, int64_t dim, const Tensor& index, const Tensor& src, std::string reduce, bool include_self) {
    return ops::scatter_reduce(self, dim, index, src, reduce, include_self);
}

Tensor alias_wrap_slice_Tensor(const Tensor& self, int64_t dim, std::optional<int64_t> start, std::optional<int64_t> end, int64_t step) {
    return ops::slice(self, dim, start, end, step);
}

Tensor alias_wrap_softmax_int(const Tensor& self, int64_t dim, std::optional<DType> dtype) {
    return ops::softmax(self, dim, dtype.value_or(DType::Undefined));
}

std::vector<Tensor> alias_wrap_split_Tensor(const Tensor& self, int64_t split_size, int64_t dim) {
    return ops::split(self, split_size, dim);
}

std::tuple<Tensor, Tensor> alias_wrap_std_mean_dim(const Tensor& self, std::optional<std::vector<int64_t>> dim, bool unbiased, bool keepdim) {
    return ops::std_mean(self, dim.value_or(std::vector<int64_t>()), unbiased, keepdim);
}

Tensor alias_wrap_stft_center(const Tensor& self, int64_t n_fft, std::optional<int64_t> hop_length, std::optional<int64_t> win_length, const std::optional<Tensor>& window, bool center, std::string pad_mode, bool normalized, std::optional<bool> onesided, std::optional<bool> return_complex, std::optional<bool> align_to_window) {
    return ops::stft(self, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided.value_or(true), return_complex.value_or(true));
}

Tensor alias_wrap_transpose_int(const Tensor& self, int64_t dim0, int64_t dim1) {
    return ops::transpose(self, dim0, dim1);
}

std::vector<Tensor> alias_wrap_unbind_int(const Tensor& self, int64_t dim) {
    return ops::unbind(self, dim);
}

std::tuple<Tensor, Tensor> alias_wrap_var_mean_dim(const Tensor& self, std::optional<std::vector<int64_t>> dim, bool unbiased, bool keepdim) {
    return ops::var_mean(self, dim.value_or(std::vector<int64_t>()), unbiased, keepdim);
}

Tensor alias_wrap_xlogy_Tensor(const Tensor& self, const Tensor& other) {
    return ops::xlogy(self, other);
}

Tensor& inplace_wrap_masked_fill_dd_Scalar(Tensor& self, const Tensor& mask, Scalar value) {
    ops::copy_(self, ops::masked_fill_(self, mask, value));
    return self;
}

Tensor& inplace_wrap_random_dd_from(Tensor& self, int64_t from, std::optional<int64_t> to, std::optional<Generator> generator) {
    ops::copy_(self, ops::random_(self, from, to.value_or(0)));
    return self;
}

Tensor& inplace_wrap_xlogy_dd_Tensor(Tensor& self, const Tensor& other) {
    ops::copy_(self, ops::xlogy_(self, other));
    return self;
}

} // namespace composite
} // namespace tensorplay

namespace tensorplay {
TENSORPLAY_LIBRARY_IMPL(Composite, VariantWiringaliasoverloads) {
    m.impl("_ctc_loss.Tensor", composite::alias_wrap__ctc_loss_Tensor);
    m.impl("_ctc_loss_backward.Tensor", composite::alias_wrap__ctc_loss_backward_Tensor);
    m.impl("conv_transpose2d.input", composite::alias_wrap_conv_transpose2d_input);
    m.impl("conv_transpose3d.input", composite::alias_wrap_conv_transpose3d_input);
    m.impl("count_nonzero.dim_IntList", composite::alias_wrap_count_nonzero_dim_IntList);
    m.impl("float_power.Tensor_Tensor", composite::alias_wrap_float_power_Tensor_Tensor);
    m.impl("frexp.Tensor", composite::alias_wrap_frexp_Tensor);
    m.impl("gradient.tensorarray", composite::alias_wrap_gradient_tensorarray);
    m.impl("ldexp.Tensor", composite::alias_wrap_ldexp_Tensor);
    m.impl("lerp.Scalar", composite::alias_wrap_lerp_Scalar);
    m.impl("log_softmax.int", composite::alias_wrap_log_softmax_int);
    m.impl("lstm.input", composite::alias_wrap_lstm_input);
    m.impl("masked_fill.Scalar", composite::alias_wrap_masked_fill_Scalar);
    m.impl("meshgrid.indexing", composite::alias_wrap_meshgrid_indexing);
    m.impl("min.other", composite::alias_wrap_min_other);
    m.impl("movedim.intlist", composite::alias_wrap_movedim_intlist);
    m.impl("normal.Tensor_Tensor", composite::alias_wrap_normal_Tensor_Tensor);
    m.impl("scatter_reduce.two", composite::alias_wrap_scatter_reduce_two);
    m.impl("slice.Tensor", composite::alias_wrap_slice_Tensor);
    m.impl("softmax.int", composite::alias_wrap_softmax_int);
    m.impl("split.Tensor", composite::alias_wrap_split_Tensor);
    m.impl("std_mean.dim", composite::alias_wrap_std_mean_dim);
    m.impl("stft.center", composite::alias_wrap_stft_center);
    m.impl("transpose.int", composite::alias_wrap_transpose_int);
    m.impl("unbind.int", composite::alias_wrap_unbind_int);
    m.impl("var_mean.dim", composite::alias_wrap_var_mean_dim);
    m.impl("xlogy.Tensor", composite::alias_wrap_xlogy_Tensor);
    m.impl("masked_fill_.Scalar", composite::inplace_wrap_masked_fill_dd_Scalar);
    m.impl("random_.from", composite::inplace_wrap_random_dd_from);
    m.impl("xlogy_.Tensor", composite::inplace_wrap_xlogy_dd_Tensor);
}
} // namespace tensorplay
