"""Names used by the TensorPlay model archive format."""

ARCHIVE_FORMAT_PATH = "archive_format"
ARCHIVE_FORMAT_VALUE = "pt2"
ARCHIVE_ROOT_NAME = "tensorplay"
ARCHIVE_VERSION_PATH = "archive_version"
ARCHIVE_VERSION_VALUE = "1"
AOTINDUCTOR_DIR = "data/aotinductor/"
CONSTANTS_DIR = "data/constants/"
CONSTANTS_CONFIG_FILENAME_FORMAT = CONSTANTS_DIR + "{}/constants.json"
CUSTOM_OBJ_FILENAME_PREFIX = "custom_obj_"
OPAQUE_OBJ_FILENAME_PREFIX = "opaque_obj_"
EXECUTORCH_DIR = "data/executorch/"
EXTRA_DIR = "extra/"
MODELS_DIR = "models/"
MODELS_FILENAME_FORMAT = MODELS_DIR + "{}.json"
MODULE_INFO_PATH = "module_info.json"
MTIA_DIR = "data/mtia/"
SAMPLE_INPUTS_DIR = "data/sample_inputs/"
SAMPLE_INPUTS_FILENAME_FORMAT = SAMPLE_INPUTS_DIR + "{}.pkl"
TENSOR_CONSTANT_FILENAME_PREFIX = "tensor_constant_"
WEIGHTS_CONFIG_FILENAME_FORMAT = "data/weights/{}/weights.json"
WEIGHT_FILENAME_PREFIX = "weight_"
WEIGHTS_DIR = "data/weights/"
XL_MODEL_WEIGHTS_DIR = "data/xl_model_weights/"
XL_MODEL_WEIGHTS_PARAM_CONFIG_PATH = XL_MODEL_WEIGHTS_DIR + "params.json"
