# noqa: F401, E501
# This is an auto-generated file. Please do not modify it by hand.
# To re-generate, run the generator named in the file it writes.

import operator
import tensorplay as tp

operator_set = tp.ops.tp
prims = tp.ops.prims

from tensorplay.compiler.backends.stax.pattern_matcher import (
   Arg,
   CallFunction,
   CallFunctionVarArgs,
   CallMethod,
   CallMethodVarArgs,
   CallModule,
   CallModuleVarArgs,
   ExclusiveKeywordArg,
   GetAttr,
   Ignored,
   KeywordArg,
   ListOf,
   MultiOutputPattern,
   PatternExpr,
   RepeatedExpr,
   _TargetArgsExpr,
   _TargetExpr,
   _TargetExprVarArgs,
)
permute_default = CallFunction(operator_set.permute.default, KeywordArg('query'), Ignored())
mul_Scalar = CallFunction(operator_set.mul.Scalar, permute_default, KeywordArg('inv_scale'))
broadcast_to_default = CallFunction(operator_set.broadcast_to.default, mul_Scalar, Ignored())
reshape_default = CallFunction(operator_set.reshape.default, broadcast_to_default, Ignored())
permute_default_0 = CallFunction(operator_set.permute.default, KeywordArg('key'), Ignored())
permute_default_1 = CallFunction(operator_set.permute.default, permute_default_0, Ignored())
mul_Scalar_0 = CallFunction(operator_set.mul.Scalar, permute_default_1, KeywordArg('inv_scale'))
broadcast_to_default_0 = CallFunction(operator_set.broadcast_to.default, mul_Scalar_0, Ignored())
reshape_default_0 = CallFunction(operator_set.reshape.default, broadcast_to_default_0, Ignored())
bmm_default = CallFunction(operator_set.bmm.default, reshape_default, reshape_default_0)
reshape_default_1 = CallFunction(operator_set.reshape.default, bmm_default, Ignored())
add_Tensor = CallFunction(operator_set.add.Tensor, reshape_default_1, KeywordArg('attn_mask'), alpha=Ignored())
eq_Scalar = CallFunction(operator_set.eq.Scalar, add_Tensor, Ignored())
logical_not_default = CallFunction(operator_set.logical_not.default, eq_Scalar)
to_dtype = CallFunction(operator_set.to.dtype, logical_not_default, Ignored(), False, False, None)
sum_dim_IntList = CallFunction(operator_set.sum.dim_IntList, to_dtype, Ignored(), True, dtype=Ignored())
eq_Scalar_0 = CallFunction(operator_set.eq.Scalar, sum_dim_IntList, Ignored())
softmax_default = CallFunction(operator_set.softmax.default, add_Tensor, Ignored(), Ignored())
full_like_default = CallFunction(operator_set.full_like.default, softmax_default, Ignored(), dtype=Ignored(), device=Ignored())
where_self = CallFunction(operator_set.where.self, eq_Scalar_0, full_like_default, softmax_default)
broadcast_to_default_1 = CallFunction(operator_set.broadcast_to.default, where_self, Ignored())
reshape_default_2 = CallFunction(operator_set.reshape.default, broadcast_to_default_1, Ignored())
permute_default_2 = CallFunction(operator_set.permute.default, KeywordArg('value'), Ignored())
broadcast_to_default_2 = CallFunction(operator_set.broadcast_to.default, permute_default_2, Ignored())
reshape_default_3 = CallFunction(operator_set.reshape.default, broadcast_to_default_2, Ignored())
bmm_default_0 = CallFunction(operator_set.bmm.default, reshape_default_2, reshape_default_3)
reshape_default_4 = CallFunction(operator_set.reshape.default, bmm_default_0, Ignored())
permute_default_3 = CallFunction(operator_set.permute.default, where_self, Ignored())
broadcast_to_default_3 = CallFunction(operator_set.broadcast_to.default, permute_default_3, Ignored())
reshape_default_5 = CallFunction(operator_set.reshape.default, broadcast_to_default_3, Ignored())
broadcast_to_default_4 = CallFunction(operator_set.broadcast_to.default, KeywordArg('tangents_1'), Ignored())
reshape_default_6 = CallFunction(operator_set.reshape.default, broadcast_to_default_4, Ignored())
bmm_default_1 = CallFunction(operator_set.bmm.default, reshape_default_5, reshape_default_6)
reshape_default_7 = CallFunction(operator_set.reshape.default, bmm_default_1, Ignored())
permute_backward_default = CallFunction(operator_set.permute_backward.default, reshape_default_7, KeywordArg('value'), Ignored())
_sfdp_pattern_29_training = MultiOutputPattern([reshape_default_4,
  None,
  None,
  permute_backward_default
])


permute_default = CallFunction(operator_set.permute.default, KeywordArg('query'), Ignored())
mul_Scalar = CallFunction(operator_set.mul.Scalar, permute_default, KeywordArg('inv_scale'))
broadcast_to_default = CallFunction(operator_set.broadcast_to.default, mul_Scalar, Ignored())
reshape_default = CallFunction(operator_set.reshape.default, broadcast_to_default, Ignored())
permute_default_0 = CallFunction(operator_set.permute.default, KeywordArg('key'), Ignored())
permute_default_1 = CallFunction(operator_set.permute.default, permute_default_0, Ignored())
mul_Scalar_0 = CallFunction(operator_set.mul.Scalar, permute_default_1, KeywordArg('inv_scale'))
broadcast_to_default_0 = CallFunction(operator_set.broadcast_to.default, mul_Scalar_0, Ignored())
reshape_default_0 = CallFunction(operator_set.reshape.default, broadcast_to_default_0, Ignored())
bmm_default = CallFunction(operator_set.bmm.default, reshape_default, reshape_default_0)
reshape_default_1 = CallFunction(operator_set.reshape.default, bmm_default, Ignored())
add_Tensor = CallFunction(operator_set.add.Tensor, reshape_default_1, KeywordArg('attn_mask'), alpha=Ignored())
eq_Scalar = CallFunction(operator_set.eq.Scalar, add_Tensor, Ignored())
logical_not_default = CallFunction(operator_set.logical_not.default, eq_Scalar)
to_dtype = CallFunction(operator_set.to.dtype, logical_not_default, Ignored(), False, False, None)
sum_dim_IntList = CallFunction(operator_set.sum.dim_IntList, to_dtype, Ignored(), True, dtype=Ignored())
eq_Scalar_0 = CallFunction(operator_set.eq.Scalar, sum_dim_IntList, Ignored())
softmax_default = CallFunction(operator_set.softmax.default, add_Tensor, Ignored(), Ignored())
full_like_default = CallFunction(operator_set.full_like.default, softmax_default, Ignored(), dtype=Ignored(), device=Ignored())
where_self = CallFunction(operator_set.where.self, eq_Scalar_0, full_like_default, softmax_default)
broadcast_to_default_1 = CallFunction(operator_set.broadcast_to.default, where_self, Ignored())
reshape_default_2 = CallFunction(operator_set.reshape.default, broadcast_to_default_1, Ignored())
permute_default_2 = CallFunction(operator_set.permute.default, KeywordArg('value'), Ignored())
broadcast_to_default_2 = CallFunction(operator_set.broadcast_to.default, permute_default_2, Ignored())
reshape_default_3 = CallFunction(operator_set.reshape.default, broadcast_to_default_2, Ignored())
bmm_default_0 = CallFunction(operator_set.bmm.default, reshape_default_2, reshape_default_3)
_sfdp_pattern_29_inference = CallFunction(operator_set.reshape.default, bmm_default_0, Ignored())


permute_default = CallFunction(operator_set.permute.default, KeywordArg('query'), Ignored())
mul_Scalar = CallFunction(operator_set.mul.Scalar, permute_default, KeywordArg('inv_scale'))
broadcast_to_default = CallFunction(operator_set.broadcast_to.default, mul_Scalar, Ignored())
reshape_default = CallFunction(operator_set.reshape.default, broadcast_to_default, Ignored())
permute_default_0 = CallFunction(operator_set.permute.default, KeywordArg('key'), Ignored())
permute_default_1 = CallFunction(operator_set.permute.default, permute_default_0, Ignored())
mul_Scalar_0 = CallFunction(operator_set.mul.Scalar, permute_default_1, KeywordArg('inv_scale'))
broadcast_to_default_0 = CallFunction(operator_set.broadcast_to.default, mul_Scalar_0, Ignored())
reshape_default_0 = CallFunction(operator_set.reshape.default, broadcast_to_default_0, Ignored())
bmm_default = CallFunction(operator_set.bmm.default, reshape_default, reshape_default_0)
reshape_default_1 = CallFunction(operator_set.reshape.default, bmm_default, Ignored())
add_Tensor = CallFunction(operator_set.add.Tensor, reshape_default_1, KeywordArg('attn_mask'), alpha=Ignored())
eq_Scalar = CallFunction(operator_set.eq.Scalar, add_Tensor, Ignored())
logical_not_default = CallFunction(operator_set.logical_not.default, eq_Scalar)
to_dtype = CallFunction(operator_set.to.dtype, logical_not_default, Ignored(), False, False, None)
sum_dim_IntList = CallFunction(operator_set.sum.dim_IntList, to_dtype, Ignored(), True, dtype=Ignored())
eq_Scalar_0 = CallFunction(operator_set.eq.Scalar, sum_dim_IntList, Ignored())
softmax_default = CallFunction(operator_set.softmax.default, add_Tensor, Ignored(), Ignored())
full_like_default = CallFunction(operator_set.full_like.default, softmax_default, Ignored(), dtype=Ignored(), device=Ignored())
where_self = CallFunction(operator_set.where.self, eq_Scalar_0, full_like_default, softmax_default)
broadcast_to_default_1 = CallFunction(operator_set.broadcast_to.default, where_self, Ignored())
reshape_default_2 = CallFunction(operator_set.reshape.default, broadcast_to_default_1, Ignored())
permute_default_2 = CallFunction(operator_set.permute.default, KeywordArg('value'), Ignored())
broadcast_to_default_2 = CallFunction(operator_set.broadcast_to.default, permute_default_2, Ignored())
reshape_default_3 = CallFunction(operator_set.reshape.default, broadcast_to_default_2, Ignored())
bmm_default_0 = CallFunction(operator_set.bmm.default, reshape_default_2, reshape_default_3)
reshape_default_4 = CallFunction(operator_set.reshape.default, bmm_default_0, Ignored())
permute_default_3 = CallFunction(operator_set.permute.default, where_self, Ignored())
broadcast_to_default_3 = CallFunction(operator_set.broadcast_to.default, permute_default_3, Ignored())
reshape_default_5 = CallFunction(operator_set.reshape.default, broadcast_to_default_3, Ignored())
broadcast_to_default_4 = CallFunction(operator_set.broadcast_to.default, KeywordArg('tangents_1'), Ignored())
reshape_default_6 = CallFunction(operator_set.reshape.default, broadcast_to_default_4, Ignored())
bmm_default_1 = CallFunction(operator_set.bmm.default, reshape_default_5, reshape_default_6)
reshape_default_7 = CallFunction(operator_set.reshape.default, bmm_default_1, Ignored())
permute_backward_default = CallFunction(operator_set.permute_backward.default, reshape_default_7, KeywordArg('value'), Ignored())
_sfdp_pattern_29_bs1_training = MultiOutputPattern([reshape_default_4,
  None,
  None,
  permute_backward_default
])


permute_default = CallFunction(operator_set.permute.default, KeywordArg('query'), Ignored())
mul_Scalar = CallFunction(operator_set.mul.Scalar, permute_default, KeywordArg('inv_scale'))
broadcast_to_default = CallFunction(operator_set.broadcast_to.default, mul_Scalar, Ignored())
reshape_default = CallFunction(operator_set.reshape.default, broadcast_to_default, Ignored())
permute_default_0 = CallFunction(operator_set.permute.default, KeywordArg('key'), Ignored())
permute_default_1 = CallFunction(operator_set.permute.default, permute_default_0, Ignored())
mul_Scalar_0 = CallFunction(operator_set.mul.Scalar, permute_default_1, KeywordArg('inv_scale'))
broadcast_to_default_0 = CallFunction(operator_set.broadcast_to.default, mul_Scalar_0, Ignored())
reshape_default_0 = CallFunction(operator_set.reshape.default, broadcast_to_default_0, Ignored())
bmm_default = CallFunction(operator_set.bmm.default, reshape_default, reshape_default_0)
reshape_default_1 = CallFunction(operator_set.reshape.default, bmm_default, Ignored())
add_Tensor = CallFunction(operator_set.add.Tensor, reshape_default_1, KeywordArg('attn_mask'), alpha=Ignored())
eq_Scalar = CallFunction(operator_set.eq.Scalar, add_Tensor, Ignored())
logical_not_default = CallFunction(operator_set.logical_not.default, eq_Scalar)
to_dtype = CallFunction(operator_set.to.dtype, logical_not_default, Ignored(), False, False, None)
sum_dim_IntList = CallFunction(operator_set.sum.dim_IntList, to_dtype, Ignored(), True, dtype=Ignored())
eq_Scalar_0 = CallFunction(operator_set.eq.Scalar, sum_dim_IntList, Ignored())
softmax_default = CallFunction(operator_set.softmax.default, add_Tensor, Ignored(), Ignored())
full_like_default = CallFunction(operator_set.full_like.default, softmax_default, Ignored(), dtype=Ignored(), device=Ignored())
where_self = CallFunction(operator_set.where.self, eq_Scalar_0, full_like_default, softmax_default)
broadcast_to_default_1 = CallFunction(operator_set.broadcast_to.default, where_self, Ignored())
reshape_default_2 = CallFunction(operator_set.reshape.default, broadcast_to_default_1, Ignored())
permute_default_2 = CallFunction(operator_set.permute.default, KeywordArg('value'), Ignored())
broadcast_to_default_2 = CallFunction(operator_set.broadcast_to.default, permute_default_2, Ignored())
reshape_default_3 = CallFunction(operator_set.reshape.default, broadcast_to_default_2, Ignored())
bmm_default_0 = CallFunction(operator_set.bmm.default, reshape_default_2, reshape_default_3)
_sfdp_pattern_29_bs1_inference = CallFunction(operator_set.reshape.default, bmm_default_0, Ignored())


permute_default = CallFunction(operator_set.permute.default, KeywordArg('query'), Ignored())
mul_Scalar = CallFunction(operator_set.mul.Scalar, permute_default, KeywordArg('inv_scale'))
broadcast_to_default = CallFunction(operator_set.broadcast_to.default, mul_Scalar, Ignored())
reshape_default = CallFunction(operator_set.reshape.default, broadcast_to_default, Ignored())
permute_default_0 = CallFunction(operator_set.permute.default, KeywordArg('key'), Ignored())
permute_default_1 = CallFunction(operator_set.permute.default, permute_default_0, Ignored())
mul_Scalar_0 = CallFunction(operator_set.mul.Scalar, permute_default_1, KeywordArg('inv_scale'))
broadcast_to_default_0 = CallFunction(operator_set.broadcast_to.default, mul_Scalar_0, Ignored())
reshape_default_0 = CallFunction(operator_set.reshape.default, broadcast_to_default_0, Ignored())
bmm_default = CallFunction(operator_set.bmm.default, reshape_default, reshape_default_0)
reshape_default_1 = CallFunction(operator_set.reshape.default, bmm_default, Ignored())
add_Tensor = CallFunction(operator_set.add.Tensor, reshape_default_1, KeywordArg('attn_mask'), alpha=Ignored())
eq_Scalar = CallFunction(operator_set.eq.Scalar, add_Tensor, Ignored())
logical_not_default = CallFunction(operator_set.logical_not.default, eq_Scalar)
to_dtype = CallFunction(operator_set.to.dtype, logical_not_default, Ignored(), False, False, None)
sum_dim_IntList = CallFunction(operator_set.sum.dim_IntList, to_dtype, Ignored(), True, dtype=Ignored())
eq_Scalar_0 = CallFunction(operator_set.eq.Scalar, sum_dim_IntList, Ignored())
softmax_default = CallFunction(operator_set.softmax.default, add_Tensor, Ignored(), Ignored())
full_like_default = CallFunction(operator_set.full_like.default, softmax_default, Ignored(), dtype=Ignored(), device=Ignored())
where_self = CallFunction(operator_set.where.self, eq_Scalar_0, full_like_default, softmax_default)
broadcast_to_default_1 = CallFunction(operator_set.broadcast_to.default, where_self, Ignored())
reshape_default_2 = CallFunction(operator_set.reshape.default, broadcast_to_default_1, Ignored())
permute_default_2 = CallFunction(operator_set.permute.default, KeywordArg('value'), Ignored())
broadcast_to_default_2 = CallFunction(operator_set.broadcast_to.default, permute_default_2, Ignored())
reshape_default_3 = CallFunction(operator_set.reshape.default, broadcast_to_default_2, Ignored())
bmm_default_0 = CallFunction(operator_set.bmm.default, reshape_default_2, reshape_default_3)
reshape_default_4 = CallFunction(operator_set.reshape.default, bmm_default_0, Ignored())
permute_default_3 = CallFunction(operator_set.permute.default, where_self, Ignored())
broadcast_to_default_3 = CallFunction(operator_set.broadcast_to.default, permute_default_3, Ignored())
reshape_default_5 = CallFunction(operator_set.reshape.default, broadcast_to_default_3, Ignored())
broadcast_to_default_4 = CallFunction(operator_set.broadcast_to.default, KeywordArg('tangents_1'), Ignored())
reshape_default_6 = CallFunction(operator_set.reshape.default, broadcast_to_default_4, Ignored())
bmm_default_1 = CallFunction(operator_set.bmm.default, reshape_default_5, reshape_default_6)
reshape_default_7 = CallFunction(operator_set.reshape.default, bmm_default_1, Ignored())
permute_backward_default = CallFunction(operator_set.permute_backward.default, reshape_default_7, KeywordArg('value'), Ignored())
_sfdp_pattern_29_half_training = MultiOutputPattern([reshape_default_4,
  None,
  None,
  permute_backward_default
])


permute_default = CallFunction(operator_set.permute.default, KeywordArg('query'), Ignored())
mul_Scalar = CallFunction(operator_set.mul.Scalar, permute_default, KeywordArg('inv_scale'))
broadcast_to_default = CallFunction(operator_set.broadcast_to.default, mul_Scalar, Ignored())
reshape_default = CallFunction(operator_set.reshape.default, broadcast_to_default, Ignored())
permute_default_0 = CallFunction(operator_set.permute.default, KeywordArg('key'), Ignored())
permute_default_1 = CallFunction(operator_set.permute.default, permute_default_0, Ignored())
mul_Scalar_0 = CallFunction(operator_set.mul.Scalar, permute_default_1, KeywordArg('inv_scale'))
broadcast_to_default_0 = CallFunction(operator_set.broadcast_to.default, mul_Scalar_0, Ignored())
reshape_default_0 = CallFunction(operator_set.reshape.default, broadcast_to_default_0, Ignored())
bmm_default = CallFunction(operator_set.bmm.default, reshape_default, reshape_default_0)
reshape_default_1 = CallFunction(operator_set.reshape.default, bmm_default, Ignored())
add_Tensor = CallFunction(operator_set.add.Tensor, reshape_default_1, KeywordArg('attn_mask'), alpha=Ignored())
eq_Scalar = CallFunction(operator_set.eq.Scalar, add_Tensor, Ignored())
logical_not_default = CallFunction(operator_set.logical_not.default, eq_Scalar)
to_dtype = CallFunction(operator_set.to.dtype, logical_not_default, Ignored(), False, False, None)
sum_dim_IntList = CallFunction(operator_set.sum.dim_IntList, to_dtype, Ignored(), True, dtype=Ignored())
eq_Scalar_0 = CallFunction(operator_set.eq.Scalar, sum_dim_IntList, Ignored())
softmax_default = CallFunction(operator_set.softmax.default, add_Tensor, Ignored(), Ignored())
full_like_default = CallFunction(operator_set.full_like.default, softmax_default, Ignored(), dtype=Ignored(), device=Ignored())
where_self = CallFunction(operator_set.where.self, eq_Scalar_0, full_like_default, softmax_default)
broadcast_to_default_1 = CallFunction(operator_set.broadcast_to.default, where_self, Ignored())
reshape_default_2 = CallFunction(operator_set.reshape.default, broadcast_to_default_1, Ignored())
permute_default_2 = CallFunction(operator_set.permute.default, KeywordArg('value'), Ignored())
broadcast_to_default_2 = CallFunction(operator_set.broadcast_to.default, permute_default_2, Ignored())
reshape_default_3 = CallFunction(operator_set.reshape.default, broadcast_to_default_2, Ignored())
bmm_default_0 = CallFunction(operator_set.bmm.default, reshape_default_2, reshape_default_3)
_sfdp_pattern_29_half_inference = CallFunction(operator_set.reshape.default, bmm_default_0, Ignored())


permute_default = CallFunction(operator_set.permute.default, KeywordArg('query'), Ignored())
mul_Scalar = CallFunction(operator_set.mul.Scalar, permute_default, KeywordArg('inv_scale'))
broadcast_to_default = CallFunction(operator_set.broadcast_to.default, mul_Scalar, Ignored())
reshape_default = CallFunction(operator_set.reshape.default, broadcast_to_default, Ignored())
permute_default_0 = CallFunction(operator_set.permute.default, KeywordArg('key'), Ignored())
permute_default_1 = CallFunction(operator_set.permute.default, permute_default_0, Ignored())
mul_Scalar_0 = CallFunction(operator_set.mul.Scalar, permute_default_1, KeywordArg('inv_scale'))
broadcast_to_default_0 = CallFunction(operator_set.broadcast_to.default, mul_Scalar_0, Ignored())
reshape_default_0 = CallFunction(operator_set.reshape.default, broadcast_to_default_0, Ignored())
bmm_default = CallFunction(operator_set.bmm.default, reshape_default, reshape_default_0)
reshape_default_1 = CallFunction(operator_set.reshape.default, bmm_default, Ignored())
add_Tensor = CallFunction(operator_set.add.Tensor, reshape_default_1, KeywordArg('attn_mask'), alpha=Ignored())
eq_Scalar = CallFunction(operator_set.eq.Scalar, add_Tensor, Ignored())
logical_not_default = CallFunction(operator_set.logical_not.default, eq_Scalar)
to_dtype = CallFunction(operator_set.to.dtype, logical_not_default, Ignored(), False, False, None)
sum_dim_IntList = CallFunction(operator_set.sum.dim_IntList, to_dtype, Ignored(), True, dtype=Ignored())
eq_Scalar_0 = CallFunction(operator_set.eq.Scalar, sum_dim_IntList, Ignored())
softmax_default = CallFunction(operator_set.softmax.default, add_Tensor, Ignored(), Ignored())
full_like_default = CallFunction(operator_set.full_like.default, softmax_default, Ignored(), dtype=Ignored(), device=Ignored())
where_self = CallFunction(operator_set.where.self, eq_Scalar_0, full_like_default, softmax_default)
broadcast_to_default_1 = CallFunction(operator_set.broadcast_to.default, where_self, Ignored())
reshape_default_2 = CallFunction(operator_set.reshape.default, broadcast_to_default_1, Ignored())
permute_default_2 = CallFunction(operator_set.permute.default, KeywordArg('value'), Ignored())
broadcast_to_default_2 = CallFunction(operator_set.broadcast_to.default, permute_default_2, Ignored())
reshape_default_3 = CallFunction(operator_set.reshape.default, broadcast_to_default_2, Ignored())
bmm_default_0 = CallFunction(operator_set.bmm.default, reshape_default_2, reshape_default_3)
reshape_default_4 = CallFunction(operator_set.reshape.default, bmm_default_0, Ignored())
permute_default_3 = CallFunction(operator_set.permute.default, where_self, Ignored())
broadcast_to_default_3 = CallFunction(operator_set.broadcast_to.default, permute_default_3, Ignored())
reshape_default_5 = CallFunction(operator_set.reshape.default, broadcast_to_default_3, Ignored())
broadcast_to_default_4 = CallFunction(operator_set.broadcast_to.default, KeywordArg('tangents_1'), Ignored())
reshape_default_6 = CallFunction(operator_set.reshape.default, broadcast_to_default_4, Ignored())
bmm_default_1 = CallFunction(operator_set.bmm.default, reshape_default_5, reshape_default_6)
reshape_default_7 = CallFunction(operator_set.reshape.default, bmm_default_1, Ignored())
permute_backward_default = CallFunction(operator_set.permute_backward.default, reshape_default_7, KeywordArg('value'), Ignored())
_sfdp_pattern_29_half_bs1_training = MultiOutputPattern([reshape_default_4,
  None,
  None,
  permute_backward_default
])


permute_default = CallFunction(operator_set.permute.default, KeywordArg('query'), Ignored())
mul_Scalar = CallFunction(operator_set.mul.Scalar, permute_default, KeywordArg('inv_scale'))
broadcast_to_default = CallFunction(operator_set.broadcast_to.default, mul_Scalar, Ignored())
reshape_default = CallFunction(operator_set.reshape.default, broadcast_to_default, Ignored())
permute_default_0 = CallFunction(operator_set.permute.default, KeywordArg('key'), Ignored())
permute_default_1 = CallFunction(operator_set.permute.default, permute_default_0, Ignored())
mul_Scalar_0 = CallFunction(operator_set.mul.Scalar, permute_default_1, KeywordArg('inv_scale'))
broadcast_to_default_0 = CallFunction(operator_set.broadcast_to.default, mul_Scalar_0, Ignored())
reshape_default_0 = CallFunction(operator_set.reshape.default, broadcast_to_default_0, Ignored())
bmm_default = CallFunction(operator_set.bmm.default, reshape_default, reshape_default_0)
reshape_default_1 = CallFunction(operator_set.reshape.default, bmm_default, Ignored())
add_Tensor = CallFunction(operator_set.add.Tensor, reshape_default_1, KeywordArg('attn_mask'), alpha=Ignored())
eq_Scalar = CallFunction(operator_set.eq.Scalar, add_Tensor, Ignored())
logical_not_default = CallFunction(operator_set.logical_not.default, eq_Scalar)
to_dtype = CallFunction(operator_set.to.dtype, logical_not_default, Ignored(), False, False, None)
sum_dim_IntList = CallFunction(operator_set.sum.dim_IntList, to_dtype, Ignored(), True, dtype=Ignored())
eq_Scalar_0 = CallFunction(operator_set.eq.Scalar, sum_dim_IntList, Ignored())
softmax_default = CallFunction(operator_set.softmax.default, add_Tensor, Ignored(), Ignored())
full_like_default = CallFunction(operator_set.full_like.default, softmax_default, Ignored(), dtype=Ignored(), device=Ignored())
where_self = CallFunction(operator_set.where.self, eq_Scalar_0, full_like_default, softmax_default)
broadcast_to_default_1 = CallFunction(operator_set.broadcast_to.default, where_self, Ignored())
reshape_default_2 = CallFunction(operator_set.reshape.default, broadcast_to_default_1, Ignored())
permute_default_2 = CallFunction(operator_set.permute.default, KeywordArg('value'), Ignored())
broadcast_to_default_2 = CallFunction(operator_set.broadcast_to.default, permute_default_2, Ignored())
reshape_default_3 = CallFunction(operator_set.reshape.default, broadcast_to_default_2, Ignored())
bmm_default_0 = CallFunction(operator_set.bmm.default, reshape_default_2, reshape_default_3)
_sfdp_pattern_29_half_bs1_inference = CallFunction(operator_set.reshape.default, bmm_default_0, Ignored())
