# TensorPlay documentation build configuration file, adapted from
# repo actually uses; see docs/README.md for the deviation list).

import os
import sys

# -- Path setup ------------------------------------------------------------

# Prefer a built/installed tensorplay over the in-repo Python sources: the
# package dir here has no version.py or compiled _C, so importing it directly
# fails without a source build. Only fall back to the repo root when nothing
# is installed, e.g. for a plain `make html` after an in-place build.
try:
    import tensorplay  # noqa: E402,F401
except ModuleNotFoundError:
    sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
    import tensorplay  # noqa: E402,F401

# The API prose docstrings are attached lazily by this module; autodoc reads
# __doc__ attributes during the build, so the attachments must run first.
import tensorplay._docs  # noqa: E402,F401

# -- Project information -----------------------------------------------------

project = "TensorPlay"
copyright = "2025, zlx"
author = "TensorPlay contributors"
release = getattr(tensorplay, "__version__", "main")

version = release

# -- General configuration ----------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.napoleon",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.viewcode",
    "sphinx_copybutton",
    "myst_parser",
]

templates_path = ["_templates"]
# autosummary writes .rst stubs into source/generated, so both suffixes must
# be registered even though all handwritten pages are MyST markdown.
source_suffix = {
    ".md": "markdown",
    ".rst": "restructuredtext",
}
exclude_patterns = []
master_doc = "index"

# MyST options used by this documentation build.
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_image",
]
# dollarmath's default delimiter matching treats any pair of `$` as an equation,
# which swallows literal shell variables in prose. Requiring the delimiters to
# sit flush against the content keeps those as text while real formulas render.
myst_dmath_allow_space = False
myst_heading_anchors = 4

# The following options show the correct "next/previous" banners when supported
# by the selected theme.

# autodoc / autosummary options
autosummary_generate = True
numpydoc_show_class_members = False
# Render docstring "Attributes:" blocks as :ivar: fields instead of object
# descriptions; emitting a second py:attribute per field duplicates what
# autodoc already documents for the same members.
napoleon_use_ivar = True

# autosectionlabel throws warnings if section names are duplicated.
# Do not throw a warning for duplicated section names in different documents.
autosectionlabel_prefix_document = True

# Disable docstring inheritance.
autodoc_inherit_docstrings = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ---------------------------------------------------

html_theme = "sphinx_book_theme"

html_static_path = ["_static"]

html_title = f"{project} documentation"

# -- Intersphinx -----------------------------------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# -- Nitpick and warnings ----------------------------------------------------------

nitpicky = False


import re

_SIGNATURE_ONLY = re.compile(r"^\s*[\w.]+\([^()]*\)\s*->", re.S)

_STDLIB_BYTE_CONVERSION = (
    "Return the integer represented by the given array of bytes.",
    "Return an array of bytes representing an integer.",
)


_MASKED_OPS_WRAPPER = re.compile(r"^Masking-aware application of \S+ to this MaskedTensor\.$")


def _strip_reference_assets(app, what, name, obj, options, lines):
    # Generated assets under docs/source/scripts/*_images are not shipped
    # here; the directives would otherwise emit one unreadable-image warning
    # per scheduler/activation entry.
    lines[:] = [
        line for line in lines
        if not re.match(r"^\s*\.\.\s+image::\s+\S*(?:scripts/|_images/)", line)
        and "Henry2019" not in line
    ]
    # Enum helpers re-export the built-in int conversions; their inherited
    # prose contains inline markup that does not survive reST rendering and
    # duplicates what the Python reference already documents.
    text = "\n".join(lines).strip()
    if name.endswith((".from_bytes", ".to_bytes")) and text.startswith(_STDLIB_BYTE_CONVERSION):
        lines[:] = []
        return
    # The masked-tensor op wrappers share one autogenerated one-liner
    # ("Masking-aware application of abs_ to this MaskedTensor."). The
    # trailing underscore on the op name is read by reST as a link
    # reference and the text carries no information the method name does
    # not already convey, so it is dropped.
    if _MASKED_OPS_WRAPPER.match(text):
        lines[:] = []
        return
    # The masked reduction/normalization docstrings render into a colon
    # field block whose wrapped description lines are re-parsed as new
    # :keyword: fields (the field name is a whole phrase rather than an
    # identifier), so the argument block does not survive rendering here.
    # The parameters are already shown in the rendered signature, so the
    # argument block is dropped and the descriptive prose plus the worked
    # example are kept.
    if what == "function" and name.startswith("tensorplay.masked") and (
        any(re.match(r":keyword\s+\w+\s", ln) for ln in lines)
        or any(":keyword :attr:" in ln for ln in lines)
    ):
        arg_start = next((i for i, ln in enumerate(lines) if ln.startswith(":param ")), None)
        example_start = next((i for i, ln in enumerate(lines) if ln.startswith("Example::")), None)
        if arg_start is not None and example_start is not None and example_start > arg_start:
            lines[:] = lines[:arg_start] + [""] + lines[example_start:]
            return
    # Native ops whose __doc__ is just the generated C++ signature
    # ("op(Tensor a, *, int dim=0) -> Tensor"): rendered as rst it trips
    # inline-markup warnings and carries no information beyond the stub
    # signature autodoc already prints.
    if text and "\n" not in text and _SIGNATURE_ONLY.match(text):
        lines[:] = []


def setup(app):
    app.connect("autodoc-process-docstring", _strip_reference_assets)
