"""Generators for TensorGenerated.h/.cpp and TensorRedispatchGenerated.h.

Structure follows the generator's split between redispatch and public methods:
every op gets (1) a backend `redispatch` entry point that resolves its kernel
through the Dispatcher, bumps versions of mutated arguments, and is shared by
the eager path and the autograd wrappers, and (2) a public Tensor method that
performs device checks and consults Autocast/Autograd dispatch keys before
funneling into redispatch.
"""

from __future__ import annotations

from .api_types import (
    autograd_node_name,
    binding_default,
    call_arg_expr,
    cpp_arg_type,
    cpp_default,
    cpp_return_type,
    stub_arg_type,
    stub_arg_type_for,
)
from .model import Argument, NativeFunction


def _variant_instances(f: NativeFunction):
    for v in f.variants:
        yield v


def _is_const_method(f: NativeFunction) -> bool:
    self_a = f.self_arg()
    return bool(self_a) and not self_a.type.is_mutable_ref


def _sig_args(f: NativeFunction, variant: str, *, with_defaults: bool) -> list[str]:
    out = []
    for a in f.args:
        if variant == "method" and a.name == "self":
            continue
        if a.name == "requires_grad":
            continue
        s = f"{cpp_arg_type(a.type)} {a.name}"
        if with_defaults and a.default:
            s += f" = {cpp_default(a.type, a.default)}"
        out.append(s)
    # Merged out= overloads put a defaulted alpha before an output list;
    # C++ requires every parameter after the first default to have one.
    result = []
    default_started = False
    for s in out:
        if "=" in s:
            default_started = True
        elif default_started and "std::vector<Tensor>" in s:
            s = f"{s} = {{}}"
        result.append(s)
    return result


def method_signature(f: NativeFunction, variant: str, *, declaration: bool,
                     qualified: bool = False) -> str:
    ret = cpp_return_type(f)
    args = ", ".join(_sig_args(f, variant, with_defaults=declaration))
    qual = "Tensor::" if qualified else ""
    sig = f"{ret} {qual}{f.cpp_name}({args})"
    if variant == "method" and _is_const_method(f):
        sig += " const"
    return sig


# ---------------------------------------------------------------------------
# Device resolution (shared between the .cpp emitters)
# ---------------------------------------------------------------------------

def _device_source(f: NativeFunction, variant: str) -> tuple[str, str]:
    """Return (dispatch_key_source, target_device_expr)."""
    cpu = "Device(DeviceType::CPU)"
    device_arg = f.arg("device")
    if device_arg is not None:
        self_a = f.self_arg()
        if device_arg.type.is_opt:
            if f.base_name.endswith("_like") and self_a is not None:
                if variant == "method":
                    val = (f"{device_arg.name}.has_value() ? *{device_arg.name} "
                           ": device()")
                else:
                    val = (f"{device_arg.name}.has_value() ? *{device_arg.name} "
                           f": {self_a.name}.device()")
                return val, val
            val = (f"{device_arg.name}.has_value() ? *{device_arg.name} : {cpu}")
            return val, val
        return device_arg.name, device_arg.name
    if variant == "method":
        return "device()", "device()"
    first_tensor = next((a for a in f.args if a.type.kind == "Tensor"
                         and not a.type.is_opt and not a.type.is_list), None)
    if first_tensor is not None:
        return f"{first_tensor.name}.device()", f"{first_tensor.name}.device()"
    first_list = next((a for a in f.args if a.type.is_tensor_like and a.type.is_list), None)
    if first_list is not None:
        val = (f"({first_list.name}.empty() ? {cpu} : "
               f"{first_list.name}[0].device())")
        return val, val
    return cpu, cpu


# ---------------------------------------------------------------------------
# TensorGenerated.h  (included inside class Tensor)
# ---------------------------------------------------------------------------

def generate_header(funcs: list[NativeFunction]) -> str:
    lines = [
        "// Generated by tools/codegen/main.py -- DO NOT EDIT",
        "#pragma once",
        "#include <tuple>",
        "",
    ]
    seen_decl = set()
    for f in funcs:
        if f.skip_implementation:
            # The core Tensor method is the implementation (gen_tpx routes
            # through it and generate_cpp skips the definition); re-declaring
            # it here would collide with p10/include/Tensor.h -- a class may
            # not declare the same member twice.
            continue
        for variant in _variant_instances(f):
            # (`int[]`) intentionally share the same std::vector ABI.  Their
            # schema defaults may differ (`padding=0` vs `padding=[]`), but
            # C++ cannot overload those declarations.  Deduplicate on the
            # signature without defaults, matching generate_cpp's definition
            key = method_signature(f, variant, declaration=False)
            if key in seen_decl:
                continue
            seen_decl.add(key)
            # Function variants become static members of Tensor (factory
            # surface, e.g. Tensor::zeros), method variants are instance
            # methods -- same as the reference layout.
            prefix = "static " if variant == "function" else ""
            lines.append(prefix + method_signature(f, variant, declaration=True) + ";")
            lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# detail::redispatch_* helpers + Tensor methods (.cpp)
# ---------------------------------------------------------------------------

_CPP_INCLUDES = """// Generated by tools/codegen/main.py -- DO NOT EDIT
#include "Tensor.h"
#include "tensorplay/ops/TensorRedispatchGenerated.h"
#include "Dispatcher.h"
#include "Exception.h"
#include "DispatchKey.h"
#include "GradMode.h"
#include "InferenceMode.h"
#include "DType.h"
#include "Scalar.h"
#include "SizesAndStrides.h"
#include "Device.h"
#include "TypePromotion.h"
#include "autocast_mode.h"
#include "Profiler.h"
#ifdef USE_CUDA
#include "CUDARuntime.h"
#endif
#include <tuple>
#include <utility>
"""


def _emit_redispatch(lines, f, variant, dev_src):
    ret = cpp_return_type(f)
    tmpl = [ret]
    rd_args, rd_call = [], []
    for a in f.args:
        if a.name == "requires_grad":
            continue
        st = stub_arg_type(a.type)
        tmpl.append(st)
        rd_args.append(f"{st} {a.name}")
        rd_call.append(a.name)

    rd_dev = dev_src.replace("device()", "self.device()") if variant == "method" else dev_src
    mutable = [a.name for a in f.mutable_args]

    redispatch_name = f"redispatch_{f.cpp_name}_{variant}"
    lines.append("namespace detail {")
    lines.append(f"TENSORPLAY_API {ret} {redispatch_name}({', '.join(rd_args)}) {{")
    # Op-level profiler record: every dispatched execution passes through
    # exactly one redispatch funnel, so this is the single instrumentation
    # dispatch).  Inactive cost: one acquire-load of a static atomic.
    lines.append(
        f'    tensorplay::prof::OpRecord __tp_prof_rec("{f.func_name}");')
    # record_shapes: only tensor-like args are captured, and only when the
    # session requested shapes (second load sits inside the active branch,
    # so the fully-inactive path still costs exactly one load).
    shape_args = [
        a for a in f.args
        if a.type.is_tensor_like and a.name != "requires_grad"
    ]
    if shape_args:
        lines.append(
            "    if (tensorplay::prof::g_capture_shapes.load("
            "std::memory_order_acquire)) {")
        lines.append("        std::vector<std::vector<int64_t>> __tp_prof_shapes;")
        lines.append("        std::vector<int32_t> __tp_prof_dtypes;")
        for a in shape_args:
            t = a.type
            if t.is_list:
                lines.append(
                    f"        for (const auto& __tp_t : {a.name}) {{")
                lines.append(
                    "            __tp_prof_shapes.push_back("
                    "static_cast<std::vector<int64_t>>(__tp_t.shape()));")
                lines.append(
                    "            __tp_prof_dtypes.push_back(static_cast<int32_t>"
                    "(__tp_t.dtype()));")
                lines.append("        }")
            elif t.is_opt:
                lines.append(
                    f"        if ({a.name}.has_value()) {{")
                lines.append(
                    f"            __tp_prof_shapes.push_back(static_cast<"
                    f"std::vector<int64_t>>({a.name}->shape()));")
                lines.append(
                    f"            __tp_prof_dtypes.push_back(static_cast<int32_t>"
                    f"({a.name}->dtype()));")
                lines.append("        }")
            elif t.is_mutable_ref:
                lines.append(
                    f"        __tp_prof_shapes.push_back("
                    f"static_cast<std::vector<int64_t>>({a.name}.shape()));")
                lines.append(
                    f"        __tp_prof_dtypes.push_back(static_cast<int32_t>"
                    f"({a.name}.dtype()));")
            else:
                lines.append(
                    f"        __tp_prof_shapes.push_back("
                    f"static_cast<std::vector<int64_t>>({a.name}.shape()));")
                lines.append(
                    f"        __tp_prof_dtypes.push_back(static_cast<int32_t>"
                    f"({a.name}.dtype()));")
        lines.append(
            "        __tp_prof_rec.set_io_meta(std::move(__tp_prof_shapes),"
            " std::move(__tp_prof_dtypes));")
        lines.append("    }")
    # GPU timeline: pool-backed cudaEvent pair around dispatched CUDA work
    # (USE_CUDA builds only; resolved at session stop after one sync).
    lines.append("#ifdef USE_CUDA")
    lines.append("    tensorplay::prof::GpuTimerPair __tp_gpu(__tp_prof_rec);")
    lines.append("#endif")
    lines.append("#ifdef USE_CUDA")
    lines.append(f"    cuda::OptionalCUDAGuard device_guard({rd_dev});")
    lines.append("#endif")
    lines.append(
        f'    static const OperatorHandle op_handle = '
        f'Dispatcher::singleton().findHandle("{f.func_name}");')
    lines.append(f"    DispatchKey dispatch_key = computeDispatchKey({rd_dev});")
    lines.append("#ifdef USE_CUDA")
    lines.append(f"    __tp_gpu.arm({rd_dev});")
    lines.append("#endif")

    call = f"DispatchStub<{', '.join(tmpl)}>::call(op_handle, dispatch_key, {', '.join(rd_call)})"
    ret_void = ret == "void"
    if not mutable:
        if ret_void:
            lines.append(f"    {call};")
        else:
            lines.append(f"    auto&& __tp_result = {call};")
        lines.append("#ifdef USE_CUDA")
        lines.append("    __tp_gpu.close();")
        lines.append("#endif")
        # Output allocation volume for Tensor-returning ops (memory view).
        if not ret_void and ret == "Tensor":
            lines.append(
                "    if (tensorplay::prof::g_capture_shapes.load("
                "std::memory_order_acquire)) {")
            lines.append(
                "        __tp_prof_rec.set_output_bytes("
                "static_cast<int64_t>(__tp_result.numel()) * "
                "static_cast<int64_t>(__tp_result.itemsize()));")
            lines.append("    }")
        if not ret_void:
            lines.append("    return std::move(__tp_result);")
    else:
        lines.append(f"    {call};" if ret_void else
                     f"    auto&& __tp_result = {call};")
        lines.append("#ifdef USE_CUDA")
        lines.append("    __tp_gpu.close();")
        lines.append("#endif")
        for m in mutable:
            at = f.arg(m).type
            if at.is_mutable_tensor_list:
                lines.append(f"    for (const auto& __tp_tensor : {m}) {{")
                lines.append("        if (__tp_tensor.defined() && !InferenceMode::is_enabled()) __tp_tensor.unsafeGetTensorImpl()->bump_version();")
                lines.append("    }")
            else:
                lines.append(f"    if (!InferenceMode::is_enabled()) {m}.unsafeGetTensorImpl()->bump_version();")
        lines.append("    return;" if ret_void else
                     "    return std::forward<decltype(__tp_result)>(__tp_result);")
    lines.append("}")
    lines.append("} // namespace detail")
    lines.append("")
    return redispatch_name


def _emit_device_checks(lines, f, variant, target_dev):
    if f.device_check == "NoCheck" or f.cpp_name == "copy_":
        return
    is_factory_like = f.base_name.endswith("_like")
    checked = {"Tensor", "Tensor?", "Tensor[]"}
    for a in f.args:
        if variant == "method" and a.name == "self" and not is_factory_like:
            continue
        if is_factory_like and a.name == "self":
            continue
        t = a.type
        if t.is_mutable_ref:
            kind = "Tensor"
        elif t.is_mutable_tensor_list:
            kind = "Tensor[]"
        elif t.is_tensor_like:
            kind = "Tensor?" if t.is_opt else ("Tensor[]" if t.is_list else "Tensor")
        else:
            continue
        if kind == "Tensor?":
            cond = (f"{a.name}.has_value() && {a.name}->defined() && "
                    f"{a.name}->device() != {target_dev}")
        elif kind == "Tensor[]":
            cond = None
        else:
            cond = f"{a.name}.defined() && {a.name}.device() != {target_dev}"
        if kind == "Tensor[]":
            lines.append(f"    for (const auto& t : {a.name}) {{")
            lines.append(f"        if (t.defined() && t.device() != {target_dev}) {{")
            lines.append('            TP_THROW(DeviceMismatchError, "Expected all tensors to be on the same device, but found one (in ' + a.name + ') on " + t.device().toString() + " and another (' + target_dev.replace('"', '') + ') on " + ' + target_dev + '.toString());')
            lines.append("        }")
            lines.append("    }")
            continue
        lines.append(f"    if ({cond}) {{")
        shown = f"{a.name}" if kind != "Tensor[]" else f"in {a.name}"
        lhs_dev = (f"{a.name}->device().toString()" if kind == "Tensor?"
                   else f"{a.name}.device().toString()")
        lines.append(
            '            TP_THROW(DeviceMismatchError, "Expected all tensors to be on the same device, but found one (' + shown + ') on " + '
            + lhs_dev + ' + " and another (' + target_dev.replace('"', '') + ') on " + ' + target_dev + '.toString());')
        lines.append("    }")


def generate_cpp(funcs: list[NativeFunction], *,
                 autocast_ops: set[str], autograd_ops: dict[str, str]) -> str:
    """autograd_ops maps dispatcher op name -> backward node name."""
    lines = [_CPP_INCLUDES.rstrip("\n"), "", "namespace tensorplay {", ""]

    # Ops declared `variants: function, method` but without a `self` argument
    # produce identical signatures for both variants; emit only the first.
    seen_def = set()
    for f in funcs:
        if f.skip_implementation:
            continue
        for variant in _variant_instances(f):
            def_key = method_signature(f, variant, declaration=False, qualified=True)
            if def_key in seen_def:
                continue
            seen_def.add(def_key)
            dev_src, target_dev = _device_source(f, variant)

            rd_name = _emit_redispatch(lines, f, variant, dev_src)

            # ---- public entry ----
            # Both variants are members of Tensor here: static factories for
            # the function surface, instance methods otherwise.
            lines.append(method_signature(f, variant, declaration=False,
                                          qualified=True) + " {")

            if f.cpp_name == "copy_":
                lines.append('    if (!impl_ || !src.impl_) TP_THROW(RuntimeError, "Tensor not defined");')
                lines.append("    if (this->shape() != src.shape()) {")
                lines.append('    TP_THROW(RuntimeError, "copy_(): shapes mismatch (broadcasting not yet supported)");')
                lines.append("    }")

            if f.cpp_name == "contiguous":
                # contiguous): resolve contiguity BEFORE any dispatch. When the
                # input is already contiguous the input tensor itself is
                # returned; otherwise internal kernel call sites (e.g. the
                # unary pointwise kernels) would route through the autograd
                # `contiguous` wrapper, which tags the aliased input with a
                # ContiguousBackward node and corrupts the graph (leaf inputs
                # would silently become non-leaves).
                self_expr = "(*this)" if variant == "method" else "self"
                lines.append("    {")
                lines.append("        auto __fmt = static_cast<MemoryFormat>(memory_format);")
                lines.append("        if (__fmt == MemoryFormat::Preserve) __fmt = MemoryFormat::Contiguous;")
                lines.append(f"        if ({self_expr}.is_contiguous(__fmt)) return {self_expr};")
                lines.append("    }")

            _emit_device_checks(lines, f, variant, target_dev)

            call_args = []
            for a in f.args:
                if a.name == "requires_grad":
                    continue
                if variant == "method" and a.name == "self":
                    call_args.append("*this")
                else:
                    call_args.append(call_arg_expr(f.base_name, a))
            call_str = ", ".join(call_args)

            ret = cpp_return_type(f)
            ret_void = ret == "void"

            tmpl = [ret] + [stub_arg_type_for(f.base_name, a)
                           for a in f.args if a.name != "requires_grad"]

            # Autocast key outranks Autograd (casts precede VariableType).
            if f.func_name in autocast_ops:
                lines.append("    {")
                lines.append(
                    '        static const OperatorHandle __ac_handle = '
                    f'Dispatcher::singleton().findHandle("{f.func_name}");')
                lines.append(
                    f"        DispatchKey __ac_key = toAutocastKey(computeDispatchKey({dev_src}));")
                # is_enabled first: one thread-local load short-circuits the
                # common (disabled) path before touching the dispatch table.
                lines.append(
                    "        if (autocast::is_enabled(__ac_key) && __ac_handle && __ac_handle.getKernel(__ac_key)) {")
                ac_call = f"DispatchStub<{', '.join(tmpl)}>::call(__ac_handle, __ac_key, {call_str})"
                if ret_void:
                    lines.append(f"            {ac_call};")
                    lines.append("            return;")
                else:
                    lines.append(f"            return {ac_call};")
                lines.append("        }")
                lines.append("    }")

            node = autograd_ops.get(f.func_name)
            if node:
                lines.append("    if (GradMode::is_enabled()) {")
                lines.append(
                    '        static const OperatorHandle ag_handle = '
                    f'Dispatcher::singleton().findHandle("{f.func_name}");')
                lines.append(
                    f"        DispatchKey ag_key = toAutogradKey(computeDispatchKey({dev_src}));")
                lines.append("        if (ag_handle && ag_handle.getKernel(ag_key)) {")
                ag_call = f"DispatchStub<{', '.join(tmpl)}>::call(ag_handle, ag_key, {call_str})"
                if ret_void:
                    lines.append(f"            {ag_call};")
                    lines.append("            return;")
                else:
                    lines.append(f"            return {ag_call};")
                lines.append("        }")
                lines.append("    }")

            tail = f"detail::{rd_name}({call_str})"
            lines.append(f"    {'return ' + tail + ';' if not ret_void else tail + ';'}")
            lines.append("}")
            lines.append("")

    lines.append("} // namespace tensorplay")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# TensorRedispatchGenerated.h
# ---------------------------------------------------------------------------

def generate_redispatch_header(funcs: list[NativeFunction]) -> str:
    lines = [
        "// Generated by tools/codegen/main.py -- DO NOT EDIT",
        "#pragma once",
        '#include "Tensor.h"',
        '#include "Macros.h"',
        "",
        "namespace tensorplay {",
        "namespace detail {",
        "",
    ]
    for f in funcs:
        if f.skip_implementation:
            continue
        for variant in _variant_instances(f):
            ret = cpp_return_type(f)
            rd_args = [f"{stub_arg_type(a.type)} {a.name}"
                       for a in f.args if a.name != "requires_grad"]
            lines.append(
                f"TENSORPLAY_API {ret} redispatch_{f.cpp_name}_{variant}({', '.join(rd_args)});")
            lines.append("")
    lines.extend(["} // namespace detail", "} // namespace tensorplay"])
    return "\n".join(lines)
