"""Generation of tensorplay/functional.py (the Python functional surface).

Keeps the reference implementation's public contract: keyword-compatible
wrappers over the generated pybind functions, Scalar normalization, device
normalization, and compiler graph capture hooks.
"""

from __future__ import annotations

from .api_types import py_default_for, python_default
from .model import NativeFunction

_HEADER = '''# Generated by tools/codegen/gen.py -- Do not edit directly

import tensorplay
import tensorplay._C as _C
from tensorplay._C import DType
from tensorplay.compiler.graph import capture_call as _capture_call

def _ensure_device(device):
    if device is None or device is Ellipsis:
        return tensorplay.device("cpu")
    if isinstance(device, str):
        return tensorplay.device(device)
    return device
'''


def _param_name(a) -> str:
    name = a.python_name
    return 'input' if name == 'self' else name


def _capture_line(lines, fn_name, params):
    tup = ', '.join(params)
    if len(params) == 1:
        tup += ','
    lines.append(f'    _captured = _capture_call({fn_name}, ({tup}), {{}})')
    lines.append('    if _captured is not None:')
    lines.append('        return _captured')


def generate_functional_py(funcs: list[NativeFunction]) -> str:
    lines = [_HEADER]

    seen: set[str] = set()
    has_matmul_out = any(f.func_name == 'matmul.out' for f in funcs)

    for f in funcs:
        name = f.cpp_name
        if name in seen or 'function' not in f.variants and 'method' not in f.variants:
            continue

        # linalg ops are exposed through the tensorplay.linalg package only
        # (mirrors torch, where they live under torch.linalg).
        if name.startswith('linalg_'):
            continue

        # ---- overload families routed straight to the extension -------------
        if name == 'where' and 'function' in f.variants:
            seen.add(name)
            lines += [
                'def where(condition, input, other):',
                '    _captured = _capture_call(where, (condition, input, other), {})',
                '    if _captured is not None:',
                '        return _captured',
                '    _input_is_tensor = isinstance(input, tensorplay.Tensor)',
                '    _other_is_tensor = isinstance(other, tensorplay.Tensor)',
                '    if not _input_is_tensor:',
                '        input = tensorplay.Scalar(input)',
                '    if not _other_is_tensor:',
                '        other = tensorplay.Scalar(other)',
                '    return _C.where(condition=condition, self=input, other=other)',
                '',
            ]
            continue

        if name.startswith('_foreach_') and 'function' in f.variants:
            seen.add(name)
            lines += [
                f'def {name}(input, *args, **kwargs):',
                f'    _captured = _capture_call({name}, (input, *args), kwargs)',
                '    if _captured is not None:',
                '        return _captured',
                f'    return _C.{name}(input, *args, **kwargs)',
                '',
            ]
            continue

        # ---- factory functions ---------------------------------------------
        if ('function' in f.variants and
                name in ('randn', 'rand', 'zeros', 'ones', 'empty')):
            seen.add(name)
            pin_ok = name in ('zeros', 'ones', 'empty')
            pin_param = ', pin_memory=False' if pin_ok else ''
            pin_arg = ', pin_memory=pin_memory' if pin_ok else ''
            cap_kwargs = ("{'dtype': dtype, 'device': device"
                          + (", 'pin_memory': pin_memory" if pin_ok else "")
                          + ", 'requires_grad': requires_grad}")
            lines += [
                f'def {name}(*size, dtype=DType.float32, device=None{pin_param}, requires_grad=False):',
                '    if len(size) == 1 and (isinstance(size[0], (list, tuple)) or hasattr(size[0], \'__iter__\')):',
                '        _size = size[0]',
                '    else:',
                '        _size = size',
                f'    _captured = _capture_call({name}, tuple(size), {cap_kwargs})',
                '    if _captured is not None:',
                '        return _captured',
                f'    return _C.{name}(size=list(_size), dtype=dtype, device=_ensure_device(device){pin_arg}, requires_grad=requires_grad)',
                '',
            ]
            continue

        if name == 'arange' and 'function' in f.variants:
            seen.add(name)
            lines += [
                'def arange(*args, dtype=DType.undefined, device=None, requires_grad=False):',
                "    _captured = _capture_call(arange, tuple(args), {'dtype': dtype, 'device': device, 'requires_grad': requires_grad})",
                '    if _captured is not None:',
                '        return _captured',
                '    if len(args) == 1:',
                '        return _C.arange(end=args[0], dtype=dtype, device=_ensure_device(device), requires_grad=requires_grad)',
                '    elif len(args) == 2:',
                '        return _C.arange(start=args[0], end=args[1], dtype=dtype, device=_ensure_device(device), requires_grad=requires_grad)',
                '    elif len(args) == 3:',
                '        return _C.arange(start=args[0], end=args[1], step=args[2], dtype=dtype, device=_ensure_device(device), requires_grad=requires_grad)',
                "    else:",
                "        raise TypeError(f'arange expected 1-3 positional arguments, got {len(args)}')",
                '',
            ]
            continue

        if 'function' in f.variants:
            seen.add(name)

            if name == 'matmul' and has_matmul_out:
                lines += [
                    'def matmul(input, other, *, out=None):',
                    '    if out is not None:',
                    '        return _C.matmul(self=input, other=other, out=out)',
                    '    _captured = _capture_call(matmul, (input, other), {})',
                    '    if _captured is not None:',
                    '        return _captured',
                    '    return _C.matmul(self=input, other=other)',
                    '',
                ]
                continue

            arg_strs, call_args = [], []
            for a in f.args:
                pname = _param_name(a)
                s = pname
                dft = py_default_for(f, a, 'python')
                if dft is not None:
                    s += f'={dft}'
                elif a.default:
                    s += f'={python_default(a.type, a.default)}'
                arg_strs.append(s)
                if a.name == 'device':
                    rhs = pname if name.endswith('_like') else f'_ensure_device({pname})'
                    call_args.append(f'{a.python_name}={rhs}')
                else:
                    call_args.append(f'{a.python_name}={pname}')

            lines.append(f'def {name}({", ".join(arg_strs)}):')
            _capture_line(lines, name, [_param_name(a) for a in f.args])

            for a in f.args:
                t, pname = a.type, _param_name(a)
                if t.kind == 'Scalar' and not t.is_opt:
                    lines.append(
                        f'    if not isinstance({pname}, (tensorplay.Scalar, tensorplay.Tensor)):')
                    lines.append(f'        {pname} = tensorplay.Scalar({pname})')
                elif t.kind == 'Scalar' and t.is_opt:
                    lines.append(
                        f'    if {pname} is not None and not isinstance({pname}, (tensorplay.Scalar, tensorplay.Tensor)):')
                    lines.append(f'        {pname} = tensorplay.Scalar({pname})')
                elif t.is_tensor_like and not t.is_list and a.default == '{}':
                    lines.append(f'    if {pname} is None:')
                    lines.append(f'        {pname} = tensorplay.Tensor()')

            lines.append(f'    return _C.{name}({", ".join(call_args)})')
            lines.append('')
            continue

        # ---- method-only wrappers ------------------------------------------
        if 'method' in f.variants:
            seen.add(name)
            args = f.args
            if not args or args[0].name != 'self':
                continue
            arg_strs = ['input']
            call_args = []
            for a in args[1:]:
                pname = a.python_name
                s = pname
                dft = py_default_for(f, a, 'python')
                if dft is not None:
                    s += f'={dft}'
                elif a.default:
                    s += f'={python_default(a.type, a.default)}'
                arg_strs.append(s)
                call_args.append(f'{pname}={pname}')
            lines.append(f'def {name}({", ".join(arg_strs)}):')
            if not name.endswith('_'):
                _capture_line(lines, name,
                              ['input'] + [a.python_name for a in args[1:]])
            lines.append(f'    return input.{name}({", ".join(call_args)})')
            lines.append('')
    return '\n'.join(lines) + '\n'
