"""CPython C-API fast-path generator -- upstream gen_python_functions
alignment slice 1.

Per op emits one ``METH_FASTCALL | METH_KEYWORDS`` function that parses
positional/keyword args against the schema, unpacks through the
``CPythonBridge.h`` helpers, calls the generated ``tpx::ops`` symbol and
packs the result.  pybind11 overload dispatch is bypassed; the existing
binding surface stays untouched.

Types without a bridge mapping are skipped and counted, mirroring
upstream's "unsupported signature" fallthrough.
"""

from __future__ import annotations

from .api_types import cpp_arg_type
from .main import CodegenContext, register_generator

# schema type -> (bridge call template, doc)
_BRIDGE = {
    "const Tensor&": "tpx_py_tensor({n})",
    "Tensor&": "tpx_py_tensor({n})",
    "const Scalar&": "tpx_py_scalar({n})",
    "Scalar": "tpx_py_scalar({n})",
    "std::optional<Tensor>": "tpx_py_opt_tensor({n})",
    "int64_t": "tpx_py_int64({n})",
    "double": "tpx_py_double({n})",
    "bool": "tpx_py_bool({n})",
    "std::optional<int64_t>": "tpx_py_opt_int64({n})",
    "std::optional<double>": "tpx_py_opt_double({n})",
    "std::optional<bool>": "tpx_py_opt_bool({n})",
    "std::optional<Scalar>": "tpx_py_opt_scalar({n})",
    "std::vector<int64_t>": "tpx_py_intlist({n})",
    "std::string": "tpx_py_string({n})",
    "DType": "tpx_py_dtype({n})",
    "std::optional<DType>": "tpx_py_opt_dtype({n})",
}

_RET_SHAPES = {"void", "value", "tuple", "list", "mut_ref"}


def _emit_op(out: list[str], f, variant: str) -> str | None:
    """Emit one entry point; return its name or None if unsupported."""
    slots: list[tuple[str, str]] = []          # (argname, bridge expr)
    for i, a in enumerate(f.args):
        if a.name == "requires_grad":
            continue
        tpl = _BRIDGE.get(cpp_arg_type(a.type))
        if tpl is None:
            return None                        # unsupported type -> skip op
        slots.append((a.name, tpl.format(n=f"s.pos({i})")))

    if f.cpp_return_kind not in _RET_SHAPES:
        return None

    fn = f"pyop_{f.cpp_name}_{variant}"
    nargs = len(slots)
    kwlist = ('static const char* kwlist[] = {'
              + ", ".join(f'"{n}"' for n, _ in slots)
              + ', nullptr};') if nargs else \
             'static const char* kwlist[] = {nullptr};'

    call = ", ".join("s_" + n for n, _ in slots)
    op = f"tensorplay::ops::{f.cpp_name}"
    kind = f.cpp_return_kind
    if kind == "void":
        invoke = f"{op}({call}); Py_RETURN_NONE;"
    elif kind == "value":
        invoke = f"auto r = {op}({call}); return tpx_py_wrap(r);"
    elif kind == "tuple":
        invoke = f"auto r = {op}({call}); return tpx_py_wrap_tuple(r);"
    elif kind == "list":
        invoke = f"auto r = {op}({call}); return tpx_py_wrap_list(r);"
    else:                                      # mut_ref
        keep = "tpx_py_keep_alive(s0);" if nargs else ""
        invoke = f"auto& r = {op}({call}); {keep} return tpx_py_wrap(r);"

    out.extend([
        f"static PyObject* {fn}(PyObject*, PyObject* const* args,",
        f"{' ' * len(fn)}                        Py_ssize_t nargs, PyObject* kwnames) {{",
        "    try {",
        f"        {kwlist}",
        f"        auto s = tpx_py_parse(args, nargs, kwnames, kwlist, {nargs}, \"{f.func_name}\");",
    ])
    for name, expr in slots:
        out.append(f"        auto&& s_{name} = {expr};")
    out.append(f"        {invoke}")
    out.extend([
        "    } catch (const std::exception& e) {",
        "        tpx_py_set_error(e);",
        "        return nullptr;",
        "    }",
        "}",
        "",
    ])
    return fn


@register_generator("PythonCAPI")
def _gen_python_capi(ctx: CodegenContext) -> None:
    out: list[str] = [
        "// Generated by tools/codegen/gen_python_c.py -- DO NOT EDIT.",
        "#pragma once",
        "",
        "#include <Python.h>",
        '#include "CPythonBridge.h"',
        "#include <TPXOpsGenerated.h>",
        "",
        "namespace tensorplay { namespace python_c {",
        "",
    ]
    table: list[str] = []
    skipped = 0
    for f in ctx.funcs:
        for variant in f.variants:
            name = _emit_op(out, f, variant)
            if name is None:
                skipped += 1
            else:
                table.append(
                    f'    {{"{f.cpp_name}", (PyCFunction)(void*){name},'
                    f" METH_FASTCALL | METH_KEYWORDS, nullptr}},")

    out += [
        "inline constexpr PyMethodDef generated_methods[] = {",
        *table,
        "    {nullptr, nullptr, 0, nullptr},",
        "};",
        "",
        "inline void register_generated_cpython(PyObject* module) {",
        "    PyModule_AddFunctions(module, const_cast<PyMethodDef*>(generated_methods));",
        "}",
        "",
        "} }  // namespace tensorplay::python_c",
        "",
    ]
    ctx.write("TensorCPythonGenerated.h", "\n".join(out))
