"""pybind11 binding generation (TensorBindingsGenerated.h)."""

from __future__ import annotations

from .api_types import (binding_default, cpp_arg_type, py_default_for,
                        sanitize_name)
from .gen_tpx import _dedup_key, get_tpx_ops_signature
from .model import NativeFunction

_HEADER = """// Generated by tools/codegen/main.py -- DO NOT EDIT
#pragma once
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "Autograd.h"
#include "tensorplay/ops/TPXOpsGenerated.h"

namespace py = pybind11;

namespace tensorplay {
namespace python {

using Tensor = tensorplay::Tensor;
"""


def _emit_def(lines, f: NativeFunction, *, method: bool):
    args = []
    for a in f.args:
        if method and a.name == 'self':
            continue
        s = f'py::arg("{sanitize_name(a.name)}")'
        dft = py_default_for(f, a, 'binding') or (
            binding_default(a.type, a.default) if a.default else None)
        if a.default or dft is not None:
            s += f' = {dft if dft is not None else binding_default(a.type, a.default)}'
        args.append(s)
    args_str = (', ' + ', '.join(args)) if args else ''
    sig = get_tpx_ops_signature(f)
    ptr = f'static_cast<{sig}>(&tensorplay::tpx::ops::{f.cpp_name})'
    lines.append(f'    m.def("{f.cpp_name}", {ptr}{args_str});')


def generate_bindings(funcs: list[NativeFunction]) -> str:
    lines = _HEADER.splitlines()
    lines.append('inline void bind_generated_tensor_methods(py::class_<Tensor>& m) {')
    seen: set[str] = set()
    for f in funcs:
        for variant in f.variants:
            if variant != 'method':
                continue
            if _dedup_key(f) in seen:
                continue
            seen.add(_dedup_key(f))
            _emit_def(lines, f, method=True)
    lines.append('}')
    lines.append('')
    lines.append('inline void bind_generated_op_functions(py::module_& m) {')
    seen.clear()
    for f in funcs:
        for variant in f.variants:
            if variant != 'function':
                continue
            key = _dedup_key(f)
            if key in seen:
                continue
            seen.add(key)
            _emit_def(lines, f, method=False)
    lines += ['}', '} // namespace python', '} // namespace tensorplay']
    return '\n'.join(lines)
