"""Structured-kernel generator -- codegen-side scaffold.

Upstream torchgen drives StructuredKernelGenerator off two schema fields
(`structured`, `structured_delegate`) to factor ops into meta/composite
kernels.  p10 does not yet have a Meta backend or the composite
registration tier, so this module:

1. validates every structured entry against its delegate chain (catches
   typos at generation time instead of link time), and
2. reserves the "Structured" target in run_gen() so that once yaml grows
   structured entries -- or p10 gains Device::Meta -- kernel emission
   slots in here without touching the orchestrator again.
"""

from __future__ import annotations

from collections import Counter

from .main import CodegenContext, register_generator


def validate_structured(funcs) -> list[str]:
    """Return human-readable problems; empty list == consistent."""
    by_name = {f.func_name: f for f in funcs}
    problems: list[str] = []
    delegates: Counter[str] = Counter()

    for f in funcs:
        if f.structured_delegate is not None:
            target = str(f.structured_delegate)
            if target not in by_name:
                problems.append(
                    f"{f.func_name}: structured_delegate '{target}' not found")
    return problems


@register_generator("Structured")
def _gen_structured(ctx: CodegenContext) -> None:
    problems = validate_structured(ctx.funcs)
    n_structured = sum(1 for f in ctx.funcs if f.structured_delegate is None and any(str(g.structured_delegate)==f.func_name for g in ctx.funcs))
    n_delegates = sum(1 for f in ctx.funcs if f.structured_delegate)
    hdr = (
        "// Generated by tools/codegen/gen_structured.py -- DO NOT EDIT.\n"
        "// Reserved slot for upstream-style structured kernels\n"
        f"// ({n_structured} roots, {n_delegates} delegates).\n"
        "#pragma once\n"
    )
    ctx.write("StructuredGenerated.h", hdr)
    if problems:
        raise SystemExit(
            "structured consistency errors:\n  " + "\n  ".join(problems))
