"""Generation of tensorplay/functional.py (the Python functional surface).

Defines keyword-compatible wrappers over generated extension functions,
Scalar normalization, device normalization, and compiler graph capture hooks.
"""

from __future__ import annotations

import keyword

from .api_types import py_default_for, python_default
from .model import NativeFunction

_HEADER = '''# Generated by tools/codegen/main.py -- Do not edit directly

import tensorplay
import tensorplay._C as _C
from tensorplay._C import DType
import tensorplay.graph as _graph
from tensorplay.graph import capture_call as _capture_call
_capturing = _graph.capturing

def _ensure_device(device):
    # None stays None so the C++ factory layer resolves it against
    # only spellings the bindings cannot parse are normalized here.
    if device is None or device is Ellipsis:
        return None
    if isinstance(device, str):
        return tensorplay.device(device)
    return device

_MISSING = object()
'''


def _param_name(a) -> str:
    name = a.python_name
    return 'input' if name == 'self' else name


def _capture_line(lines, fn_name, params, kwparams=()):
    # Eager hot path: the proxy scan (and its kwargs dict) only runs while a
    # Tracer.capture is live -- measured ~1.5us/call of pure-Python tax on
    # factory ops when unguarded.
    #
    # Keyword-only signature parameters must ride the capture as keywords:
    # the public spelling accepts them only as keywords, so recording them
    # positionally would produce a node the interpreter cannot replay, and
    # omitting them would silently drop user values (add's alpha).
    lines.append('    if _capturing():')
    tup = ', '.join(params)
    if len(params) == 1:
        tup += ','
    kw = '{' + ', '.join(f"'{k}': {k}" for k in kwparams) + '}'
    lines.append(f'        _captured = _capture_call({fn_name}, ({tup}), {kw})')
    lines.append('        if _captured is not None:')
    lines.append('            return _captured')


def _sig_param(a) -> str:
    s = _param_name(a)
    if a.default:
        return s + '=' + python_default(a.type, a.default)
    # Added positional (e.g. `int[] dim`) with no schema default: the Python
    # `int[1]? dim=None`.
    return s + '=None'


def _reduction_union_lines(name, base, sib) -> list[str] | None:
    """
    `<op>.dim_IntList(self, dim, keepdim, *, dtype)` behind one public
    signature `op(input, dim=None, keepdim=False, *, dtype=...)`; dim=None
    union wrapper when the overload pair has exactly that shape: identical
    kwonly sets, and the sibling's positionals are the base's with new
    defaulted/list params inserted (subsequence check)."""
    nonout = [g for g in (base, sib)]
    pa = [a for a in base.args if not a.kwonly]
    ps = [a for a in sib.args if not a.kwonly]
    ka = [a for a in base.args if a.kwonly]
    ks = [a for a in sib.args if a.kwonly]
    if ('function' not in base.variants
            or not pa or not pa[0].type.is_tensor_like
            or not ps[0].type.is_tensor_like
            or [a.name for a in ka] != [a.name for a in ks]):
        return None
    base_names = [a.name for a in pa[1:]]
    it = iter([a.name for a in ps[1:]])
    if not all(n in it for n in base_names):
        return None
    sib_extras = [a for a in ps[1:]]
    known = set(base_names)
    added = [a for a in sib_extras if a.name not in known]
    if not added:
        return None
    # Only unambiguous additions: defaulted scalars/flags or a leading dim
    # list / bare-int (which may lack a schema default -- it becomes the
    # None router).
    if not all(a.type.is_list or a.default or a.type.kind == 'int64_t'
               for a in added):
        return None
    route = next((a for a in added
                  if a.type.is_list or not a.default), None)
    if route is None or len(added) > 2:
        return None

    # Existing base positionals keep their slots (tp.norm(x, 2) stays p=2);
    # new params are appended before the kwonly tail.
    sig = ['input'] + [_sig_param(a) for a in pa[1:]]
    sig += [_sig_param(a) for a in added]
    if ka:
        sig += ['*'] + [_sig_param(a) for a in ka]

    # Keyword-only schema args must be captured as keywords: recording them
    # positionally produces a node that cannot be replayed against the public
    # signature (interpreters call ``target(*args, **kwargs)``).
    cap = ['input'] + [_param_name(a) for a in pa[1:] + added]
    cap_kwargs = ('{' + ', '.join(f"'{_param_name(a)}': {_param_name(a)}"
                                  for a in ka) + '}')

    def ccall(g, args):
        # Positional for schema-order params (binding order == schema order);
        # keyword-only schema args must remain keyword at the binding.
        parts = ['input']
        kw_only_names = {a.python_name for a in g.args if a.kwonly}
        for a in args:
            nm = _param_name(a)
            parts.append(f'{nm}={nm}' if a.python_name in kw_only_names else nm)
        for a in g.args:
            if a.kwonly:
                nm = _param_name(a)
                parts.append(f'{nm}={nm}')
        return f'_C.{name}({", ".join(parts)})'

    base_call = ccall(base, pa[1:])
    sib_call = ccall(sib, ps[1:])
    return [
        f'def {name}({", ".join(sig)}):',
        '    if _capturing():',
        '        _captured = _capture_call('
        + f'{name}, ({", ".join(cap)}' + (',' if len(cap) == 1 else '')
        + f'), {cap_kwargs})',
        '        if _captured is not None:',
        '            return _captured',
        f'    if {_param_name(route)} is None:',
        f'        return {base_call}',
        f'    return {sib_call}',
        '',
    ]


def _required_kwonly_sibling(base, group):
    """Find a sibling overload that only adds required keyword-only arguments.

    ``argsort``/``sort`` spell their stable form as a separate overload whose
    every parameter matches the plain overload by name, plus a required
    keyword-only flag (``stable``).  Such a sibling cannot be reached by
    argument shape -- the plain overload accepts the same positional call --
    so the public wrapper has to route on the flag being supplied.  Returns
    ``(sibling, extras)`` or ``None``.
    """
    base_names = {a.python_name for a in base.args}
    for sib in group:
        if sib is base or sib.overload_name == 'out' or sib.out_args:
            continue
        sib_names = {a.python_name for a in sib.args}
        if not base_names <= sib_names:
            continue
        extras = [a for a in sib.args if a.python_name not in base_names]
        if len(extras) == 1 and extras[0].kwonly and not extras[0].default:
            return sib, extras[0]
    return None


def generate_functional_py(funcs: list[NativeFunction]) -> str:
    lines = [_HEADER]

    seen: set[str] = set()

    for f in funcs:
        name = f.cpp_name
        if name in seen or 'function' not in f.variants and 'method' not in f.variants:
            continue

        # Some schema names collide with Python keywords (`and`, `or`, `not`).
        # A module-level `def` cannot spell them; such ops stay reachable via
        # their method variants and operator overloads instead.
        if not name.isidentifier() or keyword.iskeyword(name):
            continue

        # Overload-group facts used by the Python argument parser:
        #    keyword on the public function;
        #  - a base+dim reduction pair (sum/mean/prod/max/min/all/any/
        #    dim=None routing to the base overload (_reduction_union_lines);
        #  - remaining non-out overloads must be selected by positional shape
        #    (tensor_split's int vs int[] vs Tensor), so the wrapper forwards
        #    positionally and lets the FASTCALL group dispatcher pick.
        group = [g for g in funcs if g.cpp_name == name]
        out_variant = next(
            (g for g in group if g.overload_name == 'out' or g.out_args), None)
        multi_overload = sum(
            1 for g in group
            if g.overload_name != 'out' and not g.out_args) > 1

        # linalg ops are exposed through the tensorplay.linalg package only
        if name.startswith('linalg_'):
            continue

        # ---- overload families routed straight to the extension -------------
        if name == 'where' and 'function' in f.variants:
            seen.add(name)
            lines += [
                'def where(condition, input, other):',
                '    if _capturing():',
                '        _captured = _capture_call(where, (condition, input, other), {})',
                '        if _captured is not None:',
                '            return _captured',
                '    _input_is_tensor = isinstance(input, tensorplay.Tensor)',
                '    _other_is_tensor = isinstance(other, tensorplay.Tensor)',
                '    if not _input_is_tensor:',
                '        input = tensorplay.Scalar(input)',
                '    if not _other_is_tensor:',
                '        other = tensorplay.Scalar(other)',
                '    return _C.where(condition=condition, self=input, other=other)',
                '',
            ]
            continue

        # ---- division carrying an optional rounding mode --------------------
        # div/divide pair their plain overloads with mode-taking ones.
        # Forwarding the mode unconditionally would push every plain division
        # through the optional-string parse, so the wrapper only reaches for
        # the mode overloads once a mode is actually supplied.
        if (any(a.name == 'rounding_mode' for g in group for a in g.args)
                and not any(a.name == 'rounding_mode' for a in f.args)):
            seen.add(name)
            lines += [
                f'def {name}(input, other, rounding_mode=None):',
                '    if _capturing():',
                f'        _captured = _capture_call({name}, (input, other), '
                "{'rounding_mode': rounding_mode})",
                '        if _captured is not None:',
                '            return _captured',
                '    if not isinstance(input, tensorplay.Tensor):',
                '        input = tensorplay.as_tensor(input)',
                '    if rounding_mode is None:',
                f'        return input.{name}(other=other)',
                f'    return input.{name}(other=other, rounding_mode=rounding_mode)',
                '',
            ]
            continue

        if name.startswith('_foreach_') and 'function' in f.variants:
            seen.add(name)
            lines += [
                f'def {name}(input, *args, **kwargs):',
                '    if _capturing():',
                f'        _captured = _capture_call({name}, (input, *args), kwargs)',
                '        if _captured is not None:',
                '            return _captured',
                f'    return _C.{name}(input, *args, **kwargs)',
                '',
            ]
            continue

        if name == 'mm' and 'function' in f.variants:
            seen.add(name)
            lines += [
                'def mm(input, mat2):',
                '    if _capturing():',
                '        _captured = _capture_call(mm, (input, mat2), {})',
                '        if _captured is not None:',
                '            return _captured',
                '    return _C.mm(input, mat2)',
                '',
            ]
            continue

        if name == 'addmm' and 'function' in f.variants:
            seen.add(name)
            lines += [
                'def addmm(input, mat1, mat2, beta=1, alpha=1):',
                '    if _capturing():',
                '        _captured = _capture_call(addmm, (input, mat1, mat2, beta, alpha), {})',
                '        if _captured is not None:',
                '            return _captured',
                '    return _C.addmm(input, mat1, mat2, beta=beta, alpha=alpha)',
                '',
            ]
            continue

        if name == 'matmul' and 'function' in f.variants:
            seen.add(name)
            lines += [
                'def matmul(input, other, *, out=None):',
                '    if out is not None:',
                '        return _C.matmul(input, other, out=out)',
                '    if _capturing():',
                '        _captured = _capture_call(matmul, (input, other), {})',
                '        if _captured is not None:',
                '            return _captured',
                '    return _C.matmul(input, other)',
                '',
            ]
            continue

        if name == 'linear' and 'function' in f.variants:
            seen.add(name)
            lines += [
                'def linear(input, weight, bias=None):',
                '    if _capturing():',
                '        _captured = _capture_call(linear, (input, weight, bias), {})',
                '        if _captured is not None:',
                '            return _captured',
                '    return _C.linear(input, weight, bias)',
                '',
            ]
            continue

        # ---- factory functions ---------------------------------------------
        if ('function' in f.variants and
                name in ('randn', 'rand', 'zeros', 'ones', 'empty')):
            seen.add(name)
            pin_ok = name in ('zeros', 'ones', 'empty')
            pin_param = ', pin_memory=False' if pin_ok else ''
            pin_arg = ', pin_memory=pin_memory' if pin_ok else ''
            cap_kwargs = ("{'dtype': DType.undefined if dtype is None else dtype"
                          ", 'device': device"
                          + (", 'pin_memory': pin_memory" if pin_ok else "")
                          + ", 'requires_grad': requires_grad}")
            fast_guard = 'dtype is None and device is None and not requires_grad'
            if pin_ok:
                fast_guard += ' and not pin_memory'
            lines += [
                f'_c_{name} = _C.{name}',
                '',
                f'def {name}(*size, dtype=None, device=None{pin_param}, requires_grad=False):',
                '    if _capturing():',
                f'        _captured = _capture_call({name}, tuple(size), {cap_kwargs})',
                '        if _captured is not None:',
                '            return _captured',
                '    if isinstance(device, str):',
                '        device = tensorplay.device(device)',
                '    elif device is Ellipsis:',
                '        device = None',
                '    if len(size) == 1:',
                '        s0 = size[0]',
                '        if s0.__class__ in (list, tuple):',
                '            size = s0',
                '        elif hasattr(s0, \'__iter__\'):',
                '            size = list(s0)',
                '    # Hot path: every option defaulted -> keyword-free positional',
                '    # call (pybind kwarg parsing costs ~0.3us/call; the C++ side',
                '    # applies identical defaults).',
                f'    if {fast_guard}:',
                f'        return _c_{name}(size)',
                f'    return _C.{name}(size=size, dtype=dtype, device=device{pin_arg}, requires_grad=requires_grad)',
                '',
            ]
            continue

        if name == 'arange' and 'function' in f.variants:
            seen.add(name)
            # integral args -> int64, any float arg -> default float dtype.
            # Passing Undefined through the binding crashes on some builds.
            lines += [
                'def arange(*args, dtype=DType.undefined, device=None, requires_grad=False):',
                "    _captured = _capture_call(arange, tuple(args), {'dtype': dtype, 'device': device, 'requires_grad': requires_grad})",
                '    if _captured is not None:',
                '        return _captured',
                '    if dtype == DType.undefined:',
                '        _has_float = False',
                '        for _a in args:',
                '            if isinstance(_a, float):',
                '                _has_float = True',
                '                break',
                '        if _has_float:',
                '            dtype = DType.float32',
                '        else:',
                '            dtype = DType.int64',
                '    if len(args) == 1:',
                '        return _C.arange(end=args[0], dtype=dtype, device=_ensure_device(device), requires_grad=requires_grad)',
                '    elif len(args) == 2:',
                '        return _C.arange(start=args[0], end=args[1], dtype=dtype, device=_ensure_device(device), requires_grad=requires_grad)',
                '    elif len(args) == 3:',
                '        return _C.arange(start=args[0], end=args[1], step=args[2], dtype=dtype, device=_ensure_device(device), requires_grad=requires_grad)',
                "    else:",
                "        raise TypeError(f'arange expected 1-3 positional arguments, got {len(args)}')",
                '',
            ]
            continue

        if name == 'squeeze_copy' and 'function' in f.variants:
            seen.add(name)
            # routes to the base overload, an int to .dim, a sequence to
            # .dims (positional forwarding lets the group dispatcher pick).
            lines += [
                'def squeeze_copy(input, dim=None):',
                '    if _capturing():',
                '        _captured = _capture_call(squeeze_copy, (input, dim), {})',
                '        if _captured is not None:',
                '            return _captured',
                '    if dim is None:',
                '        return _C.squeeze_copy(input)',
                '    if isinstance(dim, (list, tuple)):',
                '        return _C.squeeze_copy(input, list(dim))',
                '    return _C.squeeze_copy(input, dim)',
                '',
            ]
            continue

        if name == 'unique' and 'function' in f.variants:
            seen.add(name)
            # dim form routes to unique_dim; the flat form always computes
            # all three outputs and trims them in Python, matching the
            # reference contract of returning 1/2/3 tensors by flags.
            lines += [
                'def unique(input, sorted=True, return_inverse=False, return_counts=False, dim=None):',
                '    if dim is not None:',
                '        values, inverse, counts = unique_dim(input, dim, sorted, True, True)',
                '        outs = [values]',
                '        if return_inverse:',
                '            outs.append(inverse)',
                '        if return_counts:',
                '            outs.append(counts)',
                '        return outs[0] if len(outs) == 1 else tuple(outs)',
                '    if _capturing():',
                '        _captured = _capture_call(unique, (input, sorted, return_inverse, return_counts), {})',
                '        if _captured is not None:',
                '            return _captured',
                '    values, inverse, counts = _C.unique(input, sorted, True, True)',
                '    outs = [values]',
                '    if return_inverse:',
                '        outs.append(inverse)',
                '    if return_counts:',
                '        outs.append(counts)',
                '    return outs[0] if len(outs) == 1 else tuple(outs)',
                '',
            ]
            continue

        if name == 'unique_consecutive' and 'function' in f.variants:
            seen.add(name)
            # flags false only the output tensor is returned.
            lines += [
                'def unique_consecutive(input, return_inverse=False, return_counts=False, dim=None):',
                '    if _capturing():',
                '        _captured = _capture_call(unique_consecutive, (input, return_inverse, return_counts, dim), {})',
                '        if _captured is not None:',
                '            return _captured',
                '    _result = _C.unique_consecutive(input, return_inverse, return_counts, dim)',
                '    if not return_inverse and not return_counts:',
                '        return _result[0]',
                '    if not return_inverse:',
                '        return _result[0], _result[2]',
                '    if not return_counts:',
                '        return _result[0], _result[1]',
                '    return _result',
                '',
            ]
            continue

        if name == 'trapz' and 'function' in f.variants:
            seen.add(name)
            # x-Tensor form routes to trapz.x, the scalar form to trapz.dx
            # (positional forwarding lets the FASTCALL group dispatcher pick).
            lines += [
                'def trapz(y, x=None, dx=None, dim=-1):',
                '    if _capturing():',
                '        _captured = _capture_call(trapz, (y, x, dx, dim), {})',
                '        if _captured is not None:',
                '            return _captured',
                '    if x is not None:',
                '        return _C.trapz(y, x, dim=dim)',
                '    if dx is None:',
                '        dx = 1.0',
                '    return _C.trapz(y, dx=dx, dim=dim)',
                '',
            ]
            continue

        if name == 'kaiser_window' and 'function' in f.variants:
            seen.add(name)
            # .beta overloads: kaiser_window(window_length, periodic=True,
            # beta=12.0, *, dtype, device, pin_memory).  Always forward to
            lines += [
                'def kaiser_window(window_length, periodic=True, beta=12.0, *, dtype=None, device=None, pin_memory=False):',
                '    if _capturing():',
                '        _captured = _capture_call(kaiser_window, '
                "(window_length, periodic, beta), "
                "{'dtype': dtype, 'device': device, 'pin_memory': pin_memory})",
                '        if _captured is not None:',
                '            return _captured',
                '    if dtype is None:',
                '        dtype = DType.undefined',
                '    return _C.kaiser_window(window_length, periodic, beta, dtype=dtype, device=_ensure_device(device), pin_memory=pin_memory)',
                '',
            ]
            continue

        # Compressed sparse constructors have two call shapes in the native
        # schema: an explicit-size overload and an overload that infers the
        # logical shape from the buffers.  Expose both behind the same Python
        # signature, matching torch.sparse_*_tensor(..., size=None), instead
        # of letting the generated wrapper make `size` mandatory.
        compressed_ctor_names = {
            'sparse_compressed_tensor': ('compressed_indices', 'plain_indices'),
            'sparse_csr_tensor': ('crow_indices', 'col_indices'),
            'sparse_csc_tensor': ('ccol_indices', 'row_indices'),
            'sparse_bsr_tensor': ('crow_indices', 'col_indices'),
            'sparse_bsc_tensor': ('ccol_indices', 'row_indices'),
        }
        if (name in compressed_ctor_names and 'function' in f.variants
                and sum(1 for g in group
                        if g.overload_name != 'out' and not g.out_args) >= 2):
            seen.add(name)
            first, second = compressed_ctor_names[name]
            lines += [
                f'def {name}({first}, {second}, values, size=None, *, dtype=None, layout=None, device=None, pin_memory=False):',
                '    if _capturing():',
                f"        _captured = _capture_call({name}, ({first}, {second}, values, size), {{'dtype': dtype, 'layout': layout, 'device': device, 'pin_memory': pin_memory}})",
                '        if _captured is not None:',
                '            return _captured',
                '    _device = _ensure_device(device)',
                '    if size is None:',
                f'        return _C.{name}({first}, {second}, values, dtype=dtype, layout=layout, device=_device, pin_memory=pin_memory)',
                f'    return _C.{name}({first}, {second}, values, size, dtype=dtype, layout=layout, device=_device, pin_memory=pin_memory)',
                '',
            ]
            continue

        if 'function' in f.variants:
            if f is out_variant:
                # The plain overload of the group owns the out-accepting
                # wrapper; emitting from the .out overload itself would
                # duplicate the schema's own `out` argument.  The plain
                # overload marks the name as seen when it is visited.
                continue
            seen.add(name)

            # A lone Tensor[] positional parameter renders as *args (the
            # FASTCALL layer folds surplus positionals into the list), and
            # that surface outranks the out-union wrapper below -- otherwise
            # chain_matmul(m1, m2, m3) would demand a single list argument.
            if (len(f.args) == 1 and f.args[0].type.is_tensor_like
                    and f.args[0].type.is_list):
                lines.append(f'def {name}(*args):')
                _capture_line(lines, name, ['*args'])
                lines.append(f'    return _C.{name}(*args)')
                lines.append('')
                continue

            # This overload family has two distinct call shapes: omitting p
            # uses the tensor of probabilities, while providing p selects the
            # scalar probability operation.  Keeping the sentinel makes an
            # explicit None distinguishable from an omitted argument.
            if (name == 'bernoulli' and f.overload_name == ''
                    and out_variant is not None
                    and any(g.overload_name == 'p' for g in group)):
                seen.add(name)
                lines += [
                    'def bernoulli(input, p=_MISSING, *, generator=None, out=None):',
                    '    if p is _MISSING:',
                    '        if out is not None:',
                    '            return _C.bernoulli(self=input, generator=generator, out=out)',
                    '        if _capturing():',
                    '            _captured = _capture_call(bernoulli, (input,), {"generator": generator})',
                    '            if _captured is not None:',
                    '                return _captured',
                    '        return _C.bernoulli(self=input, generator=generator)',
                    '    if out is not None:',
                    '        return _C.bernoulli(self=input, p=p, generator=generator, out=out)',
                    '    if _capturing():',
                    '        _captured = _capture_call(bernoulli, (input, p), {"generator": generator})',
                    '        if _captured is not None:',
                    '            return _captured',
                    '    return _C.bernoulli(self=input, p=p, generator=generator)',
                    '',
                ]
                continue

            # A base+dim reduction pair forms one public union signature
            # (dim=None routes to the base overload).  This must win over the
            # out-variant merge below: the pair's dim positional lacks a
            # schema default, so the merge check would reject it and fall
            # back to the base-only wrapper, hiding sum(t, [1]) shapes.
            sibs_pre = [g for g in group if g is not f
                        and g.overload_name != 'out' and not g.out_args]
            if multi_overload:
                for sib in sibs_pre:
                    union = _reduction_union_lines(name, f, sib)
                    if union is not None:
                        seen.add(name)
                        lines += union
                        break
                else:
                    union = None
                if union is not None:
                    continue

            if out_variant is not None:
                # autograd capture (matching the matmul special-case this
                # generalizes).  Schema defaults carry over to the public
                # signature: positional arguments keep them inline, and
                # keyword-only schema arguments stay keyword-only with
                # their defaults, as required by the generated public surface.
                pos = []
                for a in f.args:
                    if a.kwonly:
                        continue
                    p = _param_name(a)
                    if a.default:
                        p += '=' + python_default(a.type, a.default)
                    pos.append(p)
                pos_names = [_param_name(a) for a in f.args if not a.kwonly]
                kwonly = ['*']
                for a in f.args:
                    if not a.kwonly:
                        continue
                    p = _param_name(a)
                    if a.default:
                        p += '=' + python_default(a.type, a.default)
                    kwonly.append(p)
                kw = ", ".join(f"{a.python_name}={_param_name(a)}"
                               for a in f.args)
                merged = []
                # multi-overload groups forward positionally (schema order):
                # siblings may spell the same slot differently (isin's
                # test_element vs test_elements), so a keyword built from
                # this overload's name would reject the matching candidate.
                # Keyword-only schema args stay keyword (the FASTCALL binding
                # rejects them positionally).
                if multi_overload:
                    fwd = [_param_name(a) for a in f.args if not a.kwonly]
                    fwd += [f'{a.python_name}={_param_name(a)}'
                            for a in f.args if a.kwonly]
                else:
                    fwd = None
                # Sibling overloads that only append defaulted positional
                # parameters to the base's positional list fold into one
                # public signature.  The extension-level group dispatcher
                # keeps choosing the candidate by argument shape.
                if multi_overload:
                    base_pos = [a for a in f.args if not a.kwonly]
                    merged = []
                    for sib in group:
                        if sib is f or sib.overload_name == 'out' or sib.out_args:
                            continue
                        sib_pos = [a for a in sib.args if not a.kwonly]
                        if len(sib_pos) <= len(base_pos):
                            continue
                        head_ok = all(
                            sa.python_name == ba.python_name
                            and sa.type == ba.type
                            for sa, ba in zip(sib_pos[:len(base_pos)], base_pos))
                        tail_ok = all(a.default for a in sib_pos[len(base_pos):])
                        if not (head_ok and tail_ok):
                            continue
                        for a in sib_pos[len(base_pos):]:
                            p = _param_name(a)
                            if a.default:
                                p += '=' + python_default(a.type, a.default)
                            pos.append(p)
                            pos_names.append(_param_name(a))
                            merged.append((a.python_name, _param_name(a)))
                    if merged:
                        kw += ", " + ", ".join(
                            f"{n}={p}" for n, p in merged)
                # A sibling that only adds one required keyword-only argument
                # shares every call shape with this overload, so no amount of
                # positional forwarding can reach it.  The public signature
                # carries that argument behind a sentinel and routes on it
                # being supplied.
                kw_route = (_required_kwonly_sibling(f, group)
                            if multi_overload else None)
                if kw_route is not None:
                    kw_sib, kw_extra = kw_route
                    kw_extra_name = _param_name(kw_extra)
                    kwonly.append(f'{kw_extra_name}=_MISSING')
                    kw_call = [_param_name(a) for a in kw_sib.args if not a.kwonly]
                    kw_call += [f'{a.python_name}={_param_name(a)}'
                                for a in kw_sib.args if a.kwonly]
                    # The out form of the routed overload is only reachable
                    # when it spells its destination `out`; grouped multi-output
                    # schemas name theirs individually and are left alone.
                    kw_out = any(
                        (g.overload_name == 'out' or g.out_args)
                        and {a.python_name for a in g.args}
                        >= {a.python_name for a in kw_sib.args} | {'out'}
                        for g in group)
                lines.append(f'def {name}({", ".join(pos + kwonly + ["out=None"])}):')
                if kw_route is not None:
                    lines.append(f'    if {kw_extra_name} is not _MISSING:')
                    if kw_out:
                        lines.append('        if out is not None:')
                        lines.append(
                            f'            return _C.{name}('
                            f'{", ".join(kw_call + ["out=out"])})')
                    cap_kw = ', '.join(
                        f"'{_param_name(a)}': {_param_name(a)}"
                        for a in f.args if a.kwonly)
                    cap_kw = ('{' + cap_kw + (', ' if cap_kw else '')
                              + f"'{kw_extra_name}': {kw_extra_name}" + '}')
                    cap_pos = ', '.join(pos_names)
                    if len(pos_names) == 1:
                        cap_pos += ','
                    lines += [
                        '        if _capturing():',
                        f'            _captured = _capture_call({name}, '
                        f'({cap_pos}), {cap_kw})',
                        '            if _captured is not None:',
                        '                return _captured',
                        f'        return _C.{name}({", ".join(kw_call)})',
                    ]
                if fwd is not None:
                    lines.append(
                        f'    if out is not None:')
                    lines.append(
                        f'        return _C.{name}({", ".join(fwd + ["out=out"])})')
                else:
                    lines.append('    if out is not None:')
                    lines.append(f'        return _C.{name}({kw}, out=out)')
                _capture_line(
                    lines,
                    name,
                    pos_names,
                    tuple(_param_name(a) for a in f.args if a.kwonly),
                )
                if fwd is not None:
                    lines.append(f'    return _C.{name}({", ".join(fwd)})')
                else:
                    lines.append(f'    return _C.{name}({kw})')
                lines.append('')
                continue

            # (broadcast_tensors(*tensors), block_diag(*tensors)); the
            # FASTCALL layer folds surplus positionals into the list.
            seq_varargs = any(
                g.overload_name != 'out' and not g.out_args and len(g.args) == 1
                and g.args[0].type.is_tensor_like and g.args[0].type.is_list
                for g in group)
            if (len(f.args) >= 2 and f.args[0].type.kind == 'str'
                    and f.args[1].type.is_tensor_like and f.args[1].type.is_list):
                head = [_param_name(a) for a in f.args[:1]]
                rest = f.args[1:]
                sig = head[0] + ", *" + rest[0].python_name
                extra = "".join(
                    ", " + _param_name(a) + "=None" for a in rest[1:])
                tail = ""
                for a in rest[1:]:
                    pn = _param_name(a)
                    dft = python_default(a.type, a.default) if a.default else "None"
                    tail += f", {pn} if {pn} is not None else {dft}"
                fwd = head[0] + ", list(" + rest[0].python_name + ")" + tail
                lines.append(f'def {name}({sig}{extra}):')
                _capture_line(lines, name, head + ['*' + rest[0].python_name])
                lines.append(f'    return _C.{name}({fwd})')
                lines.append('')
                continue

            if seq_varargs:
                # Works with or without sibling overloads: a lone tensor hits
                # the plain candidate, surplus positionals fold into the
                # Tensor[] candidate (atleast_2d(t) vs atleast_2d(t1, t2)).
                lines.append(f'def {name}(*args):')
                _capture_line(lines, name, ['*args'])
                lines.append(f'    return _C.{name}(*args)')
                lines.append('')
                continue

            sibs = [g for g in group if g is not f and g.overload_name != 'out'
                       and not g.out_args]
            if multi_overload:
                for sib in sibs:
                    union = _reduction_union_lines(name, f, sib)
                    if union is not None:
                        seen.add(name)
                        lines += union
                        break
                    union = None
                if union is not None:
                    continue
                    continue

            sig_items, call_args = [], []
            for a in f.args:
                pname = _param_name(a)
                s = pname
                dft = py_default_for(f, a, 'python')
                has_default = dft is not None or bool(a.default)
                if dft is not None:
                    s += f'={dft}'
                elif a.default:
                    s += f'={python_default(a.type, a.default)}'
                sig_items.append((has_default, s, pname))
                if a.name == 'device':
                    rhs = pname if name.endswith('_like') else f'_ensure_device({pname})'
                    if a.kwonly:
                        call_args.append(f'{a.python_name}={rhs}')
                    else:
                        call_args.append(rhs)
                elif a.kwonly:
                    call_args.append(f'{a.python_name}={pname}')
                else:
                    call_args.append(pname)

            # A defaulted parameter cannot precede a plain one in a Python
            # signature; schema order sometimes violates that (mutable
            # trailing tensors), so plain params move forward -- stable, and
            # the extension call below keeps schema order.
            sig_items.sort(key=lambda item: item[0])
            arg_strs = [s for _, s, _ in sig_items]

            lines.append(f'def {name}({", ".join(arg_strs)}):')
            _capture_line(lines, name, [pn for _, _, pn in sig_items])

            for a in f.args:
                t, pname = a.type, _param_name(a)
                if t.kind == 'Scalar' and not t.is_opt:
                    lines.append(
                        f'    if not isinstance({pname}, (tensorplay.Scalar, tensorplay.Tensor)):')
                    lines.append(f'        {pname} = tensorplay.Scalar({pname})')
                elif t.kind == 'int64_t' and t.is_list:
                    # one-element list for `int[]` slots (`amax(x, dim=1)`);
                    # the generated FASTCALL binding only parses sequences.
                    lines.append(
                        f'    if isinstance({pname}, int) and not isinstance({pname}, bool):')
                    lines.append(f'        {pname} = [{pname}]')
                elif t.kind == 'Scalar' and t.is_opt:
                    lines.append(
                        f'    if {pname} is not None and not isinstance({pname}, (tensorplay.Scalar, tensorplay.Tensor)):')
                    lines.append(f'        {pname} = tensorplay.Scalar({pname})')
                elif t.kind == 'DType' and t.is_opt:
                    # Factory ops (no leading tensor receiver) resolve an
                    # explicit None through the C++ default-dtype
                    # substitution (DType.undefined); tensor-receiver ops
                    # keep std::optional semantics -- their kernels
                    # distinguish "absent" (keep input dtype) from
                    # "undefined" (global default).
                    if not (f.args and f.args[0].type.is_tensor_like):
                        lines.append(f'    if {pname} is None:')
                        lines.append(f'            {pname} = DType.undefined')
                elif t.is_tensor_like and not t.is_list and a.default == '{}':
                    lines.append(f'    if {pname} is None:')
                    lines.append(f'        {pname} = tensorplay.Tensor()')

            if multi_overload:
                # Positional forwarding: candidate selection happens in the
                # FASTCALL group dispatcher.
                # Keyword-only schema args never discriminate candidates and
                # the binding rejects them positionally, so keep them
                # keyword here too.
                pos = [_param_name(a) for a in f.args if not a.kwonly]
                kws = [f'{a.python_name}={_param_name(a)}'
                       for a in f.args if a.kwonly]
                lines.append(
                    f"    return _C.{name}({', '.join(pos + kws)})")
            else:
                lines.append(f'    return _C.{name}({", ".join(call_args)})')
            lines.append('')
            continue

        # ---- method-only wrappers ------------------------------------------
        if 'method' in f.variants:
            seen.add(name)
            args = f.args
            if not args or args[0].name != 'self':
                continue
            # Binary ops that accept a Scalar on the right also accept a plain
            # number on the LEFT (3 * t spelled out as multiply(3, t)); the
            # receiver is promoted so the method form can carry the call.
            scalar_rhs = not name.endswith('_') and any(
                len(g.args) >= 2 and g.args[0].type.is_tensor_like
                and not g.args[0].type.is_list and g.args[1].type.kind == 'Scalar'
                for g in group)
            arg_strs = ['input']
            call_args = []
            sig_items = []
            for a in args[1:]:
                pname = a.python_name
                s = pname
                dft = py_default_for(f, a, 'python')
                has_default = dft is not None or bool(a.default)
                if dft is not None:
                    s += f'={dft}'
                elif a.default:
                    s += f'={python_default(a.type, a.default)}'
                sig_items.append((has_default, s))
                call_args.append(f'{pname}={pname}')
            sig_items.sort(key=lambda item: item[0])
            arg_strs += [s for _, s in sig_items]
            lines.append(f'def {name}({", ".join(arg_strs)}):')
            if not name.endswith('_'):
                _capture_line(lines, name,
                              ['input'] + [a.python_name for a in args[1:]])
            if scalar_rhs:
                lines.append('    if not isinstance(input, tensorplay.Tensor):')
                lines.append('        input = tensorplay.as_tensor(input)')
            lines.append(f'    return input.{name}({", ".join(call_args)})')
            lines.append('')

    # Factory hot paths: hand the Python wrappers to the extension so the
    # public names rebind onto C trampolines -- eager calls skip the Python
    # frame entirely and vector straight into the generated METH_FASTCALL
    # entry, while Tracer captures divert back to these wrappers.  The guard
    # keeps the plain wrappers when running against an older extension.
    lines += [
        'try:',
        "    _C.install_factory_fast_paths(_C, {",
        "        'empty': empty, 'zeros': zeros, 'ones': ones,",
        "        'rand': rand, 'randn': randn, 'full': full,",
        '    })',
        '    # Adopt the C trampolines (installed as _C.<name>_fast) as the',
        '    # public factories: eager calls skip the Python frame; captures',
        '    # divert back to the wrapper objects handed over above.',
        '    empty = _C.empty_fast',
        '    zeros = _C.zeros_fast',
        '    ones = _C.ones_fast',
        '    rand = _C.rand_fast',
        '    randn = _C.randn_fast',
        '    full = _C.full_fast',
        'except (AttributeError, TypeError):',
        '    pass',
        '',
    ]
    return '\n'.join(lines) + '\n'
