"""Emit validated structured schema metadata."""

from __future__ import annotations

import json

from .main import CodegenContext, register_generator


def _records(functions):
    return tuple(getattr(functions, "reference_functions", functions))


def _name(function) -> str:
    return str(function.func.name)


def _kind(function) -> str:
    return function.func.kind().name


def validate_structured(functions) -> list[str]:
    """Return all invalid structured relationships in the schema."""
    records = _records(functions)
    by_name = {_name(function): function for function in records}
    problems: list[str] = []

    for function in records:
        delegate = function.structured_delegate
        if delegate is not None:
            delegate_name = str(delegate)
            target = by_name.get(delegate_name)
            if target is None:
                problems.append(
                    f"{_name(function)}: structured_delegate "
                    f"'{delegate_name}' is not present"
                )
                continue
            if not target.structured:
                problems.append(
                    f"{_name(function)}: delegate '{delegate_name}' "
                    "is not a structured out function"
                )
            if _kind(target) != "out":
                problems.append(
                    f"{_name(function)}: delegate '{delegate_name}' "
                    f"has schema kind {_kind(target)}, expected out"
                )
            if _kind(function) == "out":
                problems.append(
                    f"{_name(function)}: out functions cannot delegate"
                )
            if function.func.signature() != target.func.signature():
                problems.append(
                    f"{_name(function)}: delegate signature differs from "
                    f"'{delegate_name}'"
                )

        if function.structured and _kind(function) != "out":
            problems.append(
                f"{_name(function)}: structured is valid only on out functions"
            )
        if function.structured and function.structured_delegate is not None:
            problems.append(
                f"{_name(function)}: structured and structured_delegate "
                "cannot both be set"
            )

    return problems


def _structured_groups(ctx: CodegenContext):
    grouped = getattr(ctx.funcs, "grouped_native_functions", None)
    if grouped is None:
        return ()
    return tuple(group for group in grouped() if getattr(group, "structured", False))


def _cpp_string(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=True)


def _dispatch_entries(group) -> tuple[tuple[str, str], ...]:
    dispatch = getattr(group.out, "dispatch", {}) or {}
    return tuple(sorted((str(key), str(value))
                        for key, value in dispatch.items()
                        if str(key) != "__line__"))


def _inherits_name(group) -> str:
    value = getattr(group.out, "structured_inherits", None)
    if value is None:
        value = getattr(group.out, "structured_inherits_delegate", None)
    return "" if value is None else str(value)


def _render_header(groups) -> str:
    lines = [
        "// Generated by tools/codegen/gen_structured.py -- DO NOT EDIT.",
        "#pragma once",
        "#include <array>",
        "#include <cstddef>",
        "",
        "namespace tensorplay {",
        "namespace structured {",
        "",
        "struct DispatchEntry {",
        "    const char* key;",
        "    const char* kernel;",
        "};",
        "",
        "struct SchemaEntry {",
        "    const char* functional;",
        "    const char* out;",
        "    const char* inherits;",
        "    const DispatchEntry* dispatch;",
        "    std::size_t dispatch_count;",
        "};",
        "",
    ]

    dispatch_names: list[str] = []
    for index, group in enumerate(groups):
        name = f"kDispatch_{index}"
        dispatch_names.append(name)
        entries = _dispatch_entries(group)
        if not entries:
            lines.append(
                f"inline constexpr std::array<DispatchEntry, 0> {name}{{}};")
            continue
        lines.append(
            f"inline constexpr std::array<DispatchEntry, {len(entries)}> "
            f"{name} = {{ {{")
        for key, kernel in entries:
            lines.append(
                f"    {{ {_cpp_string(key)}, {_cpp_string(kernel)} }},")
        lines.append("} };")
        lines.append("")

    if not groups:
        lines.append(
            "inline constexpr std::array<SchemaEntry, 0> kSchemas{};")
    else:
        lines.append(
            f"inline constexpr std::array<SchemaEntry, {len(groups)}> "
            "kSchemas = { {")
        for index, group in enumerate(groups):
            lines.append(
                f"    {{ {_cpp_string(group.functional.func.name)}, "
                f"{_cpp_string(group.out.func.name)}, "
                f"{_cpp_string(_inherits_name(group))}, "
                f"{dispatch_names[index]}.data(), "
                f"{dispatch_names[index]}.size() }},")
        lines.append("} };")
    lines.extend([
        "",
        "inline constexpr std::size_t schema_count = kSchemas.size();",
        "",
        "constexpr bool same_name(const char* lhs, const char* rhs) noexcept {",
        "    if (lhs == nullptr || rhs == nullptr) return lhs == rhs;",
        "    while (*lhs != '\\0' && *lhs == *rhs) {",
        "        ++lhs;",
        "        ++rhs;",
        "    }",
        "    return *lhs == *rhs;",
        "}",
        "",
        "constexpr const SchemaEntry* find_schema(const char* name) noexcept {",
        "    for (const auto& schema : kSchemas) {",
        "        if (same_name(schema.functional, name) ||",
        "            same_name(schema.out, name)) return &schema;",
        "    }",
        "    return nullptr;",
        "}",
        "",
        "} // namespace structured",
        "} // namespace tensorplay",
        "",
    ])
    return "\n".join(lines)


@register_generator("Structured")
def _gen_structured(ctx: CodegenContext) -> None:
    problems = validate_structured(ctx.funcs)
    if problems:
        raise ValueError(
            "structured schema validation failed:\n  "
            + "\n  ".join(problems)
        )

    groups = _structured_groups(ctx)
    ctx.write("StructuredGenerated.h", _render_header(groups))
