"""Generators for TPXOpsGenerated.h/.cpp -- the Autograd-key kernels.

Every operator exposes a free function ``tensorplay::tpx::ops::<name>`` that
routes through the Autocast key first, applies mutation under GradMode,
invokes the backend through ``detail::redispatch_*``, builds the backward node
with its saved variables, and attaches history to the outputs.
"""

from __future__ import annotations

from .api_types import (
    call_arg_expr,
    cpp_arg_type,
    cpp_default,
    cpp_return_type,
    stub_arg_type_for,
    tuple_element_cpp_types,
    tuple_element_names,
)
from .gen_autograd import OpDerivatives
from .model import NativeFunction, redispatch_name as _redispatch_name

_H = [
    '// Generated by tools/codegen/main.py -- DO NOT EDIT',
    '#pragma once',
    '#include "Autograd.h"',
    '#include "tensorplay/ops/TensorRedispatchGenerated.h"',
    '#include <tuple>',
    '',
]


# Value: backward node, forward operation name, and whether mutation of a
# multi-output view is forbidden.
_LIST_VIEW_OPS = {
    'unbind': ('UnbindBackward', 'Unbind', True),
    'split': ('SplitBackward', 'Split', True),
    'split_with_sizes': ('SplitBackward', 'SplitWithSizes', True),
    'chunk': ('SplitBackward', 'Split', True),
    'tensor_split': ('SplitBackward', 'TensorSplit', False),
}

def _dedup_key(f: NativeFunction) -> str:
    return f.cpp_name + ':' + ','.join(cpp_arg_type(a.type) for a in f.args)


def _signature_args(f: NativeFunction) -> str:
    args = []
    for a in f.args:
        s = f'{cpp_arg_type(a.type)} {a.name}'
        if not f.is_out and a.default and a.name not in f.cpp_no_default_args:
            s += f' = {cpp_default(a.type, a.default)}'
        args.append(s)
    return ", ".join(args)


def _core_call_expr(f: NativeFunction) -> str:
    rd = _redispatch_name(f, f.variants[0])
    core_args = [call_arg_expr(f.base_name, a)
                 for a in f.args if a.name != 'requires_grad']
    if f.manual_kernel_registration:
        if f.self_arg() is not None and 'method' in f.variants:
            self_arg = f.self_arg()
            rest = [a.name for a in f.args
                    if a.name != self_arg.name and a.name != 'requires_grad']
            return f'{self_arg.name}.{f.cpp_name}({", ".join(rest)})'
        return f'Tensor::{f.cpp_name}({", ".join(core_args)})'
    return f'::tensorplay::detail::{rd}({", ".join(core_args)})'


def _inline_forward_lines(f: NativeFunction, autocast_ops: set[str],
                          derivatives: dict[str, OpDerivatives]
                          ) -> list[str] | None:
    """Body lines for wrappers that carry no eager-path work of their own.

    An operator whose generated wrapper would only forward to the redispatch
    helper (no gradient bookkeeping, no autocast rule, no factory default
    resolution, no view version-counter sharing, no requires_grad flag
    plumbing) is emitted as an inline header definition instead of an
    out-of-line one: call sites bind the body directly and skip one
    out-of-line call per invocation.  Returns None when the wrapper must
    stay out-of-line because it does real work around the core call.
    """
    if _has_autograd(f, derivatives):
        return None
    _self_lv = f.self_arg()
    if (f.cpp_return_kind == 'list' and _self_lv is not None
            and f.returns_view_of_input
            and any(a.name == 'dim' for a in f.args)):
        return None                                # multi-output view rule
    if f.func_name in autocast_ops:
        return None
    if not (f.args and f.args[0].type.is_tensor_like):
        for a in f.args:                           # factory default fill-in
            at = cpp_arg_type(a.type)
            if a.name == 'device' and at == 'std::optional<Device>':
                return None
            if (a.name == 'dtype' and f.base_name in _DTYPE_GLOBAL_DEFAULT_OPS
                    and at in ('DType', 'std::optional<DType>')):
                return None
    _self = f.self_arg()
    _is_inplace = (f.base_name.endswith('_') and _self is not None
                   and _self.name != 'requires_grad')
    if (not _is_inplace and _self is not None
            and f.returns_view_of_input and f.cpp_return_kind == 'value'):
        return None                                # view version sharing
    if f.cpp_return_kind == 'value' and any(
            a.name == 'requires_grad' for a in f.args):
        return None
    core_call = _core_call_expr(f)
    kind = f.cpp_return_kind
    if kind in ('value', 'tuple', 'list'):
        return [f'    return {core_call};']
    if kind == 'void':
        return [f'    {core_call};']
    if kind == 'mut_ref':
        alias = next((a.name for a in f.mutable_args if a.type.is_mutable_ref),
                     f.args[0].name)
        return [f'    {core_call};', f'    return {alias};']
    return None


def generate_tpx_ops_h(funcs: list[NativeFunction], *,
                       autocast_ops: set[str],
                       derivatives: dict[str, OpDerivatives]) -> str:
    lines = list(_H)
    lines += ['namespace tensorplay {', 'namespace tpx {', 'namespace ops {', '']
    seen: set[str] = set()
    for f in funcs:
        key = _dedup_key(f)
        if key in seen:
            continue
        seen.add(key)
        ret = cpp_return_type(f)
        inline = _inline_forward_lines(f, autocast_ops, derivatives)
        if inline is not None:
            lines.append(f'inline {ret} {f.cpp_name}({_signature_args(f)}) {{')
            lines.extend(inline)
            lines.append('}')
        else:
            lines.append(f'TENSORPLAY_API {ret} {f.cpp_name}({_signature_args(f)});')
        lines.append('')
    lines += ['} // namespace ops', '} // namespace tpx', '} // namespace tensorplay']
    return '\n'.join(lines)


_CPP_INCLUDES = """// Generated by tools/codegen/main.py -- DO NOT EDIT
#include "Autograd.h"
#include "tensorplay/ops/AutogradNodesGenerated.h"
#include "Node.h"
#include "tensorplay/ops/TPXOpsGenerated.h"
#include "tensorplay/ops/TensorRedispatchGenerated.h"
#include "Dispatcher.h"
#include "DispatchKey.h"
#include "InferenceMode.h"
#include "Context.h"
#include "autocast_mode.h"
#include <algorithm>
"""


def _device_source_expr(f: NativeFunction) -> str | None:
    cpu = 'Device(DeviceType::CPU)'
    for a in f.args:
        if a.type.is_tensor_like and not a.type.is_list and not a.type.is_opt:
            return f'{a.name}.device()'
    for a in f.args:
        if a.type.is_tensor_like and a.type.is_list:
            return f'deviceForTensorArg({a.name})'
    return None


def _emit_autocast_block(lines, f, arg_types):
    dev_src = _device_source_expr(f)
    if dev_src is None:
        return
    tmpl = ', '.join([cpp_return_type(f)] + arg_types)
    call_args = ', '.join(a.name for a in f.args)
    ac_call = f'DispatchStub<{tmpl}>::call(__ac_handle, __ac_key, {call_args})'
    ret_void = cpp_return_type(f) == 'void'
    lines.append('    {')
    lines.append(
        '        static const OperatorHandle __ac_handle = '
        f'Dispatcher::singleton().findHandle("{f.func_name}");')
    lines.append(
        f'        DispatchKey __ac_key = toAutocastKey(computeDispatchKey({dev_src}));')
    lines.append(
        '        if (__ac_handle && __ac_handle.getKernel(__ac_key) && '
        '::tensorplay::autocast::is_enabled(__ac_key)) {')
    if ret_void:
        lines.append(f'            {ac_call};')
        lines.append('            return;')
    else:
        lines.append(f'            return {ac_call};')
    lines.append('        }')
    lines.append('    }')


def _node_ctor_args(dv: OpDerivatives, f: NativeFunction,
                    core_result_var: str | None) -> list[str]:
    """Ordered constructor arguments for the backward node."""
    arg_names = {a.name for a in f.args}
    # Manual nodes (empty formulas, hand-written structs) are not extended.
    args: list[str] = []
    out_index = {n: i for i, n in enumerate(tuple_element_names(f))}
    for m, _t in dv.members:
        if m in dv.used_input_names:
            if (m == 'self' and f.func_name.endswith('_')
                    and any(a.name == 'self' for a in f.args)):
                # Pre-mutation capture is hoisted by the wrapper; the live
                # `self` already holds the update.
                args.append('__tp_original_self.value()')
            else:
                args.append(m)
        elif m == 'result':
            expr = 'result'
            if dv.node_name == 'ReluBackward':
                expr += '.detach()'
            args.append(expr)
        elif m in out_index:
            expr = f'std::get<{out_index[m]}>({core_result_var or "core_result"})'
            if dv.node_name == 'ReluBackward':
                expr += '.detach()'
            args.append(expr)
        else:
            args.append(m)
    return args


def _has_autograd(f: NativeFunction, derivatives: dict[str, OpDerivatives]) -> bool:
    return f.func_name in derivatives or f.func_name == 'relu_'


def _emit_requires_grad_detection(lines, f):
    checks = []
    for a in f.args:
        t = a.type
        if t.is_tensor_like and not t.is_list and not t.is_opt:
            checks.append(f'{a.name}.requires_grad()')
        elif t.is_tensor_like and t.is_list:
            if t.list_elem_opt:
                checks.append(
                    f'std::any_of({a.name}.begin(), {a.name}.end(), '
                    '[](const std::optional<Tensor>& tensor) {'
                    ' return tensor.has_value() && tensor->requires_grad(); })')
            else:
                checks.append(
                    f'std::any_of({a.name}.begin(), {a.name}.end(), '
                    '[](const Tensor& tensor) { return tensor.requires_grad(); })')
        elif t.is_tensor_like and t.is_opt:
            checks.append(f'({a.name}.has_value() && {a.name}->requires_grad())')
    lines.append('    bool requires_grad = false;')
    if checks:
        cond = ' || '.join(checks)
        lines.append(
            '    if (GradMode::is_enabled() && !InferenceMode::is_enabled() '
            f'&& ({cond})) requires_grad = true;')


def _emit_leaf_checks(lines, f):
    for a in f.mutable_args:
        if a.type.is_mutable_ref:
            lines.append(f'    if (requires_grad && {a.name}.requires_grad()) {{')
            # views created by multi-output nodes (CreationMeta::
            # MULTI_OUTPUT_NODE) can never be mutated in-place; this fires
            # before the view-of-leaf / leaf checks.
            lines.append('        {')
            lines.append(
                f'            auto __tp_gf = tensorplay::tpx::impl::grad_fn({a.name});')
            lines.append(
                f'            if (__tp_gf && {a.name}.unsafeGetTensorImpl()->is_view() '
                '&& __tp_gf->is_multi_output_view()) {')
            lines.append(
                '                TP_THROW(RuntimeError, "Output ", '
                f'tensorplay::tpx::impl::output_nr({a.name}), " of ", '
                '__tp_gf->forward_op_name(), '
                '" is a view and is being modified inplace." '
                '" This view is the output of a function that returns multiple views." '
                '" Such functions do not allow the output views to be modified inplace." '
                '" You should replace the inplace operation by an out-of-place one.");')
            lines.append('            }')
            lines.append('        }')
            lines.append(
                f'        if (tensorplay::tpx::impl::is_view_of_leaf({a.name})) {{')
            lines.append(
                '            TP_THROW(RuntimeError, "a view of a leaf Variable '
                'that requires grad is being used in an in-place operation.");')
            lines.append('        }')
            lines.append(
                f'        if (tensorplay::tpx::impl::is_leaf({a.name})) {{')
            lines.append(
                '            TP_THROW(RuntimeError, "a leaf Variable that requires grad '
                'is being used in an in-place operation");')
            lines.append('        }')
            lines.append('    }')


def _emit_edges(lines, f):
    list_args = [a.name for a in f.args if a.type.is_tensor_like and a.type.is_list]
    tensor_args = [a.name for a in f.args if a.type.is_tensor_like]
    if list_args:
        lines.append('        std::vector<Edge> autograd_edges;')
        for a in f.args:
            t = a.type
            if t.is_tensor_like and t.is_list:
                lines.append(f'        for (const auto& tensor : {a.name}) {{')
                if t.list_elem_opt:
                    lines.append('            if (tensor.has_value()) collect_next_edges_helper(autograd_edges, *tensor);')
                else:
                    lines.append('            collect_next_edges_helper(autograd_edges, tensor);')
                lines.append('        }')
            elif t.is_tensor_like:
                if t.is_opt:
                    lines.append(f'        if ({a.name}.has_value()) collect_next_edges_helper(autograd_edges, *{a.name});')
                else:
                    lines.append(f'        collect_next_edges_helper(autograd_edges, {a.name});')
        lines.append('        grad_fn->add_next_edge_list(std::move(autograd_edges));')
    else:
        lines.append(
            f'        grad_fn->add_next_edge_list(collect_next_edges({", ".join(tensor_args)}));')


def _view_replay_lambda(f: NativeFunction) -> str:
    view_input = f.view_input_name or "self"
    call_args = []
    for arg in f.args:
        if arg.name == view_input:
            call_args.append("__tp_view_base")
        elif arg.name != "requires_grad":
            call_args.append(arg.name)
    return (
        "[=](const Tensor& __tp_view_base) { return "
        f"tensorplay::tpx::ops::{f.cpp_name}({', '.join(call_args)}); }}"
    )


# arange/linspace/logspace infer from their scalar inputs; full infers from
# fill_value; randint/randperm/eye keep concrete integral/float defaults.
_DTYPE_GLOBAL_DEFAULT_OPS = {"rand", "randn", "empty", "zeros", "ones"}


def generate_tpx_ops_cpp(funcs: list[NativeFunction], *,
                         autocast_ops: set[str],
                         derivatives: dict[str, OpDerivatives]) -> str:
    lines = [_CPP_INCLUDES.rstrip('\n'), '',
             'namespace tensorplay {', 'namespace tpx {', 'namespace ops {', '']

    seen: set[str] = set()
    for f in funcs:
        key = _dedup_key(f)
        if key in seen:
            continue
        seen.add(key)

        if _inline_forward_lines(f, autocast_ops, derivatives) is not None:
            # Defined inline in TPXOpsGenerated.h; no out-of-line body.
            continue

        arg_types = [cpp_arg_type(a.type) for a in f.args]
        ret = cpp_return_type(f)
        ret_void = ret == 'void'
        has_ag = _has_autograd(f, derivatives)
        _self_lv = f.self_arg()
        _is_list_view = (f.cpp_return_kind == 'list' and _self_lv is not None
                         and f.returns_view_of_input
                         and any(a.name == 'dim' for a in f.args))
        if _is_list_view and f.base_name not in _LIST_VIEW_OPS:
            raise ValueError(
                f"list view operator {f.func_name} has no autograd view rule"
            )

        lines.append(f'{ret} {f.cpp_name}({", ".join(f"{t} {a.name}" for t, a in zip(arg_types, f.args))}) {{')

        # ---- factory global-default resolution ------------------------------
        # Factory-style ops (no leading tensor receiver) honor the global
        # default dtype/device when the caller leaves them unset, like
        # TensorOptions fallthrough.  arange-family dtypes are
        # excluded: their kernels infer from the scalar inputs instead.
        if not (f.args and f.args[0].type.is_tensor_like):
            for a in f.args:
                at = cpp_arg_type(a.type)
                if a.name == 'device' and at == 'std::optional<Device>':
                    lines.append(
                        '    if (!device.has_value()) '
                        'device = globalContext().defaultDevice();')
                elif (a.name == 'dtype' and f.base_name in _DTYPE_GLOBAL_DEFAULT_OPS
                      and at in ('DType', 'std::optional<DType>')):
                    if at == 'std::optional<DType>':
                        lines.append(
                            '    if (!dtype.has_value() || *dtype == DType::Undefined) '
                            'dtype = globalContext().defaultDType();')
                    else:
                        lines.append(
                            '    if (dtype == DType::Undefined) '
                            'dtype = globalContext().defaultDType();')

        if f.func_name in autocast_ops:
            _emit_autocast_block(lines, f, arg_types)

        # ---- gradient bookkeeping -----------------------------------------
        if has_ag or _is_list_view:
            _emit_requires_grad_detection(lines, f)
            _emit_leaf_checks(lines, f)
            # In-place ops whose derivative references `self` must evaluate
            # the slope at the PRE-mutation value.  Capture the
            # clone before the core call; _node_ctor_args splices it in.
            _dv_pre = derivatives.get(f.func_name)
            if (_dv_pre is not None and _dv_pre.formulas
                    and f.base_name.endswith('_')
                    and f.func_name.endswith('_')
                    and 'self' in _dv_pre.used_input_names
                    and any(a.name == 'self' for a in f.args)):
                lines.append('    std::optional<Tensor> __tp_original_self;')
                lines.append('    if (requires_grad) {')
                lines.append('        const bool __tp_prev_gm = GradMode::is_enabled();')
                lines.append('        GradMode::set_enabled(false);')
                lines.append('        __tp_original_self = self.clone();')
                lines.append('        GradMode::set_enabled(__tp_prev_gm);')
                lines.append('    }')

        # ---- core invocation ----------------------------------------------
        core_call = _core_call_expr(f)

        kind = f.cpp_return_kind
        if kind in ('tuple', 'list'):
            lines.append(f'    auto core_result = {core_call};')
        elif kind == 'value':
            ret_type = cpp_return_type(f)
            if ret_type == 'Tensor':
                lines.append(f'    Tensor result = {core_call};')
            else:
                lines.append(f'    {ret_type} result = {core_call};')
        elif kind in ('mut_ref', 'void'):
            lines.append(f'    {core_call};')

        # ---- InplaceOrView semantics ---------------------------------------
        # InplaceOrView semantics: in-place ops bump their version counter
        # after mutation; view ops share the
        # base's counter so writes through the view are tracked.
        _self = f.self_arg()
        _is_inplace = (f.base_name.endswith('_') and _self is not None
                       and _self.name != 'requires_grad')
        _is_view = (not _is_inplace and _self is not None
                    and f.returns_view_of_input and kind == 'value')
        if _is_inplace:
            # Version bumping is owned exclusively by the below-autograd
            # redispatch layer (gen_api.py emits it inside
            # detail::redispatch_*); the InplaceOrView layer sits below the
            # autograd wrapper; bumping here again would
            # double-count under the default autograd path.
            pass
        elif _is_view:
            lines.append(
                f'    if (result.unsafeGetTensorImpl()->storage().is_same('
                f'{_self.name}.unsafeGetTensorImpl()->storage())) {{')
            lines.append(
                f'        result.unsafeGetTensorImpl()->share_version_counter('
                f'*{_self.name}.unsafeGetTensorImpl());')
            lines.append(
                '        result.unsafeGetTensorImpl()->set_is_view(true);')
            if has_ag:
                replay = _view_replay_lambda(f)
                metadata_change = 'true' if f.view_metadata_changes else 'false'
                lines.append('        if (requires_grad) {')
                lines.append(
                    '            tensorplay::tpx::impl::set_view_metadata('
                    f'result, {_self.name}, tensorplay::tpx::CreationMeta::DEFAULT, '
                    f'{replay}, {metadata_change});')
                lines.append('        }')
            lines.append('    }')

        # ---- backward node --------------------------------------------------
        dv_nd = derivatives.get(f.func_name)
        _non_diff = dv_nd is not None and dv_nd.non_differentiable_output
        if has_ag and not _non_diff:
            lines.append('    std::shared_ptr<Node> grad_fn;')
            lines.append('    if (requires_grad) {')
            if f.func_name == 'relu_':
                # In-place ReLU aliases its input; save a detached handle of
                # the mutated tensor as the mask without forming a cycle.
                lines.append(
                    f'        grad_fn = std::make_shared<ReluBackward>({f.args[0].name}.detach());')
            else:
                dv = derivatives[f.func_name]
                ctor_args = _node_ctor_args(dv, f, 'core_result')
                lines.append(
                    f'        grad_fn = std::make_shared<{dv.node_name}>({", ".join(ctor_args)});')
            if f.returns_view_of_input and _self is not None and kind == 'value':
                lines.append(
                    f'        grad_fn->set_view_fn(result.unsafeGetTensorImpl()->'
                    f'storage().is_same({_self.name}.unsafeGetTensorImpl()->storage()));')
            _emit_edges(lines, f)
            lines.append('    }')
        elif _is_list_view:
            # Multi-output view op: one shared node and one output slot per
            # returned alias.
            node_name, fwd_name, multi_out = _LIST_VIEW_OPS[f.base_name]
            if f.func_name == 'split.sizes':
                fwd_name = 'SplitWithSizes'
            lines.append('    std::shared_ptr<Node> grad_fn;')
            lines.append('    if (requires_grad) {')
            lines.append(
                f'        grad_fn = std::make_shared<{node_name}>(dim, core_result);')
            lines.append('        grad_fn->set_view_fn(true);')
            lines.append(f'        grad_fn->set_forward_op_name("{fwd_name}");')
            if multi_out:
                lines.append('        grad_fn->set_multi_output_view(true);')
            _emit_edges(lines, f)
            lines.append('    }')

        # ---- result wrapping -----------------------------------------------
        if kind == 'tuple':
            tup_types = tuple_element_cpp_types(f)
            result_var = '__tp_wrapped_result'
            lines.append(f'    std::tuple<{", ".join(tup_types)}> {result_var};')
            for i, tt in enumerate(tup_types):
                lines.append(f'    std::get<{i}>({result_var}) = std::get<{i}>(core_result);')
                if tt == 'Tensor' and has_ag and not _non_diff:
                    lines.append(
                        f'    if (requires_grad && std::get<{i}>({result_var}).defined() '
                        f'&& tensorplay::isFloatingOrComplexType(std::get<{i}>({result_var}).dtype())) {{')
                    lines.append(
                        f'        tensorplay::tpx::impl::set_grad_fn(std::get<{i}>({result_var}), grad_fn, {i});')
                    lines.append('    }')
            lines.append(f'    return {result_var};')
        elif kind == 'value':
            if any(a.name == 'requires_grad' for a in f.args):
                lines.append('    tensorplay::tpx::impl::set_requires_grad(result, requires_grad);')
            if has_ag and not _non_diff:
                lines.append('    if (requires_grad) tensorplay::tpx::impl::set_requires_grad(result, true);')
                lines.append('    if (requires_grad && result.defined()) {')
                lines.append('        tensorplay::tpx::impl::set_grad_fn(result, grad_fn);')
                lines.append('    }')
            lines.append('    return result;')
        elif kind == 'list':
            if _is_list_view:
                # `self` -- share the version counter, mark is_view, and
                # attach the shared backward node with a per-element
                # output_nr for unbind/split views.
                lines.append('    for (size_t __tp_i = 0; __tp_i < core_result.size(); ++__tp_i) {')
                lines.append(
                    f'        core_result[__tp_i].unsafeGetTensorImpl()->share_version_counter('
                    f'*{_self_lv.name}.unsafeGetTensorImpl());')
                lines.append(
                    '        core_result[__tp_i].unsafeGetTensorImpl()->set_is_view(true);')
                lines.append('        if (requires_grad) {')
                lines.append(
                    '            tensorplay::tpx::impl::set_view_metadata('
                    f'core_result[__tp_i], {_self_lv.name}, '
                    'tensorplay::tpx::CreationMeta::MULTI_OUTPUT_NODE);')
                lines.append(
                    '            tensorplay::tpx::impl::set_requires_grad(core_result[__tp_i], true);')
                lines.append(
                    '            tensorplay::tpx::impl::set_grad_fn(core_result[__tp_i], grad_fn, '
                    'static_cast<uint32_t>(__tp_i));')
                lines.append('        }')
                lines.append('    }')
            lines.append('    return core_result;')
        elif kind == 'mut_ref':
            alias = next((a.name for a in f.mutable_args if a.type.is_mutable_ref),
                         f.args[0].name)
            if has_ag:
                lines.append(f'    if (requires_grad) tensorplay::tpx::impl::set_requires_grad({alias}, true);')
                lines.append(f'    if (requires_grad && {alias}.defined()) {{')
                lines.append(
                    f'        if (tensorplay::tpx::impl::has_view_metadata({alias})) {{')
                lines.append(
                    f'            tensorplay::tpx::impl::rebase_history({alias}, grad_fn);')
                lines.append('        } else {')
                lines.append(f'            tensorplay::tpx::impl::set_grad_fn({alias}, grad_fn);')
                lines.append('        }')
                lines.append('    }')
            lines.append(f'    return {alias};')
        elif kind == 'void':
            lines.append('    return;')
        else:
            lines.append(f'    return {core_call};')
        lines.append('}')
        lines.append('')

    lines += ['} // namespace ops', '} // namespace tpx', '} // namespace tensorplay']
    return '\n'.join(lines)


def get_tpx_ops_signature(f: NativeFunction) -> str:
    return (f'{cpp_return_type(f)} (*)({", ".join(cpp_arg_type(a.type) for a in f.args)})')


def generate_autograd_registration(funcs: list[NativeFunction], *,
                                   derivatives: dict[str, OpDerivatives]) -> str:
    """Registers each generated wrapper as the AutogradCPU/CUDA kernel --
    TensorPlay's RegisterAutogradCPU.cpp / RegisterAutogradCUDA.cpp."""
    lines = [
        '// Generated by tools/codegen/main.py -- DO NOT EDIT',
        '#include "Dispatcher.h"',
        '#include "DispatchKey.h"',
        '#include "tensorplay/ops/TPXOpsGenerated.h"',
        '',
        'namespace tensorplay {',
        'namespace {',
        '',
        'struct RegisterTPXAutogradKernels {',
        '    RegisterTPXAutogradKernels() {',
        '        auto& D = Dispatcher::singleton();',
    ]
    seen: set[str] = set()
    for f in funcs:
        if not _has_autograd(f, derivatives):
            continue
        if _dedup_key(f) in seen:
            continue
        seen.add(_dedup_key(f))
        fn_type = (f'{cpp_return_type(f)} (*)({", ".join(cpp_arg_type(a.type) for a in f.args)})')
        cast = f'static_cast<{fn_type}>(&::tensorplay::tpx::ops::{f.cpp_name})'
        for key in ('AutogradCPU', 'AutogradCUDA', 'AutogradVulkan'):
            lines.append(f'        D.registerKernel("{f.func_name}", DispatchKey::{key}, (KernelFunction){cast});')
    lines += [
        '    }',
        '};',
        '',
        'static RegisterTPXAutogradKernels g_register_tpx_autograd_kernels;',
        '',
        '} // namespace',
        '} // namespace tensorplay',
    ]
    return '\n'.join(lines)
