"""Generators for TPXOpsGenerated.h/.cpp -- the Autograd-key kernels.

Every operator exposes a free function ``tensorplay::tpx::ops::<name>`` that
routes through the Autocast key first, applies mutation under GradMode,
invokes the backend through ``detail::redispatch_*``, builds the backward node
with its saved variables, and attaches history to the outputs.
"""

from __future__ import annotations

import dataclasses

from .api_types import (
    call_arg_expr,
    cpp_arg_type,
    cpp_default,
    cpp_return_type,
    rewrap_arg_expr,
    stub_arg_type_for,
    tuple_element_cpp_types,
    tuple_element_names,
)
from .gen_autograd import OpDerivatives, render_formula
from .model import NativeFunction, redispatch_name as _redispatch_name

_H = [
    '// Generated by tools/codegen/main.py -- DO NOT EDIT',
    '#pragma once',
    '#include "Autograd.h"',
    '#include "tensorplay/ops/TensorRedispatchGenerated.h"',
    '#include <tuple>',
    '',
]


# Value: backward node, forward operation name, and whether mutation of a
# multi-output view is forbidden.
_LIST_VIEW_OPS = {
    'unbind': ('UnbindBackward', 'Unbind', True),
    'split': ('SplitBackward', 'Split', True),
    'split_with_sizes': ('SplitBackward', 'SplitWithSizes', True),
    'chunk': ('SplitBackward', 'Split', True),
    'tensor_split': ('SplitBackward', 'TensorSplit', False),
}

_COMPOSITE_AUTOGRAD_WRAPPERS = frozenset({'dropout'})

# Operators without a derivative whose generated wrapper is still registered
# as their autograd kernel.  ``detach`` is one: its backend-neutral kernel
# copies the tensor's metadata and dispatches nothing, so a tensor that
# requires grad has to reach it through a kernel that redispatches --
# otherwise a dispatch mode never sees the call and a trace takes the result
# for a constant.
_REDISPATCHING_AUTOGRAD_KERNELS = frozenset({'detach'})

def _dedup_key(f: NativeFunction) -> str:
    return f.cpp_name + ':' + ','.join(cpp_arg_type(a.type) for a in f.args)


def _signature_args(f: NativeFunction) -> str:
    args = []
    for a in f.args:
        s = f'{cpp_arg_type(a.type)} {a.name}'
        if not f.is_out and a.default and a.name not in f.cpp_no_default_args:
            s += f' = {cpp_default(a.type, a.default)}'
        args.append(s)
    return ", ".join(args)


def _declared_call_args(f: NativeFunction, self_name: str | None) -> list[str]:
    """The arguments a call is made with, in order.

    ``requires_grad`` is normally not one of them: a schema that returns a
    differentiable tensor carries it as a note on the result rather than as
    something the caller passes.  An operation named for that flag does take
    it, though, and dropping it there would call it with nothing.
    """

    if f.cpp_name == 'requires_grad_':
        return [a.name for a in f.args if a.name != self_name]
    return [a.name for a in f.args if a.name != self_name and a.name != 'requires_grad']


def _core_call_expr(f: NativeFunction) -> str:
    rd = _redispatch_name(f, f.variants[0])
    core_args = [call_arg_expr(f.base_name, a)
                 for a in f.args if a.name != 'requires_grad']
    if f.manual_kernel_registration:
        if f.self_arg() is not None and 'method' in f.variants:
            self_arg = f.self_arg()
            rest = _declared_call_args(f, self_arg.name)
            return f'{self_arg.name}.{f.cpp_name}({", ".join(rest)})'
        return f'Tensor::{f.cpp_name}({", ".join(core_args)})'
    return f'::tensorplay::detail::{rd}({", ".join(core_args)})'


def _inline_forward_lines(f: NativeFunction, autocast_ops: set[str],
                          derivatives: dict[str, OpDerivatives]
                          ) -> list[str] | None:
    """Body lines for wrappers that carry no eager-path work of their own.

    An operator whose generated wrapper would only forward to the redispatch
    helper (no gradient bookkeeping, no autocast rule, no factory default
    resolution, no view version-counter sharing, no requires_grad flag
    plumbing) is emitted as an inline header definition instead of an
    out-of-line one: call sites bind the body directly and skip one
    out-of-line call per invocation.  Returns None when the wrapper must
    stay out-of-line because it does real work around the core call.
    """
    if _has_autograd(f, derivatives):
        return None
    if f.is_out and any(a.type.is_tensor_like and a.type.mutability is None for a in f.args):
        return None                       # refuses a tangent it cannot carry
    _dv_inline = derivatives.get(f.func_name)
    if _dv_inline is not None and _dv_inline.fw_formulas:
        return None                       # forward-AD block needs the body
    _self_lv = f.self_arg()
    if (f.cpp_return_kind == 'list' and _self_lv is not None
            and f.returns_view_of_input
            and any(a.name == 'dim' for a in f.args)):
        return None                                # multi-output view rule
    if f.func_name in autocast_ops:
        return None
    if not (f.args and f.args[0].type.is_tensor_like):
        for a in f.args:                           # factory default fill-in
            at = cpp_arg_type(a.type)
            if a.name == 'device' and at == 'std::optional<Device>':
                return None
            if (a.name == 'dtype' and f.base_name in _DTYPE_GLOBAL_DEFAULT_OPS
                    and at in ('DType', 'std::optional<DType>')):
                return None
    _self = f.self_arg()
    _is_inplace = (f.base_name.endswith('_') and _self is not None
                   and _self.name != 'requires_grad')
    if (not _is_inplace and _self is not None
            and f.returns_view_of_input and f.cpp_return_kind == 'value'):
        return None                                # view version sharing
    if f.cpp_return_kind == 'value' and any(
            a.name == 'requires_grad' for a in f.args):
        return None
    core_call = _core_call_expr(f)
    kind = f.cpp_return_kind
    if kind in ('value', 'tuple', 'list'):
        return [f'    return {core_call};']
    if kind == 'void':
        return [f'    {core_call};']
    if kind == 'mut_ref':
        alias = next((a.name for a in f.mutable_args if a.type.is_mutable_ref),
                     f.args[0].name)
        return [f'    {core_call};', f'    return {alias};']
    return None


def generate_tpx_ops_h(funcs: list[NativeFunction], *,
                       autocast_ops: set[str],
                       derivatives: dict[str, OpDerivatives]) -> str:
    lines = list(_H)
    lines += ['namespace tensorplay {', 'namespace tpx {', 'namespace ops {', '']
    seen: set[str] = set()
    for f in funcs:
        key = _dedup_key(f)
        if key in seen:
            continue
        seen.add(key)
        ret = cpp_return_type(f)
        inline = _inline_forward_lines(f, autocast_ops, derivatives)
        if inline is not None:
            lines.append(f'inline {ret} {f.cpp_name}({_signature_args(f)}) {{')
            lines.extend(inline)
            lines.append('}')
        else:
            lines.append(f'TENSORPLAY_API {ret} {f.cpp_name}({_signature_args(f)});')
        lines.append('')
    lines += ['} // namespace ops', '} // namespace tpx', '} // namespace tensorplay']
    return '\n'.join(lines)


_CPP_INCLUDES = """// Generated by tools/codegen/main.py -- DO NOT EDIT
#include "Autograd.h"
#include "ForwardFallback.h"
#include "tensorplay/ops/AutogradNodesGenerated.h"
#include "Node.h"
#include "tensorplay/ops/TPXOpsGenerated.h"
#include "tensorplay/ops/TensorRedispatchGenerated.h"
#include "Dispatcher.h"
#include "DispatchKey.h"
#include "InferenceMode.h"
#include "Context.h"
#include "autocast_mode.h"
#include <algorithm>
"""


def _device_source_expr(f: NativeFunction) -> str | None:
    cpu = 'Device(DeviceType::CPU)'
    for a in f.args:
        if a.type.is_tensor_like and not a.type.is_list and not a.type.is_opt:
            return f'{a.name}.device()'
    for a in f.args:
        if a.type.is_tensor_like and a.type.is_list:
            return f'deviceForTensorArg({a.name})'
    return None


def _emit_autocast_block(lines, f, arg_types):
    dev_src = _device_source_expr(f)
    if dev_src is None:
        return
    tmpl = ', '.join([cpp_return_type(f)] + arg_types)
    call_args = ', '.join(a.name for a in f.args)
    ac_call = f'DispatchStub<{tmpl}>::call(__ac_handle, __ac_key, {call_args})'
    ret_void = cpp_return_type(f) == 'void'
    lines.append('    {')
    lines.append(
        '        static const OperatorHandle __ac_handle = '
        f'Dispatcher::singleton().findHandle("{f.func_name}");')
    lines.append(
        f'        DispatchKey __ac_key = toAutocastKey(computeDispatchKey({dev_src}));')
    lines.append(
        '        if (__ac_handle && __ac_handle.getKernel(__ac_key) && '
        '::tensorplay::autocast::dispatch_enabled(__ac_key)) {')
    if ret_void:
        lines.append(f'            {ac_call};')
        lines.append('            return;')
    else:
        lines.append(f'            return {ac_call};')
    lines.append('        }')
    lines.append('    }')


def _records_inplace_update(f: NativeFunction,
                            derivatives: dict[str, OpDerivatives]) -> bool:
    """An in-place op whose wrapper attaches a backward node to the updated
    tensor.  What the node learns about that tensor's inputs (its edges and
    the attributes the formulas measure) is taken before the update, which
    may change the tensor's shape."""
    dv = derivatives.get(f.func_name)
    return (f.cpp_return_kind == 'mut_ref' and f.base_name.endswith('_')
            and any(a.name == 'self' for a in f.args)
            and (f.func_name == 'relu_'
                 or (dv is not None and not dv.non_differentiable_output)))


def _hoisted_attributes(dv: OpDerivatives, f: NativeFunction) -> list[tuple[str, str, str, str]]:
    """(member, type, argument, attribute) for the attributes of a mutated
    argument the formulas measure; read before the update."""
    mutated = {a.name for a in f.mutable_args if a.type.is_mutable_ref}
    types = dict(dv.members)
    return [(m, types[m], arg, attr)
            for m, (arg, attr) in dv.attribute_members.items() if arg in mutated]


def _attribute_expr(argument: str, attribute: str) -> str:
    return f'symbolic_sizes({argument})' if attribute == 'sym_sizes' else f'{argument}.{attribute}()'


def _node_ctor_args(dv: OpDerivatives, f: NativeFunction,
                    core_result_var: str | None,
                    hoisted: bool = False) -> list[str]:
    """Ordered constructor arguments for the backward node."""
    arg_names = {a.name for a in f.args}
    # Manual nodes (empty formulas, hand-written structs) are not extended.
    args: list[str] = []
    out_index = ({n: i for i, n in enumerate(tuple_element_names(f))}
                 if f.cpp_return_kind == 'tuple' else {})
    pre_update = ({m for m, *_ in _hoisted_attributes(dv, f)} if hoisted else set())
    for m, _t in dv.members:
        if m in pre_update:
            args.append(f'std::move(*__tp_pre_{m})')
        elif m in dv.attribute_members:
            # A tensor the formulas only measure hands over that attribute.
            arg, attr = dv.attribute_members[m]
            args.append(_attribute_expr(arg, attr))
        elif m in dv.used_input_names:
            if (m == 'self' and f.base_name.endswith('_')
                    and any(a.name == 'self' for a in f.args)):
                # Pre-mutation capture is hoisted by the wrapper; the live
                # `self` already holds the update.
                args.append('__tp_original_self.value_or(Tensor())')
            else:
                args.append(m)
        elif m == 'result' and m not in out_index:
            expr = 'result'
            if dv.node_name == 'ReluBackward':
                expr += '.detach()'
            args.append(expr)
        elif m in out_index:
            # A tuple element, `result` included when an output carries that
            # name, is read out of the core call's tuple.
            expr = f'std::get<{out_index[m]}>({core_result_var or "core_result"})'
            if dv.node_name == 'ReluBackward':
                expr += '.detach()'
            if _t == 'int64_t' and tuple_element_cpp_types(f)[out_index[m]] == 'SymInt':
                # Saved as the integer it is by the time the node runs.
                expr += '.expect_int()'
            args.append(expr)
        else:
            args.append(m)
        readers = dv.conditional_members.get(m)
        if readers:
            # Kept only when an input whose gradient reads it wants one.
            arg_types = {a.name: a.type for a in f.args}
            wanted = " || ".join(
                f'({n}.has_value() && {n}->requires_grad())' if arg_types[n].is_opt
                else f'{n}.requires_grad()'
                for n in readers)
            args[-1] = f'(({wanted}) ? Tensor({args[-1]}) : Tensor())'
    return args


def _has_autograd(f: NativeFunction, derivatives: dict[str, OpDerivatives]) -> bool:
    return (
        f.func_name in derivatives
        or f.func_name == 'relu_'
        or f.func_name in _COMPOSITE_AUTOGRAD_WRAPPERS
    )


def _emit_requires_grad_detection(lines, f, skip=frozenset()):
    """Whether any input the derivatives cover wants a gradient; arguments
    in ``skip`` (declared non-differentiable) never make the output require
    one."""
    checks = []
    for a in f.args:
        if a.name in skip:
            continue
        t = a.type
        if t.is_tensor_like and not t.is_list and not t.is_opt:
            checks.append(f'{a.name}.requires_grad()')
        elif t.is_tensor_like and t.is_list:
            if t.list_elem_opt:
                checks.append(
                    f'std::any_of({a.name}.begin(), {a.name}.end(), '
                    '[](const std::optional<Tensor>& tensor) {'
                    ' return tensor.has_value() && tensor->requires_grad(); })')
            else:
                checks.append(
                    f'std::any_of({a.name}.begin(), {a.name}.end(), '
                    '[](const Tensor& tensor) { return tensor.requires_grad(); })')
        elif t.is_tensor_like and t.is_opt:
            checks.append(f'({a.name}.has_value() && {a.name}->requires_grad())')
    lines.append('    bool requires_grad = false;')
    if checks:
        cond = ' || '.join(checks)
        lines.append(
            '    if (GradMode::is_enabled() && !InferenceMode::is_enabled() '
            f'&& ({cond}) && !autograd_dispatch_excluded()) requires_grad = true;')


def _emit_leaf_checks(lines, f):
    for a in f.mutable_args:
        if a.type.is_mutable_ref:
            lines.append(f'    if (requires_grad && {a.name}.requires_grad()) {{')
            # views created by multi-output nodes (CreationMeta::
            # MULTI_OUTPUT_NODE) can never be mutated in-place; this fires
            # before the view-of-leaf / leaf checks.
            lines.append('        {')
            lines.append(
                f'            auto __tp_gf = tensorplay::tpx::impl::grad_fn({a.name});')
            lines.append(
                f'            if (__tp_gf && {a.name}.unsafeGetTensorImpl()->is_view() '
                '&& __tp_gf->is_multi_output_view()) {')
            lines.append(
                '                TP_THROW(RuntimeError, "Output ", '
                f'tensorplay::tpx::impl::output_nr({a.name}), " of ", '
                '__tp_gf->forward_op_name(), '
                '" is a view and is being modified inplace." '
                '" This view is the output of a function that returns multiple views." '
                '" Such functions do not allow the output views to be modified inplace." '
                '" You should replace the inplace operation by an out-of-place one.");')
            lines.append('            }')
            lines.append('        }')
            lines.append(
                f'        if (tensorplay::tpx::impl::is_view_of_leaf({a.name})) {{')
            lines.append(
                '            TP_THROW(RuntimeError, "a view of a leaf Variable '
                'that requires grad is being used in an in-place operation.");')
            lines.append('        }')
            lines.append(
                f'        if (tensorplay::tpx::impl::is_leaf({a.name})) {{')
            lines.append(
                '            TP_THROW(RuntimeError, "a leaf Variable that requires grad '
                'is being used in an in-place operation");')
            lines.append('        }')
            lines.append('    }')


def _emit_edges(lines, f, into: str | None = None):
    """Attach the inputs' edges to `grad_fn`, or gather them into the
    already declared vector `into`."""
    list_args = [a.name for a in f.args if a.type.is_tensor_like and a.type.is_list]
    tensor_args = [a.name for a in f.args if a.type.is_tensor_like]
    if into is not None and not list_args:
        lines.append(f'        {into} = collect_next_edges({", ".join(tensor_args)});')
    elif list_args:
        if into is not None:
            lines.append(f'        std::vector<Edge>& autograd_edges = {into};')
        else:
            lines.append('        std::vector<Edge> autograd_edges;')
        for a in f.args:
            t = a.type
            if t.is_tensor_like and t.is_list:
                lines.append(f'        for (const auto& tensor : {a.name}) {{')
                if t.list_elem_opt:
                    lines.append('            if (tensor.has_value()) collect_next_edges_helper(autograd_edges, *tensor);')
                else:
                    lines.append('            collect_next_edges_helper(autograd_edges, tensor);')
                lines.append('        }')
            elif t.is_tensor_like:
                if t.is_opt:
                    lines.append(f'        if ({a.name}.has_value()) collect_next_edges_helper(autograd_edges, *{a.name});')
                else:
                    lines.append(f'        collect_next_edges_helper(autograd_edges, {a.name});')
        if into is None:
            lines.append('        grad_fn->add_next_edge_list(std::move(autograd_edges));')
    else:
        lines.append(
            f'        grad_fn->add_next_edge_list(collect_next_edges({", ".join(tensor_args)}));')


def _view_replay_lambda(f: NativeFunction) -> str:
    view_input = f.view_input_name or "self"
    call_args = []
    for arg in f.args:
        if arg.name == view_input:
            call_args.append("__tp_view_base")
        elif arg.name != "requires_grad":
            call_args.append(arg.name)
    return (
        "[=](const Tensor& __tp_view_base) { return "
        f"tensorplay::tpx::ops::{f.cpp_name}({', '.join(call_args)}); }}"
    )


# arange/linspace/logspace infer from their scalar inputs; full infers from
# fill_value; randint/randperm/eye keep concrete integral/float defaults.
_DTYPE_GLOBAL_DEFAULT_OPS = {"rand", "randn", "empty", "zeros", "ones"}


def _emit_fw_derivative_block(lines, f, dv, native_op_names):
    """Forward-mode AD: compute the output tangent from the input tangents.

    Emitted after the core call (the formulas may read the op's own output)
    and before backward bookkeeping; the matching setter runs before the
    backward node saves the output, so a saved output keeps its tangent.
    The block is guarded so it only
    computes when at least one required input actually carries a tangent;
    inputs without one are zero-filled so the formula stays uniform.
    """
    outs = list(dv.fw_formulas)
    if outs != ["result"] or f.cpp_return_kind != 'value' \
            or cpp_return_type(f) != 'Tensor':
        raise ValueError(
            f"forward derivative for {f.func_name} requires a single Tensor "
            "result")
    required_inputs: list[str] = []
    for a in f.args:
        if a.name in dv.fw_required_tangent or a.name in dv.fw_required_primal:
            if a.type.is_opt or not a.type.is_tensor_like or a.type.is_list:
                raise ValueError(
                    f"forward derivative for {f.func_name} reads {a.name!r} "
                    "which must be a plain Tensor argument")
            required_inputs.append(a.name)
    lines.append(
        '    std::optional<Tensor> result_new_fw_grad_opt = std::nullopt;')
    lines.append('    if (__tp_fw_active) {')
    for n in dv.fw_required_tangent:
        lines.append(
            f'        auto {n}_t_raw = '
            'tensorplay::tpx::impl::to_non_opt_fw_grad('
            f'{n});')
        lines.append(
            f'        auto {n}_t = ({n}_t_raw.defined() || !{n}.defined()) '
            f'? {n}_t_raw : tensorplay::tpx::ops::zeros_like({n});')
    for n in dv.fw_required_primal:
        lines.append(
            f'        auto {n}_p = '
            'tensorplay::tpx::impl::to_non_opt_primal('
            f'{n});')
    tensor_syms = {a.name for a in f.args if a.type.is_tensor_like}
    tensor_syms |= {f'{n}_t' for n in dv.fw_required_tangent}
    tensor_syms |= {f'{n}_p' for n in dv.fw_required_primal}
    tensor_syms.add('result')
    rendered = render_formula(dv.fw_formulas['result'], tensor_syms, set(),
                              frozenset(), native_op_names)
    # With the tangents read, the formula's own ops carry none: a tangent of
    # a tangent at one level is not supported, and a bare input is a dual.
    lines.append('        tensorplay::tpx::impl::FwGradSuspend __tp_fw_formula;')
    lines.append(f'        result_new_fw_grad_opt = {rendered};')
    lines.append('    }')


# Forward-AD internals: their kernels attach or strip the tangent themselves.
_FW_OWN_TANGENT_OPS = frozenset({'_make_dual', '_fw_primal', '_unpack_dual'})
_FW_REFUSALS = frozenset({'refuse', 'refuse_out'})


def _fw_draws_random(f: NativeFunction) -> bool:
    return ('nondeterministic_seeded' in f.tags
            or any(a.type.kind == 'Generator' for a in f.args))


def _functional_twin(f: NativeFunction, funcs_by_base) -> NativeFunction | None:
    """The out-of-place operation an in-place update computes: same base
    name without the trailing underscore, same arguments, the updated one
    read instead of written.  Another written argument is allowed only where
    the operation draws random numbers: the twin then runs on the replayed
    stream and writes what the update writes again."""
    if not f.args or f.args[0].type.mutability is None or f.args[0].type.is_list:
        return None
    if any(a.type.mutability is not None for a in f.args[1:]) and not _fw_draws_random(f):
        return None
    want = ([(f.args[0].name, dataclasses.replace(f.args[0].type, mutability=None))]
            + [(a.name, a.type) for a in f.args[1:]])
    for g in funcs_by_base.get(f.base_name[:-1], ()):
        if (g.cpp_return_kind == 'value' and cpp_return_type(g) == 'Tensor'
                and [(a.name, a.type) for a in g.args] == want):
            return g
    return None


def _fw_plan(f: NativeFunction, dv: OpDerivatives | None,
             derivatives: dict[str, OpDerivatives], funcs_by_base,
             is_list_view: bool):
    """How the wrapper answers the tangent of its outputs.

    Returns (plan, args, twin): ``plan`` is ``'formula'``, ``'view'``,
    ``'inplace'``, ``'inplace_view'``, ``'rerun'``, ``'refuse'``,
    ``'refuse_out'`` (an out= variant) or None (not differentiable); ``args`` are the arguments whose tangents it reads;
    ``twin`` is the functional twin of an in-place update.
    """
    kind = f.cpp_return_kind
    if f.base_name in _FW_OWN_TANGENT_OPS:
        return None, [], None
    if f.is_out and (dv is None or not dv.fw_formulas):
        ins = [a for a in f.args if a.type.is_tensor_like and a.type.mutability is None]
        return ('refuse_out' if ins else None), ins, None
    if dv is None:
        if is_list_view:
            return 'view', [f.args[0]], None
        if f.func_name == 'relu_':
            twin = _functional_twin(f, funcs_by_base)
            if twin is not None and twin.func_name in derivatives:
                return 'inplace', [f.args[0]], twin
        return None, [], None
    if dv.fw_formulas:
        return 'formula', [a for a in f.args
                           if a.name in dv.fw_required_tangent
                           or a.name in dv.fw_required_primal], None
    if dv.non_differentiable_output:
        return None, [], None
    diff = [a for a in f.args
            if a.type.is_tensor_like and a.name not in dv.non_differentiable_args
            and (not dv.formulas or a.name in dv.formulas)]
    if not diff:
        return None, [], None
    only_self = [a.name for a in diff] == [f.args[0].name] and not f.args[0].type.is_list
    if kind == 'mut_ref' and f.base_name.endswith('_'):
        if f.is_view_op:
            return ('inplace_view' if only_self else 'refuse'), diff, None
        twin = _functional_twin(f, funcs_by_base)
        if twin is not None and twin.func_name in derivatives:
            return 'inplace', diff, twin
        return 'refuse', diff, None
    if (f.returns_view_of_input and kind == 'value' and cpp_return_type(f) == 'Tensor'
            and not f.mutable_args and only_self):
        return 'view', diff, None
    if kind == 'value':
        returns_tensors = cpp_return_type(f) == 'Tensor'
    elif kind == 'tuple':
        types = tuple_element_cpp_types(f)
        returns_tensors = ('Tensor' in types
                           and not any('Tensor' in t and t != 'Tensor' for t in types))
    elif kind == 'list':
        returns_tensors = cpp_return_type(f) == 'std::vector<Tensor>'
    else:
        returns_tensors = False
    if (returns_tensors and not f.mutable_args and not f.is_out
            and not any(a.type.is_list and a.type.is_opt for a in diff)):
        return 'rerun', diff, None
    return 'refuse', diff, None


def _fw_tangent_condition(args) -> str:
    checks = []
    for a in args:
        if a.type.is_list and a.type.is_opt:
            checks.append(f'({a.name}.has_value() && '
                          f'tensorplay::tpx::impl::any_fw_grad_defined(*{a.name}, /* level */ 0))')
        elif a.type.is_list:
            checks.append(f'tensorplay::tpx::impl::any_fw_grad_defined({a.name}, /* level */ 0)')
        else:
            checks.append(f'tensorplay::tpx::impl::is_fw_grad_defined({a.name}, /* level */ 0)')
    return ('tensorplay::tpx::ForwardADLevel::has_any_level() && ('
            + ' || '.join(checks) + ')')


def _fw_pack(vec: str, a) -> str:
    if a.type.is_list:
        return f'tensorplay::tpx::impl::append_tensors({vec}, {a.name});'
    if a.type.is_opt:
        return f'{vec}.push_back({a.name}.has_value() ? *{a.name} : Tensor());'
    return f'{vec}.push_back({a.name});'


def _emit_fw_pre_core(lines, f, plan, args, twin):
    """Before the kernel: whether a tangent is due, the refusal, the random
    streams a rerun replays, the twin's tangent of an in-place update; then
    tangent reads go off while the kernel runs."""
    if plan is None:
        return
    lines.append(f'    const bool __tp_fw_active = {_fw_tangent_condition(args)};')
    if plan in _FW_REFUSALS:
        lines.append('    if (__tp_fw_active) {')
        lines.append(f'        tensorplay::tpx::impl::refuse_forward_ad("{f.func_name}", '
                     f'{"true" if plan == "refuse_out" else "false"});')
        lines.append('    }')
        return
    random = plan in ('rerun', 'inplace') and _fw_draws_random(f)
    if random:
        gen = next((a.name for a in f.args if a.type.kind == 'Generator'), None)
        lines.append('    std::optional<tensorplay::tpx::impl::RandomReplay> __tp_fw_rng;')
        lines.append('    if (__tp_fw_active) {')
        lines.append('        std::vector<Tensor> __tp_fw_devices;')
        for a in f.args:
            if a.type.is_tensor_like and not (a.type.is_list and a.type.is_opt):
                lines.append('        ' + _fw_pack('__tp_fw_devices', a))
        lines.append(f'        __tp_fw_rng.emplace(__tp_fw_devices, {gen or "std::nullopt"});')
        lines.append('    }')
    if plan == 'inplace':
        call = (f'::tensorplay::tpx::ops::{twin.cpp_name}('
                f'{", ".join(a.name for a in f.args)})')
        if random:
            call = (f'__tp_fw_rng->run([&]() -> std::vector<Tensor> {{ '
                    f'return {{{call}}}; }})[0]')
        lines.append('    Tensor __tp_fw_inplace;')
        lines.append('    if (__tp_fw_active) {')
        lines.append(f'        __tp_fw_inplace = tensorplay::tpx::impl::fw_grad({call}, 0);')
        # A twin whose output takes no tangent (a comparison) leaves the
        # updated values independent of every tangent.
        lines.append('        if (!__tp_fw_inplace.defined()) '
                     f'__tp_fw_inplace = tensorplay::tpx::ops::zeros_like({f.args[0].name});')
        lines.append('    }')
    elif plan == 'inplace_view':
        lines.append('    Tensor __tp_fw_self_t;')
        lines.append(f'    if (__tp_fw_active) __tp_fw_self_t = '
                     f'tensorplay::tpx::impl::fw_grad({f.args[0].name}, 0);')
    lines.append('    std::optional<tensorplay::tpx::impl::FwGradSuspend> __tp_fw_off;')
    lines.append('    if (__tp_fw_active) __tp_fw_off.emplace();')


def _emit_fw_post_core(lines, f, plan, args, twin):
    """After the kernel: the tangents of a view or of a rerun through the
    backward, left in ``__tp_fw_tangents`` (one per output) for the setters
    that follow."""
    if plan not in ('view', 'rerun'):
        return
    kind = f.cpp_return_kind
    lines.append('    std::vector<Tensor> __tp_fw_tangents;')
    lines.append('    if (__tp_fw_active) {')
    if plan == 'view':
        base = f.args[0].name
        call = (f'::tensorplay::tpx::ops::{f.cpp_name}('
                + ', '.join('__tp_fw_base_t' if a.name == base else a.name for a in f.args)
                + ')')
        lines.append(f'        const Tensor __tp_fw_base_t = '
                     f'tensorplay::tpx::impl::fw_grad({base}, 0);')
        lines.append(f'        __tp_fw_tangents = {call};' if kind == 'list'
                     else f'        __tp_fw_tangents = {{{call}}};')
        lines.append('    }')
        return
    names = {a.name for a in args}
    lines.append('        std::vector<Tensor> __tp_fw_in;')
    call_args = []
    for a in f.args:
        if a.name not in names:
            call_args.append(a.name)
            continue
        lines.append(f'        const size_t __tp_at_{a.name} = __tp_fw_in.size();')
        lines.append('        ' + _fw_pack('__tp_fw_in', a))
        if a.type.is_list and a.type.list_elem_opt:
            call_args.append(f'tensorplay::tpx::impl::optional_tensors_from('
                             f'__tp_p, __tp_at_{a.name}, {a.name}.size())')
        elif a.type.is_list:
            call_args.append(f'tensorplay::tpx::impl::tensors_from('
                             f'__tp_p, __tp_at_{a.name}, {a.name}.size())')
        elif a.type.is_opt:
            call_args.append(f'tensorplay::tpx::impl::optional_from(__tp_p[__tp_at_{a.name}])')
        else:
            call_args.append(f'__tp_p[__tp_at_{a.name}]')
    call = f'::tensorplay::tpx::ops::{f.cpp_name}({", ".join(call_args)})'
    if kind == 'value':
        body = f'return {{{call}}};'
    elif kind == 'list':
        body = f'return {call};'
    else:
        elems = [f'std::get<{i}>(__tp_r)' if t == 'Tensor' else 'Tensor()'
                 for i, t in enumerate(tuple_element_cpp_types(f))]
        body = f'auto __tp_r = {call}; return {{{", ".join(elems)}}};'
    if _fw_draws_random(f):
        body = f'return __tp_fw_rng->run([&]() -> std::vector<Tensor> {{ {body} }});'
    lines.append('        __tp_fw_tangents = tensorplay::tpx::impl::fw_grads_from_backward(')
    lines.append(f'            "{f.func_name}", __tp_fw_in,')
    lines.append('            [&](const std::vector<Tensor>& __tp_p) -> std::vector<Tensor> {')
    lines.append(f'                {body}')
    lines.append('            });')
    lines.append('    }')


def _emit_fw_setters(lines, f, plan):
    """The outputs take their tangents before the backward node is built:
    the node saves its outputs, and a saved output keeps the tangent it has
    then, which a forward-over-reverse pass reads back."""
    kind = f.cpp_return_kind
    if plan == 'formula':
        lines.append('    if (result_new_fw_grad_opt.has_value() && result_new_fw_grad_opt.value().defined() && result.defined()) {')
        lines.append('        // The hardcoded 0 here tracks the single supported forward level.')
        lines.append('        tensorplay::tpx::impl::set_fw_grad(result, result_new_fw_grad_opt.value(), /* level */ 0, /* is_inplace_op */ false);')
        lines.append('    }')
    elif plan in ('view', 'rerun'):
        if kind == 'value':
            lines.append('    if (!__tp_fw_tangents.empty()) '
                         'tensorplay::tpx::impl::set_output_fw_grad(result, __tp_fw_tangents[0]);')
        elif kind == 'list':
            lines.append('    for (size_t __tp_i = 0; __tp_i < __tp_fw_tangents.size() '
                         '&& __tp_i < core_result.size(); ++__tp_i) {')
            lines.append('        tensorplay::tpx::impl::set_output_fw_grad('
                         'core_result[__tp_i], __tp_fw_tangents[__tp_i]);')
            lines.append('    }')
        else:
            for i, tt in enumerate(tuple_element_cpp_types(f)):
                if tt == 'Tensor':
                    lines.append(
                        f'    if (__tp_fw_tangents.size() > {i}) '
                        'tensorplay::tpx::impl::set_output_fw_grad('
                        f'std::get<{i}>(core_result), __tp_fw_tangents[{i}]);')
    elif plan == 'inplace':
        lines.append(f'    tensorplay::tpx::impl::set_inplace_fw_grad({f.args[0].name}, __tp_fw_inplace);')
    elif plan == 'inplace_view':
        # The tangent takes the same new geometry.
        rest = ', '.join(['__tp_fw_self_t'] + [a.name for a in f.args[1:]])
        lines.append('    if (__tp_fw_self_t.defined()) '
                     f'::tensorplay::tpx::ops::{f.cpp_name}({rest});')


def generate_tpx_ops_cpp(funcs: list[NativeFunction], *,
                         autocast_ops: set[str],
                         derivatives: dict[str, OpDerivatives],
                         native_op_names: set[str] = frozenset()) -> str:
    lines = [_CPP_INCLUDES.rstrip('\n'), '',
             'namespace tensorplay {', 'namespace tpx {', 'namespace ops {', '']

    funcs_by_base: dict[str, list[NativeFunction]] = {}
    for g in funcs:
        funcs_by_base.setdefault(g.base_name, []).append(g)

    seen: set[str] = set()
    for f in funcs:
        key = _dedup_key(f)
        if key in seen:
            continue
        seen.add(key)

        if _inline_forward_lines(f, autocast_ops, derivatives) is not None:
            # Defined inline in TPXOpsGenerated.h; no out-of-line body.
            continue

        arg_types = [cpp_arg_type(a.type) for a in f.args]
        ret = cpp_return_type(f)
        ret_void = ret == 'void'
        has_ag = _has_autograd(f, derivatives)
        _self_lv = f.self_arg()
        _is_list_view = (f.cpp_return_kind == 'list' and _self_lv is not None
                         and f.returns_view_of_input
                         and any(a.name == 'dim' for a in f.args))
        if _is_list_view and f.base_name not in _LIST_VIEW_OPS:
            raise ValueError(
                f"list view operator {f.func_name} has no autograd view rule"
            )

        _fw = _fw_plan(f, derivatives.get(f.func_name), derivatives, funcs_by_base,
                       _is_list_view)

        lines.append(f'{ret} {f.cpp_name}({", ".join(f"{t} {a.name}" for t, a in zip(arg_types, f.args))}) {{')

        if f.func_name == 'dropout':
            lines.append(
                '    return std::get<0>(native_dropout(input, p, '
                'std::optional<bool>(train)));')
            lines.append('}')
            lines.append('')
            continue

        # ---- factory global-default resolution ------------------------------
        # Factory-style ops (no leading tensor receiver) honor the global
        # default dtype/device when the caller leaves them unset, like
        # TensorOptions fallthrough.  arange-family dtypes are
        # excluded: their kernels infer from the scalar inputs instead.
        if not (f.args and f.args[0].type.is_tensor_like):
            for a in f.args:
                at = cpp_arg_type(a.type)
                if a.name == 'device' and at == 'std::optional<Device>':
                    lines.append(
                        '    if (!device.has_value()) '
                        'device = globalContext().defaultDevice();')
                elif (a.name == 'dtype' and f.base_name in _DTYPE_GLOBAL_DEFAULT_OPS
                      and at in ('DType', 'std::optional<DType>')):
                    if at == 'std::optional<DType>':
                        lines.append(
                            '    if (!dtype.has_value() || *dtype == DType::Undefined) '
                            'dtype = globalContext().defaultDType();')
                    else:
                        lines.append(
                            '    if (dtype == DType::Undefined) '
                            'dtype = globalContext().defaultDType();')

        if f.func_name in autocast_ops:
            _emit_autocast_block(lines, f, arg_types)

        # ---- gradient bookkeeping -----------------------------------------
        if has_ag or _is_list_view:
            _dv_nd = derivatives.get(f.func_name)
            _emit_requires_grad_detection(
                lines, f, _dv_nd.non_differentiable_args if _dv_nd is not None else frozenset())
            _emit_leaf_checks(lines, f)
            # In-place ops whose derivative references `self` must evaluate
            # the slope at the PRE-mutation value -- overloaded spellings
            # (mul_.Tensor) included.  Capture the clone before the core
            # call; _node_ctor_args splices it in.
            _dv_pre = derivatives.get(f.func_name)
            if (_dv_pre is not None and _dv_pre.formulas
                    and f.base_name.endswith('_')
                    and 'self' in _dv_pre.used_input_names
                    and any(a.name == 'self' for a in f.args)):
                lines.append('    std::optional<Tensor> __tp_original_self;')
                # Kept only for the slots that read it: no clone when none
                # of their inputs wants a gradient.
                _readers = _dv_pre.conditional_members.get('self')
                _cond = 'requires_grad'
                if _readers:
                    _types = {a.name: a.type for a in f.args}
                    _cond += ' && (' + ' || '.join(
                        f'({n}.has_value() && {n}->requires_grad())' if _types[n].is_opt
                        else f'{n}.requires_grad()' for n in _readers) + ')'
                lines.append(f'    if ({_cond}) {{')
                lines.append('        const bool __tp_prev_gm = GradMode::is_enabled();')
                lines.append('        GradMode::set_enabled(false);')
                lines.append('        __tp_original_self = self.clone();')
                lines.append('        GradMode::set_enabled(__tp_prev_gm);')
                lines.append('    }')

        # An update may reshape the tensor (squeeze_, t_): the edges and the
        # measured attributes describe it as the formulas' input, before.
        _hoist_inplace = has_ag and _records_inplace_update(f, derivatives)
        if _hoist_inplace:
            _dv_pre = derivatives.get(f.func_name)
            for m, mtype, arg, attr in (_hoisted_attributes(_dv_pre, f)
                                        if _dv_pre is not None else []):
                lines.append(f'    std::optional<{mtype}> __tp_pre_{m};')
                lines.append(f'    if (requires_grad) __tp_pre_{m} = {_attribute_expr(arg, attr)};')
            lines.append('    std::vector<Edge> __tp_inplace_edges;')
            lines.append('    if (requires_grad) {')
            _emit_edges(lines, f, into='__tp_inplace_edges')
            lines.append('    }')

        # ---- forward AD before the kernel ---------------------------------
        _emit_fw_pre_core(lines, f, *_fw)

        # ---- core invocation ----------------------------------------------
        core_call = _core_call_expr(f)

        kind = f.cpp_return_kind
        if kind in ('tuple', 'list'):
            lines.append(f'    auto core_result = {core_call};')
        elif kind == 'value':
            ret_type = cpp_return_type(f)
            if ret_type == 'Tensor':
                lines.append(f'    Tensor result = {core_call};')
            else:
                lines.append(f'    {ret_type} result = {core_call};')
        elif kind in ('mut_ref', 'void'):
            lines.append(f'    {core_call};')
            _dv_res = derivatives.get(f.func_name)
            if (kind == 'mut_ref' and has_ag and _dv_res is not None
                    and 'result' in _dv_res.used_output_names):
                # An in-place op's result is the updated tensor itself.
                _alias = next((a.name for a in f.mutable_args if a.type.is_mutable_ref),
                              f.args[0].name)
                lines.append(f'    const Tensor& result = {_alias};')

        if _fw[0] is not None and _fw[0] not in _FW_REFUSALS:
            lines.append('    __tp_fw_off.reset();')

        # ---- InplaceOrView semantics ---------------------------------------
        # InplaceOrView semantics: in-place ops bump their version counter
        # after mutation; view ops share the
        # base's counter so writes through the view are tracked.
        _self = f.self_arg()
        _is_inplace = (f.base_name.endswith('_') and _self is not None
                       and _self.name != 'requires_grad')
        _is_view = (not _is_inplace and _self is not None
                    and f.returns_view_of_input and kind == 'value')
        if _is_inplace:
            # Version bumping is owned exclusively by the below-autograd
            # redispatch layer (gen_api.py emits it inside
            # detail::redispatch_*); the InplaceOrView layer sits below the
            # autograd wrapper; bumping here again would
            # double-count under the default autograd path.
            pass
        elif _is_view:
            lines.append(
                f'    if (result.unsafeGetTensorImpl()->storage().is_same('
                f'{_self.name}.unsafeGetTensorImpl()->storage())) {{')
            lines.append(
                f'        result.unsafeGetTensorImpl()->share_version_counter('
                f'*{_self.name}.unsafeGetTensorImpl());')
            lines.append(
                '        result.unsafeGetTensorImpl()->set_is_view(true);')
            # The primal of a dual views it for the backward only: as a
            # forward view it would read the dual's tangent back.
            if has_ag and f.base_name != '_fw_primal':
                replay = _view_replay_lambda(f)
                metadata_change = 'true' if f.view_metadata_changes else 'false'
                lines.append('        if (requires_grad) {')
                lines.append(
                    '            tensorplay::tpx::impl::set_view_metadata('
                    f'result, {_self.name}, tensorplay::tpx::CreationMeta::DEFAULT, '
                    f'{replay}, {metadata_change});')
                lines.append('        }')
            lines.append('    }')

        # ---- forward-AD propagation -----------------------------------------
        _dv_fw = derivatives.get(f.func_name)
        if _dv_fw is not None and _dv_fw.fw_formulas:
            _emit_fw_derivative_block(lines, f, _dv_fw, native_op_names)
        _emit_fw_post_core(lines, f, *_fw)
        _emit_fw_setters(lines, f, _fw[0])

        # ---- backward node --------------------------------------------------
        dv_nd = derivatives.get(f.func_name)
        _non_diff = dv_nd is not None and dv_nd.non_differentiable_output
        if has_ag and not _non_diff:
            lines.append('    std::shared_ptr<Node> grad_fn;')
            lines.append('    if (requires_grad) {')
            if f.func_name == 'relu_':
                # In-place ReLU aliases its input; save a detached handle of
                # the mutated tensor as the mask without forming a cycle.
                lines.append(
                    f'        grad_fn = std::make_shared<ReluBackward>({f.args[0].name}.detach());')
            else:
                dv = derivatives[f.func_name]
                ctor_args = _node_ctor_args(dv, f, 'core_result', hoisted=_hoist_inplace)
                lines.append(
                    f'        grad_fn = std::make_shared<{dv.node_name}>({", ".join(ctor_args)});')
            if f.returns_view_of_input and _self is not None and kind == 'value':
                lines.append(
                    f'        grad_fn->set_view_fn(result.unsafeGetTensorImpl()->'
                    f'storage().is_same({_self.name}.unsafeGetTensorImpl()->storage()));')
            if _hoist_inplace:
                lines.append('        grad_fn->add_next_edge_list(std::move(__tp_inplace_edges));')
            else:
                _emit_edges(lines, f)
            lines.append('    }')
        elif _is_list_view:
            # Multi-output view op: one shared node and one output slot per
            # returned alias.
            node_name, fwd_name, multi_out = _LIST_VIEW_OPS[f.base_name]
            if f.func_name == 'split.sizes':
                fwd_name = 'SplitWithSizes'
            lines.append('    std::shared_ptr<Node> grad_fn;')
            lines.append('    if (requires_grad) {')
            lines.append(
                f'        grad_fn = std::make_shared<{node_name}>(dim, core_result);')
            lines.append('        grad_fn->set_view_fn(true);')
            lines.append(f'        grad_fn->set_forward_op_name("{fwd_name}");')
            if multi_out:
                lines.append('        grad_fn->set_multi_output_view(true);')
            _emit_edges(lines, f)
            lines.append('    }')

        # ---- result wrapping -----------------------------------------------
        if kind == 'tuple':
            tup_types = tuple_element_cpp_types(f)
            result_var = '__tp_wrapped_result'
            differentiable_outputs = (
                dv_nd.differentiable_outputs if dv_nd is not None else None)
            lines.append(f'    std::tuple<{", ".join(tup_types)}> {result_var};')
            for i, tt in enumerate(tup_types):
                lines.append(f'    std::get<{i}>({result_var}) = std::get<{i}>(core_result);')
                output_is_differentiable = (
                    differentiable_outputs is None
                    or differentiable_outputs[i])
                if (tt == 'Tensor' and has_ag and not _non_diff
                        and output_is_differentiable):
                    lines.append(
                        f'    if (requires_grad && std::get<{i}>({result_var}).defined() '
                        f'&& tensorplay::isFloatingOrComplexType(std::get<{i}>({result_var}).dtype())) {{')
                    lines.append(
                        f'        tensorplay::tpx::impl::set_grad_fn(std::get<{i}>({result_var}), grad_fn, {i});')
                    lines.append('    }')
            lines.append(f'    return {result_var};')
        elif kind == 'value':
            if any(a.name == 'requires_grad' for a in f.args):
                lines.append('    tensorplay::tpx::impl::set_requires_grad(result, requires_grad);')
            if has_ag and not _non_diff:
                lines.append('    if (requires_grad) tensorplay::tpx::impl::set_requires_grad(result, true);')
                lines.append('    if (requires_grad && result.defined()) {')
                lines.append('        tensorplay::tpx::impl::set_grad_fn(result, grad_fn);')
                lines.append('    }')
            lines.append('    return result;')
        elif kind == 'list':
            if _is_list_view:
                # `self` -- share the version counter, mark is_view, and
                # attach the shared backward node with a per-element
                # output_nr for unbind/split views.
                lines.append('    for (size_t __tp_i = 0; __tp_i < core_result.size(); ++__tp_i) {')
                lines.append(
                    f'        core_result[__tp_i].unsafeGetTensorImpl()->share_version_counter('
                    f'*{_self_lv.name}.unsafeGetTensorImpl());')
                lines.append(
                    '        core_result[__tp_i].unsafeGetTensorImpl()->set_is_view(true);')
                lines.append('        if (requires_grad) {')
                lines.append(
                    '            tensorplay::tpx::impl::set_view_metadata('
                    f'core_result[__tp_i], {_self_lv.name}, '
                    'tensorplay::tpx::CreationMeta::MULTI_OUTPUT_NODE);')
                lines.append(
                    '            tensorplay::tpx::impl::set_requires_grad(core_result[__tp_i], true);')
                lines.append(
                    '            tensorplay::tpx::impl::set_grad_fn(core_result[__tp_i], grad_fn, '
                    'static_cast<uint32_t>(__tp_i));')
                lines.append('        }')
                lines.append('    }')
            lines.append('    return core_result;')
        elif kind == 'mut_ref':
            alias = next((a.name for a in f.mutable_args if a.type.is_mutable_ref),
                         f.args[0].name)
            if has_ag and f.is_view_op and f.base_name.endswith('_'):
                # An update of the tensor's own geometry (t_, squeeze_)
                # writes no element of a base it may view: the view takes the
                # node as its history and the base keeps its own.
                lines.append(f'    if (requires_grad) tensorplay::tpx::impl::set_requires_grad({alias}, true);')
                lines.append(f'    if (requires_grad && {alias}.defined()) {{')
                lines.append(f'        tensorplay::tpx::impl::set_grad_fn({alias}, grad_fn);')
                lines.append('    }')
            elif has_ag:
                lines.append(f'    if (requires_grad) tensorplay::tpx::impl::set_requires_grad({alias}, true);')
                lines.append(f'    if (requires_grad && {alias}.defined()) {{')
                lines.append(
                    f'        if (tensorplay::tpx::impl::has_view_metadata({alias})) {{')
                lines.append(
                    f'            tensorplay::tpx::impl::rebase_history({alias}, grad_fn);')
                lines.append('        } else {')
                lines.append(f'            tensorplay::tpx::impl::set_grad_fn({alias}, grad_fn);')
                lines.append('        }')
                lines.append('    }')
            lines.append(f'    return {alias};')
        elif kind == 'void':
            lines.append('    return;')
        else:
            lines.append(f'    return {core_call};')
        lines.append('}')
        lines.append('')

    lines += ['} // namespace ops', '} // namespace tpx', '} // namespace tensorplay']
    return '\n'.join(lines)


def get_tpx_ops_signature(f: NativeFunction) -> str:
    return (f'{cpp_return_type(f)} (*)({", ".join(cpp_arg_type(a.type) for a in f.args)})')


def generate_autograd_registration(funcs: list[NativeFunction], *,
                                   derivatives: dict[str, OpDerivatives]) -> str:
    """Registers each generated wrapper as the AutogradCPU/CUDA kernel --
    TensorPlay's RegisterAutogradCPU.cpp / RegisterAutogradCUDA.cpp."""
    lines = [
        '// Generated by tools/codegen/main.py -- DO NOT EDIT',
        '#include "Dispatcher.h"',
        '#include "DispatchKey.h"',
        '#include "tensorplay/ops/TPXOpsGenerated.h"',
        '',
        'namespace tensorplay {',
        'namespace {',
        '',
        'struct RegisterTPXAutogradKernels {',
        '    RegisterTPXAutogradKernels() {',
        '        auto& D = Dispatcher::singleton();',
    ]
    registrations: list[str] = []
    adapters: list[str] = []
    seen: set[str] = set()
    for f in funcs:
        if not (_has_autograd(f, derivatives) or f.func_name in _REDISPATCHING_AUTOGRAD_KERNELS):
            continue
        if _dedup_key(f) in seen:
            continue
        seen.add(_dedup_key(f))
        # The dispatch table holds kernels with the dispatcher-stub ABI; the
        # adapter converts back to the public tpx::ops signature.
        kernel = f'autograd_kernel_{len(adapters)}'
        ret = cpp_return_type(f)
        # ``requires_grad`` is resolved before dispatch and is not part of
        # the kernel ABI.
        params = ', '.join(f'{stub_arg_type_for(f.base_name, a)} {a.name}'
                           for a in f.args if a.name != 'requires_grad')
        args = ', '.join('false' if a.name == 'requires_grad'
                         else rewrap_arg_expr(f.base_name, a, a.name) for a in f.args)
        body = f'::tensorplay::tpx::ops::{f.cpp_name}({args})'
        adapters.append(f'{ret} {kernel}({params}) {{ '
                        f'{"return " if ret != "void" else ""}{body}; }}')
        for key in ('AutogradCPU', 'AutogradCUDA', 'AutogradVulkan', 'AutogradMeta'):
            registrations.append(f'        D.registerKernel("{f.func_name}", DispatchKey::{key}, &{kernel});')
    struct_at = lines.index('struct RegisterTPXAutogradKernels {')
    lines[struct_at:struct_at] = adapters + ['']
    lines += registrations
    lines += [
        '    }',
        '};',
        '',
        'static RegisterTPXAutogradKernels g_register_tpx_autograd_kernels;',
        '',
        '} // namespace',
        '} // namespace tensorplay',
    ]
    return '\n'.join(lines)
