"""Autocast kernel generation (AutocastGenerated.cpp).

Policy lists mirror aten/src/ATen/autocast_mode.cpp's AT_FORALL_* macro
blocks, intersected with the operators available in native_functions.yaml.
Each listed op is wrapped and registered under AutocastCPU/AutocastCUDA; the
generated dispatch sites consult those keys before the autograd keys so casts
are autograd-exposed and inputs are saved for backward post-cast.
"""

from __future__ import annotations

from .api_types import cpp_arg_type, cpp_return_type
from .model import NativeFunction, Type

# AT_FORALL_LOWER_PRECISION_FP
AT_FORALL_LOWER_PRECISION_FP = [
    'mm', 'matmul', 'addmm', 'bmm', 'baddbmm',
    'conv1d', 'conv2d', 'conv3d',
    'conv_transpose2d', 'conv_transpose3d',
    'einsum', 'mv', 'scaled_dot_product_attention',
]

# AT_FORALL_FP32
AT_FORALL_FP32 = [
    'acos', 'asin', 'cosh', 'sinh', 'tan',
    'exp', 'expm1', 'log', 'log10', 'log1p', 'log2', 'rsqrt',
    'layer_norm', 'group_norm', 'nll_loss', 'mse_loss',
]

# AT_FORALL_FP32_SET_OPT_DTYPE
AT_FORALL_FP32_SET_OPT_DTYPE = ['softmax', 'log_softmax', 'sum', 'prod']

# AT_FORALL_PROMOTE
AT_FORALL_PROMOTE = ['atan2', 'addcdiv', 'addcmul', 'dot']

# CPU-only registrations (torch's KERNEL_CPU promote list).
AT_FORALL_PROMOTE_CPU_ONLY = ['cat', 'stack']

_POLICIES = {
    'lower_precision_fp': set(AT_FORALL_LOWER_PRECISION_FP),
    'fp32': set(AT_FORALL_FP32),
    'fp32_set_opt_dtype': set(AT_FORALL_FP32_SET_OPT_DTYPE),
    'promote': set(AT_FORALL_PROMOTE),
}


def autocast_policy_of(func_name: str, device_key: str | None = None) -> str | None:
    for policy, ops in _POLICIES.items():
        if func_name in ops:
            return policy
    if device_key == 'CPU' and func_name in AT_FORALL_PROMOTE_CPU_ONLY:
        return 'promote'
    return None


def autocast_registered_ops() -> set[str]:
    ops: set[str] = set()
    for s in _POLICIES.values():
        ops |= s
    ops |= set(AT_FORALL_PROMOTE_CPU_ONLY)
    return ops


def _arg_expr(policy: str, a) -> str:
    if policy in ('lower_precision_fp', 'fp32', 'promote'):
        return f'::tensorplay::autocast::cached_cast(__to_type, {a.name}, __device_type)'
    if policy == 'fp32_set_opt_dtype':
        if a.type.kind == 'DType':
            return f'::tensorplay::autocast::set_opt_dtype(DType::Float32, {a.name})'
        return a.name
    return a.name


def generate_autocast_registration(funcs: list[NativeFunction]) -> str:
    lines = [
        '// Generated by tools/codegen/gen.py -- DO NOT EDIT',
        '#include "Dispatcher.h"',
        '#include "DispatchKey.h"',
        '#include "Device.h"',
        '#include "DType.h"',
        '#include "autocast_mode.h"',
        '#include "autocast_cast.h"',
        '#include "tensorplay/ops/TPXOpsGenerated.h"',
        '',
        'namespace tensorplay {',
        'namespace {',
        '',
    ]

    kernels: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for f in funcs:
        name = f.func_name
        base = f.base_name
        if name in seen or f.skip_implementation:
            continue
        emitted_for_op = False
        for device_key in ('CPU', 'CUDA'):
            policy = autocast_policy_of(base, device_key)
            if policy is None:
                continue
            seen.add(name)
            kernel = f'autocast_kernel_{f.cpp_name}_{device_key.lower()}'
            kernels.append((name, kernel, device_key))

            sig_args = [f'{cpp_arg_type(a.type)} {a.name}' for a in f.args]
            ret = cpp_return_type(f)
            ret_void = ret == 'void'
            lines.append(f'{ret} {kernel}({", ".join(sig_args)}) {{')
            lines.append(f'    const DeviceType __device_type = DeviceType::{device_key};')
            lines.append('    ::tensorplay::autocast::ExcludeAutocastGuard no_autocast(__device_type);')

            call_str = ', '.join(_arg_expr(policy, a) for a in f.args)
            plain = ', '.join(a.name for a in f.args)
            call = f'::tensorplay::tpx::ops::{f.cpp_name}'

            if policy in ('lower_precision_fp', 'fp32'):
                if policy == 'lower_precision_fp':
                    lines.append(
                        '    const DType __to_type = ::tensorplay::autocast::'
                        'get_lower_precision_fp_from_device_type(__device_type);')
                else:
                    lines.append('    const DType __to_type = DType::Float32;')
                lines.append(f'    return {call}({call_str});' if not ret_void
                             else f'    {call}({call_str});')
            elif policy == 'fp32_set_opt_dtype':
                lines.append(
                    '    if (::tensorplay::autocast::firstarg_is_eligible('
                    f'__device_type, {plain})) {{')
                lines.append(f'        return {call}({call_str});' if not ret_void
                             else f'        {call}({call_str});')
                if ret_void:
                    lines.append('        return;')
                lines.append('    }')
                lines.append(f'    return {call}({plain});' if not ret_void
                             else f'    {call}({plain});')
            else:  # promote
                lines.append(
                    '    const DType __to_type = ::tensorplay::autocast::promote_type(')
                lines.append(
                    '        ::tensorplay::autocast::get_lower_precision_fp_from_device_type(__device_type),')
                lines.append(f'        __device_type, {plain});')
                lines.append(f'    return {call}({call_str});' if not ret_void
                             else f'    {call}({call_str});')
            lines.append('}')
            lines.append('')
            seen.add(name)

    lines += ['} // anonymous namespace', '']
    for device_key, lib_name in (('CPU', 'AutocastKernelsCPU'), ('CUDA', 'AutocastKernelsCUDA')):
        lines.append(f'TENSORPLAY_LIBRARY_IMPL({device_key}, {lib_name}) {{')
        for name, kernel, key in kernels:
            if key != device_key:
                continue
            lines.append(f'    m.impl("{name}", &{kernel});')
        lines.append('}')
        lines.append('')
    lines.append('} // namespace tensorplay')
    lines.append('')
    return '\n'.join(lines)
