"""Custom-operator code generator (TensorPlay's TORCH_LIBRARY analog).

Given a custom-op yaml in ATen schema grammar (the same parser as the main
pipeline -- vendored torchgen), emits:

* ``OpsGenerated.h``  -- declarations the user must implement, one per
  dispatch entry (``myop_cpu`` / ``myop_cuda``), exactly like implementing
  kernels for a TORCH_LIBRARY.
* ``OpsBinding.cpp``  -- dispatcher registration for every backend entry
  (mirroring ``TORCH_LIBRARY_IMPL(<ns>, CPU/CUDA)``), a device-resolving
  public wrapper per op that routes through p10's Dispatcher/DispatchStub,
  and a raw CPython ``PyInit_<module>`` exposing those wrappers through
  ``METH_FASTCALL | METH_KEYWORDS`` entry points on the shared
  ``tensorplay::python_c`` bridge surface (same shape as the main pipeline's
  gen_python_c.py layer; no pybind11 in generated code).

Usage (see cmake/TensorPlayCustomOp.cmake):
    python3 tensorplaygen.py --yaml ops.yaml --out_dir gen --module_name myops
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
for _p in (_ROOT,):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from tools.codegen.api_types import (binding_default, cpp_arg_type,  # noqa: E402
                                     cpp_return_type, py_default_for,
                                     sanitize_name)
from tools.codegen.gen_python_c import (_BRIDGE,  # noqa: E402
                                        _default_pyobject)
from tools.codegen.model import parse_native_yaml  # noqa: E402


def _stub_template(f):
    from tools.codegen.api_types import stub_arg_type
    parts = [cpp_return_type(f)]
    for a in f.args:
        if a.name == "requires_grad":
            continue
        parts.append(stub_arg_type(a.type))
    return ", ".join(parts)


def generate_header(funcs, module_name: str) -> str:
    lines = [
        f"// Generated by tensorplaygen for module '{module_name}' -- DO NOT EDIT",
        "#pragma once",
        '#include "Tensor.h"',
        '#include "Scalar.h"',
        '#include "Device.h"',
        "#include <optional>",
        "#include <string>",
        "#include <vector>",
        "#include <tuple>",
        "",
        "using namespace tensorplay;",
        "",
        "// Implement one function per dispatch entry, e.g. `myop_cpu`.",
        "// Signatures use TensorPlay C++ types; `Tensor?` schema args arrive",
        "// as std::optional<Tensor>.",
        "namespace tp_custom {",
        f"namespace {module_name} {{",
        "namespace impl {",
        "",
    ]
    for f in funcs:
        for dev, impl in sorted(f.dispatch.items()):
            ret = cpp_return_type(f)
            args = [f"{cpp_arg_type(a.type)} {a.name}" for a in f.args]
            lines.append(f"{ret} {impl}({', '.join(args)});")
    lines += ["", "} // namespace impl", f"}} // namespace {module_name}",
              "} // namespace tp_custom"]
    return "\n".join(lines)


def _dispatch_expr(f):
    first = next((a for a in f.args if a.type.is_tensor_like
                  and not a.type.is_opt and not a.type.is_list), None)
    lst = next((a for a in f.args if a.type.is_tensor_like and a.type.is_list), None)
    if first is not None:
        return f"{first.name}.device()"
    if lst is not None:
        return (f"({lst.name}.empty() ? Device(DeviceType::CPU) "
                f": {lst.name}[0].device())")
    return None


def _bridge_for(ctype: str):
    """_BRIDGE lookup, falling back to the const&-stripped spelling."""
    key = ctype.strip()
    if key in _BRIDGE:
        return _BRIDGE[key]
    if key.endswith("&"):
        key = key[:-1].strip()
    if key.startswith("const "):
        key = key[len("const "):].strip()
    return _BRIDGE.get(key)


def generate_binding(funcs, module_name: str) -> str:
    L = [
        f"// Generated by tensorplaygen for module '{module_name}' -- DO NOT EDIT",
        "#include <Python.h>",
        '#include "CPythonBridge.h"',
        '#include "Dispatcher.h"',
        '#include "DispatchKey.h"',
        '#include "Exception.h"',
        '#include "Tensor.h"',
        f'#include "OpsGenerated.h"',
        "",
        "#include <optional>",
        "#include <string>",
        "#include <type_traits>",
        "#include <vector>",
        "",
        "using namespace tensorplay;",
        "using namespace tensorplay::python_c;",
        "namespace tp_custom {",
        f"namespace {module_name} {{",
        "",
        "// ---- dispatcher registration (TORCH_LIBRARY_IMPL analog) ----",
        "namespace {",
        "struct RegisterKernels {",
        "    RegisterKernels() {",
        "        auto& D = Dispatcher::singleton();",
    ]
    for f in funcs:
        for dev, impl in sorted(f.dispatch.items()):
            key = "CPU" if dev.upper().startswith("CPU") else "CUDA"
            fn_type = (f"{cpp_return_type(f)} (*)("
                       f"{', '.join(cpp_arg_type(a.type) for a in f.args)})")
            cast = f"static_cast<{fn_type}>(&impl::{impl})"
            L.append(f'        D.registerKernel("{f.func_name}", '
                     f"DispatchKey::{key}, (KernelFunction){cast});")
    L += [
        "        }",
        "};",
        "static RegisterKernels g_register_kernels;",
        "} // namespace",
        "",
        "// ---- device-resolving public wrappers ----",
    ]

    tmpl_stub = None
    for f in funcs:
        ret = cpp_return_type(f)
        ret_void = ret == "void"
        sig_args = [f"{cpp_arg_type(a.type)} {a.name}" for a in f.args]
        call_args = [a.name for a in f.args]
        L.append(f"static {ret} {f.cpp_name}_dispatch({', '.join(sig_args)}) {{")
        dev = _dispatch_expr(f)
        if f.dispatch and dev is None:
            L.append(f'    TP_THROW(RuntimeError, "{f.cpp_name}: no Tensor argument");')
        elif f.dispatch:
            L.append("    static const OperatorHandle handle = "
                     f'Dispatcher::singleton().findHandle("{f.func_name}");')
            L.append(f"    DispatchKey key = computeDispatchKey({dev});")
            call = (f"DispatchStub<{_stub_template(f)}>::call(handle, key, "
                    f"{', '.join(call_args)})")
            L.append(f"    {'return ' + call + ';' if not ret_void else call + ';'}")
        else:
            L.append(f'    TP_THROW(NotImplementedError, "{f.cpp_name}: no backend");')
        L.append("}")
        L.append("")
    L += [f"}} // namespace {module_name}", "} // namespace tp_custom", ""]

    # ---- CPython METH_FASTCALL module (no pybind11; mirrors gen_python_c.py) ----
    # Kernels run with the GIL released, like upstream torch bindings.
    L += [
        "namespace {",
        "struct GilRelease {",
        "    PyThreadState* st;",
        "    GilRelease() : st(PyEval_SaveThread()) {}",
        "    ~GilRelease() { PyEval_RestoreThread(st); }",
        "};",
        "} // namespace",
        "",
    ]
    table: list[str] = []
    seen_names: set[str] = set()
    for f in funcs:
        prelude: list[str] = []
        slots = []                      # (pyname, bridge expr, default expr|None)
        n_pos = 0
        for ai, a in enumerate(f.args):
            ctype = cpp_arg_type(a.type)
            tpl = _bridge_for(ctype)
            if tpl is None:
                raise SystemExit(
                    f"tensorplaygen: {f.func_name}: argument '{a.name}' of C++ "
                    f"type '{ctype}' has no python_c bridge mapping; supported: "
                    + ", ".join(sorted(_BRIDGE)))
            dft = py_default_for(f, a, 'binding') or (
                binding_default(a.type, a.default) if a.default is not None else None)
            dflt = None
            if a.default is not None or dft is not None:
                expr = dft if dft is not None else binding_default(a.type, a.default)
                dflt = _default_pyobject(a, expr)
                if dflt == expr and a.type.is_list:
                    # int-list literal like std::vector<int64_t>{0,1}: build it
                    inner = expr[expr.find("{") + 1:expr.rfind("}")]
                    items = [s.strip() for s in inner.split(",") if s.strip()]
                    helper = f"pydflt_{f.cpp_name}_{ai}"
                    prelude.append(f"static PyObject* {helper}() {{")
                    prelude.append(f"    PyObject* v = PyList_New({len(items)});")
                    for j, item in enumerate(items):
                        prelude.append(
                            f"    PyList_SET_ITEM(v, {j}, PyLong_FromLongLong({item}LL));")
                    prelude.extend(["    return v;", "}", ""])
                    dflt = f"{helper}()"
            if not a.kwonly:
                n_pos += 1
            slots.append((sanitize_name(a.name), tpl, dflt, ctype))
        L.extend(prelude)
        pyname = f.cpp_name
        stem = pyname
        k = 0
        while pyname in seen_names:
            k += 1
            pyname = f"{stem}_{k}"
        seen_names.add(pyname)

        fn = f"pyop_{pyname}"
        nargs = len(slots)
        kwlist = ('static const char* kwlist[] = {'
                  + ", ".join(f'"{n}"' for n, _, _, _ in slots)
                  + ", nullptr};") if nargs else \
                 "static const char* kwlist[] = {nullptr};"
        L.append(f"static PyObject* {fn}(PyObject*, PyObject* const* args,")
        L.append(f"{' ' * len(fn)}                        Py_ssize_t nargs, PyObject* kwnames) {{")
        L.append("    try {")
        L.append(f"        {kwlist}")
        if nargs:
            L.append(f"        PyObject* slots[{nargs}];")
            L.append(f'        tpx_py_parse_into(args, nargs, kwnames, kwlist, '
                     f'{nargs}, "{f.func_name}", slots);')
        else:
            L.append(f'        tpx_py_parse_into(args, nargs, kwnames, kwlist, '
                     f'0, "{f.func_name}", nullptr);')
        if n_pos < nargs:
            L.append(f"        if (nargs > {n_pos}) {{")
            L.append('            PyErr_Format(PyExc_TypeError, "%s: too many '
                     f'positional arguments", "{f.func_name}");')
            L.append("            return nullptr;")
            L.append("        }")
        for i, (name, tpl, dflt, ctype) in enumerate(slots):
            src = f"slots[{i}]"
            if dflt is not None:
                L.append(f"        static PyObject* k{i} = {dflt}; (void)k{i};")
                L.append(f"        PyObject* s_{name} = {src} ? {src} : k{i};")
            else:
                L.append(f"        PyObject* s_{name} = {src};")
            # Tensor args bind by reference: const form avoids one refcount
            # pair per argument; the mutable form makes in-place ops write
            # through to the caller's tensor instead of a copy.
            if ctype == "Tensor&":
                decl = "auto&"
            elif ctype in ("const Tensor&", "Tensor"):
                decl = "const auto&"
            else:
                decl = "auto&&"
            L.append(f"        {decl} v_{name} = {tpl.format(n=f's_{name}')};")
        call = ", ".join(f"v_{n}" for n, _, _, _ in slots)
        target = f"tp_custom::{module_name}::{f.cpp_name}_dispatch"
        kind = f.cpp_return_kind
        # Kernels run without the GIL (like upstream torch bindings), but
        # every PyObject-producing step -- argument conversion aside, result
        # wrapping AND error reporting -- must happen with the GIL held.
        # Scope the release tightly around the raw C++ call only.
        if kind == "void":
            L.append("        {")
            L.append("            GilRelease _nogil;")
            L.append(f"            {target}({call});")
            L.append("        }")
            L.append("        Py_RETURN_NONE;")
        elif kind == "mut_ref":
            # Returns a reference into the caller's tensor: park its address,
            # re-acquire the GIL, then wrap.
            L.append(f"        std::remove_reference_t<"
                     f"decltype({target}({call}))>* rp = nullptr;")
            L.append("        {")
            L.append("            GilRelease _nogil;")
            L.append(f"            rp = &({target}({call}));")
            L.append("        }")
            keep = f"tpx_py_keep_alive(s_{slots[0][0]});" if slots else ""
            if keep:
                L.append(f"        {keep}")
            L.append("        return tpx_py_wrap(*rp);")
        else:
            # Value-category results are materialized into an optional
            # inside the GIL-free region and wrapped after reacquiring it.
            L.append(f"        std::optional<decltype({target}({call}))> rout;")
            L.append("        {")
            L.append("            GilRelease _nogil;")
            L.append(f"            rout.emplace({target}({call}));")
            L.append("        }")
            if kind == "tuple":
                L.append("        return tpx_py_wrap_tuple(*rout);")
            elif kind == "list":
                L.append("        return tpx_py_wrap_list(*rout);")
            else:  # value
                L.append("        return tpx_py_wrap(*rout);")
        L += [
            "    } catch (const std::exception& e) {",
            "        tpx_py_set_error(e);",
            "        return nullptr;",
            "    }",
            "}",
            "",
        ]
        # Upstream exposes op schemas as the PyMethodDef docstring.
        doc = f.schema.replace("\\", "\\\\").replace('"', '\\"')
        table.append(f'    {{"{pyname}", (PyCFunction)(void*){fn}, '
                     f'METH_FASTCALL | METH_KEYWORDS, "{doc}"}},')

    L += [
        "static PyMethodDef " + f"{module_name}_methods[] = {{",
        *table,
        "    {nullptr, nullptr, 0, nullptr},",
        "};",
        "",
        f"static struct PyModuleDef {module_name}_module = {{",
        "    PyModuleDef_HEAD_INIT,",
        f'    "{module_name}",',
        f"    nullptr, -1, {module_name}_methods, nullptr, nullptr, nullptr, nullptr",
        "};",
        "",
        f"PyMODINIT_FUNC PyInit_{module_name}() {{",
        f"    return PyModule_Create(&{module_name}_module);",
        "}",
        "",
    ]
    return "\n".join(L)


def main(argv=None):
    ap = argparse.ArgumentParser(description="TensorPlay custom-op generator")
    ap.add_argument("--yaml", required=True)
    ap.add_argument("--out_dir", required=True)
    ap.add_argument("--module_name", default="custom_ops")
    args = ap.parse_args(argv)

    # Custom-op yamls are plain lists; reuse the native loader minus the
    # duplicate-schema gate semantics is fine either way.
    import yaml
    with open(args.yaml) as fh:
        data = yaml.safe_load(fh) or []
    tmp = Path(args.out_dir)
    tmp.mkdir(parents=True, exist_ok=True)
    tmp_yaml = tmp / f"_ops_{args.module_name}.yaml"
    tmp_yaml.write_text(yaml.safe_dump(data, sort_keys=False))

    funcs = [f for f in parse_native_yaml(str(tmp_yaml))]
    hdr = generate_header(funcs, args.module_name)
    cpp = generate_binding(funcs, args.module_name)
    h_path = os.path.join(args.out_dir, "OpsGenerated.h")
    c_path = os.path.join(args.out_dir, "OpsBinding.cpp")
    Path(h_path).write_text(hdr + "\n")
    Path(c_path).write_text(cpp + "\n")
    print(f"Generated {h_path} and {c_path}")


if __name__ == "__main__":
    main()
