"""Custom-operator code generator (TensorPlay's TORCH_LIBRARY analog).

Given a custom-op yaml in ATen schema grammar (the same parser as the main
pipeline -- vendored torchgen), emits:

* ``OpsGenerated.h``  -- declarations the user must implement, one per
  dispatch entry (``myop_cpu`` / ``myop_cuda``), exactly like implementing
  kernels for a TORCH_LIBRARY.
* ``OpsBinding.cpp``  -- dispatcher registration for every backend entry
  (mirroring ``TORCH_LIBRARY_IMPL(<ns>, CPU/CUDA)``), a device-resolving
  public wrapper per op that routes through p10's Dispatcher/DispatchStub,
  and a nanobind module exposing those wrappers.

Usage (see cmake/TensorPlayCustomOp.cmake):
    python3 tensorplaygen.py --yaml ops.yaml --out_dir gen --module_name myops
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
for _p in (_ROOT,):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from tools.codegen.api_types import binding_default, cpp_arg_type, cpp_return_type  # noqa: E402
from tools.codegen.model import parse_native_yaml  # noqa: E402


def _stub_template(f):
    from tools.codegen.api_types import stub_arg_type
    parts = [cpp_return_type(f)]
    for a in f.args:
        if a.name == "requires_grad":
            continue
        parts.append(stub_arg_type(a.type))
    return ", ".join(parts)


def generate_header(funcs, module_name: str) -> str:
    lines = [
        f"// Generated by tensorplaygen for module '{module_name}' -- DO NOT EDIT",
        "#pragma once",
        '#include "Tensor.h"',
        '#include "Scalar.h"',
        '#include "Device.h"',
        "#include <vector>",
        "#include <tuple>",
        "",
        "// Implement one function per dispatch entry, e.g. `myop_cpu`.",
        "// Signatures use TensorPlay C++ types; `Tensor?` schema args arrive",
        "// as std::optional<Tensor>.",
        "namespace tp_custom {",
        f"namespace {module_name} {{",
        "namespace impl {",
        "",
    ]
    for f in funcs:
        for dev, impl in sorted(f.dispatch.items()):
            ret = cpp_return_type(f)
            args = [f"{cpp_arg_type(a.type)} {a.name}" for a in f.args]
            lines.append(f"{ret} {impl}({', '.join(args)});")
    lines += ["", "} // namespace impl", f"}} // namespace {module_name}",
              "} // namespace tp_custom"]
    return "\n".join(lines)


def _dispatch_expr(f):
    first = next((a for a in f.args if a.type.is_tensor_like
                  and not a.type.is_opt and not a.type.is_list), None)
    lst = next((a for a in f.args if a.type.is_tensor_like and a.type.is_list), None)
    if first is not None:
        return f"{first.name}.device()"
    if lst is not None:
        return (f"({lst.name}.empty() ? Device(DeviceType::CPU) "
                f": {lst.name}[0].device())")
    return None


def generate_binding(funcs, module_name: str) -> str:
    L = [
        f"// Generated by tensorplaygen for module '{module_name}' -- DO NOT EDIT",
        '#include "Dispatcher.h"',
        '#include "DispatchKey.h"',
        '#include "Exception.h"',
        '#include <nanobind/nanobind.h>',
        '#include <nanobind/stl/vector.h>',
        '#include <nanobind/stl/optional.h>',
        '#include <nanobind/stl/tuple.h>',
        '#include "Tensor.h"',
        f'#include "OpsGenerated.h"',
        "",
        "namespace nb = nanobind;",
        "using namespace tensorplay;",
        "namespace tp_custom {",
        f"namespace {module_name} {{",
        "",
        "// ---- dispatcher registration (TORCH_LIBRARY_IMPL analog) ----",
        "namespace {",
        "struct RegisterKernels {",
        "    RegisterKernels() {",
        "        auto& D = Dispatcher::singleton();",
    ]
    for f in funcs:
        for dev, impl in sorted(f.dispatch.items()):
            key = "CPU" if dev.upper().startswith("CPU") else "CUDA"
            fn_type = (f"{cpp_return_type(f)} (*)("
                       f"{', '.join(cpp_arg_type(a.type) for a in f.args)})")
            cast = f"static_cast<{fn_type}>(&impl::{impl})"
            L.append(f'        D.registerKernel("{f.func_name}", '
                     f"DispatchKey::{key}, (KernelFunction){cast});")
    L += [
        "        }",
        "    }",
        "};",
        "static RegisterKernels g_register_kernels;",
        "} // namespace",
        "",
        "// ---- device-resolving public wrappers ----",
    ]

    tmpl_stub = None
    for f in funcs:
        ret = cpp_return_type(f)
        ret_void = ret == "void"
        sig_args = [f"{cpp_arg_type(a.type)} {a.name}" for a in f.args]
        call_args = [a.name for a in f.args]
        L.append(f"static {ret} {f.cpp_name}_dispatch({', '.join(sig_args)}) {{")
        dev = _dispatch_expr(f)
        if f.dispatch and dev is None:
            L.append(f'    TP_THROW(RuntimeError, "{f.cpp_name}: no Tensor argument");')
        elif f.dispatch:
            L.append("    static const OperatorHandle handle = "
                     f'Dispatcher::singleton().findHandle("{f.func_name}");')
            L.append(f"    DispatchKey key = computeDispatchKey({dev});")
            call = (f"DispatchStub<{_stub_template(f)}>::call(handle, key, "
                    f"{', '.join(call_args)})")
            L.append(f"    {'return ' + call + ';' if not ret_void else call + ';'}")
        else:
            L.append(f'    TP_THROW(NotImplementedError, "{f.cpp_name}: no backend");')
        L.append("}")
        L.append("")
    L += [f"}} // namespace {module_name}", "} // namespace tp_custom", ""]

    # ---- nanobind module ----
    L += [f"NB_MODULE({module_name}, m) {{"]
    for f in funcs:
        L.append(f'    m.def("{f.cpp_name}", '
                 f"&tp_custom::{module_name}::{f.cpp_name}_dispatch,")
        for a in f.args:
            dft = ""
            raw = a.default
            if raw is not None or f.pydefaults.get(a.name):
                val = f.pydefaults.get(a.name) or raw
                val_nb = ("\"" + val.strip("'\"") + "\"" if a.type.kind == "str"
                          else ("true" if val in ("True", "true") else
                                "false" if val in ("False", "false") else
                                "std::nullopt" if val == "None" else
                                f"std::vector<int64_t>{val[1:-1]}" if (
                                    val.startswith("[") and a.type.is_list) else val))
                dft = f" = {val_nb}"
            L.append(f'          "{a.python_name}"_a{dft},')
        L.append("          nb::rv_policy::move);")
    L += ["}", ""]
    return "\n".join(L)


def main(argv=None):
    ap = argparse.ArgumentParser(description="TensorPlay custom-op generator")
    ap.add_argument("--yaml", required=True)
    ap.add_argument("--out_dir", required=True)
    ap.add_argument("--module_name", default="custom_ops")
    args = ap.parse_args(argv)

    # Custom-op yamls are plain lists; reuse the native loader minus the
    # duplicate-schema gate semantics is fine either way.
    import yaml
    with open(args.yaml) as fh:
        data = yaml.safe_load(fh) or []
    tmp = Path(args.out_dir)
    tmp.mkdir(parents=True, exist_ok=True)
    tmp_yaml = tmp / f"_ops_{args.module_name}.yaml"
    tmp_yaml.write_text(yaml.safe_dump(data, sort_keys=False))

    funcs = [f for f in parse_native_yaml(str(tmp_yaml))]
    hdr = generate_header(funcs, args.module_name)
    cpp = generate_binding(funcs, args.module_name)
    h_path = os.path.join(args.out_dir, "OpsGenerated.h")
    c_path = os.path.join(args.out_dir, "OpsBinding.cpp")
    Path(h_path).write_text(hdr + "\n")
    Path(c_path).write_text(cpp + "\n")
    print(f"Generated {h_path} and {c_path}")


if __name__ == "__main__":
    main()
